### ISSUE TITLE
possible speedup opportunity in _rrd_updatex in rrd_update.c

### ISSUE THREAD

**Issue by PlasmaHH** [oetiker/rrdtool-1.x#1005]
Hi, I am (ab)using rrdtool to try to write a lot of data and every bit of performance helps. During that I found that in _rrd_updatex it loops through the passed argv and does a copy before passing that copy to process_arg and immediately after it frees the copy again. I made the input parameter of process_arg pointer-to-const (and all those that it gets passed to too) to try to verify that nobody wants to write to it all the way down and it compiles and runs.

There does not seem to be any reason why this copy needs to be done, so it could as well just pass the arguments around.

PS: are there any plans to provide an API where I can give in int:double pairs right away? or did I overlook an existing one? as it is now I have to format as strings just to have rrdlib parse it again...

**Comment by oetiker** [comment]
how much performance do you gain by such a change, also how much by skipping the transformation ? in my experience rrdtool is io bound to such an extent that optimizations at the cpu level seem to have little to no effect ...

**Comment by PlasmaHH** [comment]
Let me give a bit of context. I am writing statistics data from 270000 sources into that much files (on multiple servers). Once per second. Think of collects on steroids. Obviously this doesn't work to write that often so I dynamically cache many GB of data and flush it regularly to disk. Depending on circumstances this means about 15000 values per write. Due to mmap, lots of ram for caching (and maybe SSDs too) this means the process is less IO bound than traditional usage. Quantifying this is a bit hard, but I get maybe 5-10 less CPU usage which helps one of the systems to go from a state of barely being able to keep up to be "ok-ish" for the workload it has to do

**Comment by TheWitness** [comment]
I would suggest you measure stime, utime and rtime, both before and after the change.  That will be enlightening.

**Comment by PlasmaHH** [comment]
> I would suggest you measure stime, utime and rtime, both before and after the change. That will be enlightening.

In principle you are right, but as I do not have a way to artificially create that workload on an otherwise undisturbed system, all I can do is compare these statistics about those values from the past (which is what is mainly stored in these files) with those after the change, try to normalize for workload and then eyeball the result, which is where I arrived at the 5-10% cpu reduction mark (on the sum of kernel and user jiffies)

**Comment by TheWitness** [comment]
Where is your pull request?
