### ISSUE TITLE
rrdcaches no work on freebsd correctly or  something with my setup is wrong

### ISSUE THREAD

**Issue by kristoferus75** [oetiker/rrdtool-1.x#1018]
Hi !

I use librenms and also rrdcached on freebsd 12.0-RELEASE-p5
But for me it seems thet rrdcached not work correctly !

rrdcached version 1.7.0

in /etc/rc.conf

```
rrdcached_enable="YES"
rrdcached_flags="-l /var/run/rrdcached.sock -L 172.30.31.25:42217 -p /var/run/rrdcached.pid -m 664 -w 1800 -z 900 -f 3600 -s www -U librenms -G librenms -B -R -j /var/tmp -t 4 -F -b
/rrd/"

```
Because if look in the var/tmp directory there are only small journal files  that not really grow : 

```
-rw-r--r--   1 librenms       wheel            44M Jun 16 16:27 rrd.journal.1560691630.858588
-rw-r--r--   1 librenms       wheel            15M Jun 16 16:46 rrd.journal.1560695230.92517
```
Here the librenms config:
```
### Enable this to use rrdcached. Be sure rrd_dir is within the rrdcached dir
### and that your web server has permission to talk to rrdcached.
#$config['rrdcached']    = "unix:/var/run/rrdcached.sock";
$config['rrdcached']    = "172.30.31.25:42217";
$config['rrd_dir'] = "/rrd";
```
What is wrong ? -> should the files grow ?
If i use only the sock the graphs doesnt work ?!

Thanks for the help !

kind regards

kirstoferus75

**Comment by c72578** [comment]
Could you solve this issue on your system?

**Comment by kristoferus75** [comment]
Hi !
rrdcached work already correct ! It was only from my college and me a misunderstanding how rrdcached work !

thanks 

kind regards kristoferus75
