### ISSUE TITLE
rrd files created on raspbian (armv7l) can't be opened in other systems (armbian aarch64, OSX Mojave)

### ISSUE THREAD

**Issue by podarok** [oetiker/rrdtool-1.x#1042]
**Describe the bug**
I'm going to migrate from raspbian to armbian and found files can't be opened

**To Reproduce**
1. Install rrdtool in raspbian
2. Create rrd file
3. Copy file to armbian
4. Run rrdtool info file.rrd and find `reached EOF while loading header rrd->ds_def` error

**Expected behavior**

**Screenshots**
opened file

**Desktop (please complete the following information):**
 - OS: armbian, OSX
 - Version 1.7.1

**Comment by c72578** [comment]
To transfer an RRD between architectures, follow these steps [1]:
1. On the same system where the RRD was created, use rrdtool dump to export the data to XML format.
2. Transfer the XML dump to the target system.
3. Run rrdtool restore to create a new RRD from the XML dump. See rrdrestore for details.

[1] https://oss.oetiker.ch/rrdtool/doc/rrddump.en.html
