### ISSUE TITLE
Show only the higher part of the Y-axis.

### ISSUE THREAD

**Issue by eager-2-learn** [oetiker/rrdtool-1.x#1070]
The use of a disk fluctuated between 90 % and 95 %.
Nagiosgraph shows with RRD an Y-axis from 0 % to 100%.
Therefor the fluctuation in the line is very small.

Is it possible to show only the Y-axis part from 85 % to 100 %,
to see more fluctuation in the line?

A logarithmic Y-axis is not a good work-around.

Support RRD this functionality?

**Comment by oetiker** [comment]
yes you can set the lower limit of the y axis accordingly ... but please, use stackoverflow for support questions

**Comment by eager-2-learn** [comment]
Thanks
