### ISSUE TITLE
Cross Site Scripting (XSS) in rrdcgi

### ISSUE THREAD

**Issue by marcinguy** [oetiker/rrdtool-1.x#1073]
**Describe the bug**
Cross Site Scripting (XSS) in rrdcgi if debug is enabled

https://github.com/oetiker/rrdtool-1.x/blob/master/src/rrd_cgi.c#L1437

**To Reproduce**
You can send request as a key, value being <script>alert(1)</script>

**Expected behavior**
Escaped output

**Screenshots**
N/A

Please confirm/deny and fix.

Tested it in offline mode, didn't setup the solution and CGI with webserver, but the bug seems to be there.

**Comment by oetiker** [comment]
The point of debug mode is to figure what is going wrong with your application. If the output of debug mode is altered, this makes it harder to use it for its purpose ... debug mode is inherently non secure ...
