### ISSUE TITLE
Segmentation fault in rrd_graph:print_calc when vidx is -1 on GF_VRULE

### ISSUE THREAD

**Issue by neirbowj** [oetiker/rrdtool-1.x#1078]
**Describe the bug**

munin-cron intermittently exits with a SIGSEGV. Upon examination of the backtrace, the fault occurs in inside `librrd.so` in [`rrd_graph:print_calc` when `im->gdes[i].gf==GF_VRULE` and `vidx==-1`](https://github.com/oetiker/rrdtool-1.x/blob/v1.7.2/src/rrd_graph.c#L2047).

**To Reproduce**

I cannot reproduce this bug on purpose (yet). With munin-cron running every five minutes, it might happen a few times a day (1-6) and then go several days without happening at all. I don't understand what the trigger is.

**Expected behavior**

Don't segfault.

**Screenshots**

With guidance, I would be glad to work on extracting more useful information from a core dump. I have not used rrdtool directly before, so it's hard for me to do better than brute force to make progress at this point.

**Desktop (please complete the following information):**

Server, actually.

 - OS: FreeBSD 12.1-RELEASE-p1 amd64
 - Browser: N/A
 - Version: rrdtool 1.7.2, perl 5.30.1, munin 2.0.56

**Smartphone (please complete the following information):**

 N/A

**Additional context**

None.

**Comment by oetiker** [comment]
if you open the core file with gdb and then call 'bt' to see where the crash happens exactly that might help ... also interesting would be to know the arguments used to call rrdtool.

**Comment by neirbowj** [comment]
As reported above, the crash happens at line 2047 of rrd_graph.c when `vidx` is -1.

```
2045        case GF_VRULE:
2046            if (im->gdes[i].xrule == 0) {   /* again ... the legend printer needs it */
2047                im->gdes[i].xrule = im->gdes[vidx].vf.when;
2048            };
2049            graphelement = 1;
2050            break;
```

A few frames up the stack I find the following (slightly sanitized) arguments to `librrd.so.8:rrd_graph`, generated by the [bind9stats](https://github.com/shuque/bind9stats/tree/v0.30) plugin. It is running on an authoritative server which does not perform recursive resolution, and apparently does not report a value for this (and several other similar) mesurands.

```
(lldb) parray `argc` argv
(char **) $2 = 0x00000008034c0800 {
  (char *) [0] = 0x0000000801bab9ed ""
  (char *) [1] = 0x0000000802e44f00 "--title"
  (char *) [2] = 0x0000000803731120 "BIND [05] Resolver Outgoing Queries - by day"
  (char *) [3] = 0x0000000802e44f08 "--start"
  (char *) [4] = 0x0000000802e44d88 "-2000m"
  (char *) [5] = 0x0000000802e44f10 "-l"
  (char *) [6] = 0x0000000802e44f18 "0"
  (char *) [7] = 0x000000080392dce0 "--vertical-label"
  (char *) [8] = 0x00000008036d0c60 "Count/sec"
  (char *) [9] = 0x000000080371e150 "--slope-mode"
  (char *) [10] = 0x000000080371e130 "--height"
  (char *) [11] = 0x0000000802e44f20 "175"
  (char *) [12] = 0x0000000802e44f28 "--width"
  (char *) [13] = 0x0000000802e44f30 "400"
  (char *) [14] = 0x000000080371e630 "--imgformat"
  (char *) [15] = 0x0000000802e44f38 "PNG"
  (char *) [16] = 0x0000000802e44f40 "--lazy"
  (char *) [17] = 0x0000000802e44f48 "--font"
  (char *) [18] = 0x0000000803716180 "DEFAULT:0:DejaVuSans,DejaVu Sans,DejaVu LGC Sans,Bitstream Vera Sans"
  (char *) [19] = 0x0000000802e44f50 "--font"
  (char *) [20] = 0x00000008012233c0 "LEGEND:7:DejaVuSansMono,DejaVu Sans Mono,DejaVu LGC Sans Mono,Bitstream Vera Sans Mono,monospace"
  (char *) [21] = 0x0000000802e44f58 "--color"
  (char *) [22] = 0x000000080371e730 "BACK#F0F0F0"
  (char *) [23] = 0x0000000802e44f60 "--color"
  (char *) [24] = 0x000000080331ba10 "FRAME#F0F0F0"
  (char *) [25] = 0x0000000802e44f68 "--color"
  (char *) [26] = 0x00000008036d0890 "CANVAS#FFFFFF"
  (char *) [27] = 0x0000000802e44f70 "--color"
  (char *) [28] = 0x000000080371e2d0 "FONT#666666"
  (char *) [29] = 0x0000000802e44f78 "--color"
  (char *) [30] = 0x000000080371e020 "AXIS#CFD6F8"
  (char *) [31] = 0x00000008036750d0 "--color"
  (char *) [32] = 0x00000008036d0610 "ARROW#CFD6F8"
  (char *) [33] = 0x000000080371ea20 "--border"
  (char *) [34] = 0x00000008036750e0 "0"
  (char *) [35] = 0x0000000803a00420 "-W"
  (char *) [36] = 0x00000008036d0730 "Munin 2.0.56"
  (char *) [37] = 0x0000000803a00410 "--end"
  (char *) [38] = 0x000000080371e050 "1583901000"
  (char *) [39] = 0x0000000803715b40 "/usr/local/www/munin/DNS/neirbowj.example.com/dns_resolver_stats_qtype-day.png"
  (char *) [40] = 0x00000008036d0d30 "VRULE:0#999999"
  (char *) [41] = 0x000000080394e340 "COMMENT:Last update\\: Wed Dec 31 19\\:00\\:00 1969\\r"
}
```

**Comment by oetiker** [comment]
can you try if these arguments crash your rrdtool ? at least for me that seems to work fine ... looking at the code I can not see how it can get to -1

**Comment by neirbowj** [comment]
I could not get `rrdtool graph ...` to crash with these arguments either. Keep in mind that the `munin-cron` perl script does not crash every time it runs, and it's not clear what varies that triggers the bug sometimes but not others.

As for the code, I think I understand the following.

`vidx` is set near the top of `print_calc` in `rrd_graph.c` and not changed before the code where the crash occurs.

```
1834
1835     localtime_r(&now, &tmvdef);
1836     for (i = 0; i < im->gdes_c; i++) {
1837         vidx = im->gdes[i].vidx;
1838         switch (im->gdes[i].gf) {
```

The members of `im->gdes` are `graph_desc_t` structs that are initialized by `newGraphDescription` in `rrd_graph_helper.c`. There is only one place in that function where `vidx` is set (768). The nearby code (769 and 777) suggests that `vidx==-1 && gf==GF_VRULE` is a valid state to be in.

```
 758   /* check if we are reusing the vname */
 759   if (vname) {
 760     int idx=find_var(im, vname);
 761     dprintfparsed("got positional index %i for %s - \n",idx,vname);
 762
 763     /* some handling */
 764     if (bitscmp(PARSE_VNAMEDEF)) {
 765       if (idx>=0) {
 766         rrd_set_error("trying to reuse vname %s",vname); return NULL; }
 767     } else if (bitscmp(PARSE_VNAMEREF)) {
 768         gdp->vidx=idx;
 769         if (idx < 0){
 770            if (bitscmp(PARSE_VNAMEREFNUM)) {
 771               double val;
 772               char *x;
 773               int f=getDouble(vname,&val,&x);
 774               if (f) {
 775                  rrd_set_error("%s is not a vname nor a number",vname); return          NULL;
 776               }
 777               if (gf==GF_VRULE){
 778                  gdp->xrule=val;
 779               }
 780               else {
 781                  gdp->yrule=val;
 782               }
 783            }
 784            else {
 785                 rrd_set_error("vname %s not found",vname); return NULL;
 786            }
 787         }
 788     }
 789   }
```

**Comment by neirbowj** [comment]
That didn't take long.

Here's my patch to `rrd_graph_helper.c`, by the way.

```
     int idx=find_var(im, vname);
     dprintfparsed("got positional index %i for %s - \n",idx,vname);

+    if (idx < 0 && gf == GF_VRULE) {
+        /* this is actually an invalid state and we want a core dump */
+        abort();
+    }
+
     /* some handling */
     if (bitscmp(PARSE_VNAMEDEF)) {
       if (idx>=0) {
```
After the abort:

```
(lldb) p vname
(char *) $2 = 0x00000008036bf686 "1584033305"
```

I will need to rebuild glib with debugging enabled to be able to properly example `im->gdef_map`.

Also, it looks like the reason it didn't take long to reproduce is that it is aborting every time instead of only intermittently. Maybe this isn't the invalid case after all.

**Comment by oetiker** [comment]
sometimes these problems are a side effect of another memory error which does not itself cause an issue as no 'wrong' memory gets accessed ... running the thing with efence or some other memory debugger might help ... 

you are running 'master' to debug this, right ?

**Comment by neirbowj** [comment]
I am running 1.7.2. After glancing over the subsequent commits on master, nothing seems to be clearly related to this bug. Of course I could be missing something. I will look into what it would take to get a memory debugger involved.

**Comment by neirbowj** [comment]
I have confirmed that the condition required to trigger the crash, `gf==GF_VRULE && xrule==0 && vidx==-1`, is frequently true in [in this section of code](https://github.com/oetiker/rrdtool-1.x/blob/v1.7.2/src/rrd_graph.c#L2045-L2050) where the crash occurs.

```
2045         case GF_VRULE:
2046             if (im->gdes[i].xrule == 0) {   /* again ... the legend printer         needs it */
2047                 im->gdes[i].xrule = im->gdes[vidx].vf.when;
2048             };
2049             graphelement = 1;
2050             break;
```

That means that line 2047 routinely accesses a location outside the bounds of that array, and sometimes that causes a segfault. Over a sample of eight consecutive runs, the condition holds [12, 4, 4, 4, 4, 4, 8, 4] times, but none caused a crash.

**Comment by neirbowj** [comment]
I think I see the problem. This is a logic bug involving an unexpected value, not a memory bug.

In the code from `rrd_graph_helper.c` I quoted above, if `gf==GF_VRULE && vidx==-1`, then `xrule` is set to a double parsed from `vname` ([here](https://github.com/oetiker/rrdtool-1.x/blob/v1.7.2/src/rrd_graph_helper.c#L773-L779)), which can be zero. In the code from `rrd_graph.c` where the crash sometimes happens, `xrule==0` is treated as an uninitialized value ([here](https://github.com/oetiker/rrdtool-1.x/blob/v1.7.2/src/rrd_graph.c#L2046-L2048)).

I have drafted a patch and will begin testing shortly.
