### ISSUE TITLE
rrdtool resize does not work on zfs

### ISSUE THREAD

**Issue by bokutin** [oetiker/rrdtool-1.x#1082]
rrdtool resize does not work on zfs.

% rrdtool resize source.rrd 0 GROW 1
ERROR: Can't create 'resize.rrd': No error: 0
% ls -l resize.rrd
-rw-r--r--   1 root  wheel         0  4月 25 15:39 resize.rrd

The cause was that posix_fallocate returned EINVAL.

I created a patch.
https://bugs.freebsd.org/bugzilla/attachment.cgi?id=213772&action=edit

https://www.freebsd.org/cgi/man.cgi?query=posix_fallocate&apropos=0&sektion=2&manpath=FreeBSD+12.0-RELEASE&arch=default&format=html

     [EINVAL]		The len	argument was less than or equal	to zero, the
			offset argument	was less than zero, or the operation
			is not supported by the	file system.

**Comment by oetiker** [comment]
I bokutin, thanks ... can you make this into a PR ?
