### ISSUE TITLE
Memory leak(s) in rrdcached

### ISSUE THREAD

**Issue by mistotebe** [oetiker/rrdtool-1.x#1101]
**Describe the bug**
Running rrdcached with munin, memory usage keeps on growing, eventually (in a few week's time) eating all available memory. This still happens with current master.

**To Reproduce**
1. Compile and run rrdcached (or install from packages)
1. Set up munin to use rrdcached
1. Check in every day to see memory usage grow

**Expected behavior**
After a while, memory usage should stay the same.

**Screenshots**
Munin memory graph over the past year
![memory-year](https://user-images.githubusercontent.com/1913139/103515954-95fe4880-4e67-11eb-9a6b-117083bc0bd1.png)

**Raspberry Pi 3:**
 - OS: Raspbian stable
 - Version: 0.7.1-2 and git master

**Comment by mistotebe** [comment]
Can't run valgrind on this host as processing the inbound traffic would not finish in the 5 minute window, is there a more lightweight way to locate leaks?

**Comment by oetiker** [comment]
you could store away the calls and re-run on a more potent platform

**Comment by mistotebe** [comment]
Is there a description/example how to do that?

**Comment by oetiker** [comment]
There is no 'magic' ... alter the relevant code in munin to store the call arguments into a file, using the commandline syntax and then pipe them into rrdtool -

**Comment by mistotebe** [comment]
Yeah, I was hoping there was an rrd tool that recorded those in a replayable way. I'll see what I can do about setting up a recording proxy since I have no idea how to hack munin to record its operations, much less to make that usable. Might take a while...

**Comment by mistotebe** [comment]
I've picked up some leaks, see #1108, I'll see if there's more, but the RPi stack is quite noisy under valgrind.

**Comment by mistotebe** [comment]
The memory footprint has been remarkably stable since deploying the patch and I could not trigger anything useful the way I'm replaying traces with valgrind.
