### ISSUE TITLE
/debian/README refers to dead sources

### ISSUE THREAD

**Issue by miiichael** [oetiker/rrdtool-1.x#1104]
git.snow-crash.org doesn't exist any more, and the repo at git.tokkee.org hasn't been updated in more than six years (it only goes up to 1.4.8). I can only conclude that the Debian packaging bits are now elsewhere. :P

(my purpose of visit was to determine if not removing $PIDFILE after exiting is the right thing to do)

**To Reproduce**
1. visit https://github.com/oetiker/rrdtool-1.x/blob/master/debian/README

**Expected behavior**
To see current Debian packaging files, or a pointer to where I can find them.

**Desktop (please complete the following information):**
Not really relevant, but I am using Chrome on Debian...

**Comment by yrebrac** [comment]
https://sources.debian.org/src/rrdtool/1.7.2-3/debian/

**Comment by miiichael** [comment]
Thankyou, I found it too, but my point was that the README here needs updating...

**Comment by yrebrac** [comment]
You can update it yourself by submitting a pull request. Once you learn how takes no longer than opening this issue would have.
