### ISSUE TITLE
Is there a way to access the delta t (time in seconds since last poll) in a COMPUTE?

### ISSUE THREAD

**Issue by yrebrac** [oetiker/rrdtool-1.x#1105]
I'll give a concrete example. I've got a server that's returning a number in watts (power). Say it's 300W, so rrd will be storing ~300 since conceptionally this is a GAUGE value. So this does not seem useful if you want to work out your electricity _consumption_.

What I'd like to do is use a COMPUTE and the delta t to convert it to kilowatt hours (energy) and store that value. For example
```
PDN * ( t(last) - t(last-1) ) / 3600 / 1000 = kWh
300W after a 5-minute poll = ~0.025
```
I imagine these compute values as similar to ABSOLUTEs in that they resemble counters that reset on each read. Presumably they could be summed in a CDEF to get the total power consumed in any interval. Of course this method assumes the power load was fairly steady between measurements.

Is this possible or is there a good alternative?

**Comment by oetiker** [comment]
If you are reading wattage, I would suggest to store just that ... you can easily calculate the kWh later but multiplying the average wattage by the time elapsed ... the only important thing, in order to get good results is to fololow the Nyquist–Shannon sampling theorem suggesting that you should poll the watts by double the frequency of change ...

**Comment by yrebrac** [comment]
How do I get the time elapsed? I've had a look through the doco and it didn't leap out at me.

**Comment by oetiker** [comment]
you don't and you don't have to ... just store the value you read of the sensor ...

**Comment by yrebrac** [comment]
Ok, so say I store a GAUGE value of 300 every update, then I will generate a graph that says 300. CDEFs are for converting values, but I'm still not clear how I would convert this value to kWh. 

What if I stored an ABSOLUTE aswell? If I understand correctly it would be divided by the interval as it is stored, which would allow me to reconstruct the interval in a CDEF by GAUGE/ABSOLUTE.

**Comment by oetiker** [comment]
you could easily get watt seconds by doing:

```
VDEF:ws=watt,TOTAL
```

or if you must have kwh you would go

```
CDEF:watt36=watt,3.6,*
VDEF:kwh=watt36,TOTAL
```
you can then 'PRINT' or 'GPRINT' the value to get the total kwhs shown in the chart ...

**Comment by yrebrac** [comment]
Ok I realise I can get a total for a particular graph, but I need the kilowatt hours in a time series.

**Comment by yrebrac** [comment]
Thanks, didn't really get it until I tried it. Just had to make one adjustment to convert from Ws to kWh:`CDEF:watts36=watt,3600000,/`

![kWh](https://user-images.githubusercontent.com/5274504/106886789-67121580-6738-11eb-9cc7-b838b8d49eb1.png)

**Comment by oetiker** [comment]
great!
