### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [oetiker/rrdtool-1.x#1107]
The current last version is:
- 1.7.2 (2019-05-27)

In few weeks, 2 years.

The project is dead?

It is possible to release a new version?

Thanks in advance.

**Comment by oetiker** [comment]
yes this is on my list :)

**Comment by oetiker** [comment]
:-) yes now it might actually happen :)

**Comment by browniebraun** [comment]
Will keep my fingers crossed as I would love to see this project not being dead, too.

**Comment by TheWitness** [comment]
I had always planned to travel to Switzerland, but who knows if I'll ever be able to get there.  RRDtool is the "Swiss Original", and there should be a statue erected somewhere there in Tobi's name regardless.

**Comment by c72578** [comment]
RRDtool 1.8.0 has been released.
https://github.com/oetiker/rrdtool-1.x/releases

**Comment by Neustradamus** [comment]
@oetiker, @c72578: Thanks for this new version after 3 years.

Do not forget to update: https://oss.oetiker.ch/rrdtool/pub/?C=M;O=D.

On https://oss.oetiker.ch/rrdtool/download.en.html, there is a link to http://oss.oetiker.ch/rrdtool/pub/beta/?M=D which is a dead link.

**Comment by browniebraun** [comment]
Yeah, I believe I can say that the Cacti group is also happy about this.

**Comment by Neustradamus** [comment]
@oetiker, @c72578: It is possible to rename the title of each release with the number of version to easy search?
- https://github.com/oetiker/rrdtool-1.x/releases
- https://github.com/oetiker/mrtg/releases
- https://github.com/oetiker/SmokePing/releases
- ...

**Comment by Neustradamus** [comment]
@oetiker, @c72578: It is possible to rename the title of each release with the number of version to easy search?
- https://github.com/oetiker/rrdtool-1.x/releases
- https://github.com/oetiker/mrtg/releases
- https://github.com/oetiker/SmokePing/releases
- ...
