### ISSUE TITLE
ERROR: Cannot create temporary file in Powershell

### ISSUE THREAD

**Issue by schattennarr** [oetiker/rrdtool-1.x#1114]
I wrote a simple script in Powershell calling the .exe with a few parameters to create a .rrd file.
Something along the lines of
`C:\Users\m\Downloads\rrdtool\rrdtool.exe create $filename.rrd --start $start DS:cpu:GAUGE:7200:0:100 DS:memory:GAUGE:7200:0:100 RRA:AVERAGE:0.5:1:77`
this works within the cmd perfectly fine, however, it tells me in powershell ERROR: Cannot create temporary file
Even if I run the shell as Administrator I get the error. I also can create files in my Downloads via PS folder just fine, as well as in C:\Temp (where the .rrd is supposed to go)

I found this issue here https://stackoverflow.com/questions/61143165/cannot-create-temporary-file-at-usr-local-share-perl-5-22-1-rrdtool-oo-pm but I don't think it's the permissions on the folder. Just to be sure I actually changed the perms of the goal folder to no avail.
I'm running the latest version 1.7
Any ideas?

**Comment by c72578** [comment]
@schattennarr Could you please provide some details concerning the script? This should make it easier to reproduce the issue. A minimal example is sufficient. There are some unknowns in the current report. Which value has `$filename` got? Remark: The following works, when directly entered in PowerShell:
`.\rrdtool.exe create test.rrd --start 1626265558 DS:cpu:GAUGE:7200:0:100 DS:memory:GAUGE:7200:0:100 RRA:AVERAGE:0.5:1:77`

**Comment by c72578** [comment]
@schattennarr Please try putting double quotes around `"$filename.rrd"`
Example PowerShell Script with three working filename examples:
```PowerShell
$rrdtool_path = "C:\Users\m\Downloads\rrdtool\"

# Backslash in path
$filename1 = "C:\Temp\test1.rrd"
# Slash in path
$filename2 = "C:/Temp/test2.rrd"
# Backslash in path, no file extension
$filename3 = "C:\Temp\test3"

$start = Get-Date -UFormat %s

echo "rrdtool_path = $rrdtool_path"
echo "filename1 = $filename1"
echo "filename2 = $filename2"
echo "filename3 = $filename3"
echo "start = $start"

& $rrdtool_path\rrdtool.exe create $filename1 --start $start DS:cpu:GAUGE:7200:0:100 DS:memory:GAUGE:7200:0:100 RRA:AVERAGE:0.5:1:77
& $rrdtool_path\rrdtool.exe create $filename2 --start $start DS:cpu:GAUGE:7200:0:100 DS:memory:GAUGE:7200:0:100 RRA:AVERAGE:0.5:1:77

# Double quotes are required in case of filename3, which does not contain the file extension
# Otherwise: ERROR: Cannot create temporary file
& $rrdtool_path\rrdtool.exe create "$filename3.rrd" --start $start DS:cpu:GAUGE:7200:0:100 DS:memory:GAUGE:7200:0:100 RRA:AVERAGE:0.5:1:77
```

**Comment by c72578** [comment]
Feel free to reopen, if you still see an issue.
