### ISSUE TITLE
ERROR: short read while reading header rrd->stat_head

### ISSUE THREAD

**Issue by andermat8** [oetiker/rrdtool-1.x#1115]
**Describe the bug**
Using RRD tool 1.7.2 in Cacti and noticing this error for some of my graphs.  ERROR: short read while reading header rrd->stat_head.  Not sure what is causing this.  

**To Reproduce**
Cacti 2.16 running on Windows Server 2012.  Net-SNMP 5.7.3, PHP 7.4.16.  

**Expected behavior**
Interface utilization graphing.  This is happening with other graphs like memory, CPU, etc. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29753529/119363162-80a18380-bc7b-11eb-823f-8c6e87f0617c.png)

**Comment by andermat8** [comment]
Revert back to 1.4.5 seems to work but I have to delete and recreate the graphs affected.

**Comment by oetiker** [comment]
that short read was reproducible ?

**Comment by andermat8** [comment]
Hi Oetiker,

Yes,  I can reproduce on three different systems with different devices.  A couple of Linux systems and a Cisco switch.

**Comment by oetiker** [comment]
please provide the command line instructions to reproduce the error!

**Comment by andermat8** [comment]
This was in Cacti so I don't have a command-line but if you look at the image provided it shows the graph in diag mode with the command used.  Is there a character limitation by chance?

**Comment by oetiker** [comment]
there are character limitations, yes, but rrdtool enforces them ...

**Comment by andermat8** [comment]
So what does the short read error mean?

**Comment by oetiker** [comment]
this error is issued when rrdtool does not get the number of bytes requested when reading the header section ... 
this is not a condition which should be possible ... unless someone has messed with the internal structure of the rrd file ...

**Comment by andermat8** [comment]
Interesting.  The RRD file is zero bytes so that would explain the error.  I'm not that familiar with RRD Tool and really just use it in Cacti and to pull data via command-line from RRD files for interface utilization to export into another system.  If the image provided is not helpful, is there a command-line test you would like me to do?

**Comment by oetiker** [comment]
aah voila :) rrdfiles with 0 bytes size are not legal ... so getting an error indicating that the header could not be read makes quite a lot of sense :)
