### ISSUE TITLE
Max values not displaying properly on 1 day timeframe

### ISSUE THREAD

**Issue by bmfmancini** [oetiker/rrdtool-1.x#1123]
Hello There,

I have found a quirk that I am trying to find out if its by design or an issue 
Running RRDtool 1.4.8 on RHEL 

Today we noticed that when you select some graphs the Maximum value is off and seems averaged out even though
Here is the Last day graph you see a spike to 250 Mbps yet the max show 180

 past day graph 
![image](https://user-images.githubusercontent.com/13388748/125124476-22fbb600-e0c6-11eb-88bf-51d754813206.png)

Zoomed into spike

![125119650-6a327880-e0bf-11eb-97d9-8258f1c8d350](https://user-images.githubusercontent.com/13388748/125124071-83d6be80-e0c5-11eb-8008-6b667fd8d671.png)

Raw data from past day 
![125119911-bc739980-e0bf-11eb-80d1-b5daeffb2433](https://user-images.githubusercontent.com/13388748/125124072-83d6be80-e0c5-11eb-9515-6341bb5984e5.png)

raw data for zoomed in period
![125120290-402d8600-e0c0-11eb-9cdc-2585700084c9](https://user-images.githubusercontent.com/13388748/125124073-83d6be80-e0c5-11eb-9918-07a46f8ec446.png)

The data lines up shows 283Mbps for both the zoomed in and non zoomed in graphs yet the Max value shows differently
I haven't noticed this before is this by design or an issue ?

**Comment by oetiker** [comment]
what sometimes confuses people, is that there is a difference between consolidating using a averaging function and a max function ... it may be that you want to use a different consolidation function ... but there is nothing sinister going on, eating your maxima
