### ISSUE TITLE
XX/rrd is to small

### ISSUE THREAD

**Issue by Asterix785** [oetiker/rrdtool-1.x#1133]
Hello,

I have an error with rrdtool when upgrading the cacti tool.
The graphs are in the same location. But it fails to load them.
Here is a capture of the error:

Do you have any idea?

https://we.tl/t-RLLq6gOfjM

Cacti: 1.2.18
Rrdtool: 1.7.2
Windows server 2016

**Comment by c72578** [comment]
@Asterix785 Which RRDtool version did you use before the upgrade? Was there a change in bitness of RRDtool, e.g. 32-bit -> 64-bit?

**Comment by Asterix785** [comment]
Before I was in version 1.7.X and now I am in 1.7.X

**Comment by Asterix785** [comment]
I notice "32" in a dll on my old server
![image](https://user-images.githubusercontent.com/74353977/134683534-9b5c3fd4-8d4c-4da6-9a32-d6e85206a8d1.png)

**Comment by c72578** [comment]
@Asterix785 the screenshot of the files on the old server shows the files from `rrdtool-1.4.5-win32-vc2008.rar` [1], which was 32-bit. 

You can backup your previous `.rrd` files (`83.rrd, 84.rrd, 85.rrd, 656.rrd`). With rrdtool.exe (1.4.5) on your old server you should be able to export the data from these `.rrd` files. If desired, you can import the data into new .rrd files or create new, fresh .rrd files on the new server.

> How to check if a binary is 32 or 64 bit on Windows?
https://superuser.com/questions/358434/how-to-check-if-a-binary-is-32-or-64-bit-on-windows

[1] http://sdrik68.free.fr/cacti/

**Comment by Asterix785** [comment]
Thank you for your answer.
I made an export of a graph in xml with the command :
rrdtool dump C:\Apache24\htdocs\cacti\rra\3\8.rrd > test.xml

But I have a lot of rrd files in my cacti rra folder (about 500).

Is it possible to do this in a different way than by file?
Is it possible to enter the folder C:\Apache24\htdocs\cacti\rra\3
and to make the command :
rrdtool dump C:\Apache24htdocs\cacti\rra\3\*.rrd > test.xml

Because I have 98 sub-folders with rrd files.
![image](https://user-images.githubusercontent.com/74353977/134881218-b0a8aea2-5241-4af1-8370-b8c8477aba6c.png)

**Comment by Asterix785** [comment]
I have installed cygwin on my server. This allows me to run linux commands.

I try the following script:
#!/bin/bash
 
rm -rf /backup/cacti_xml/*
cd C:\Apache24\htdocs\cacti\rra\3
ls -1 *.rrd | awk '{print "rrdtool dump "$1" > /backup/cacti_xml/"$1".xml"}' | sh -x

But the rrdtool dump command is not recognized. I don't know how to add it, it's getting beyond my skills :) 

![image](https://user-images.githubusercontent.com/74353977/134907115-0d6231cc-ab15-4e87-896f-ffc9116039cd.png)

**Comment by c72578** [comment]
@Asterix785 
From Windows **`cmd`** you could do:

```cmd
REM rrdtool.exe is in C:\rrdtool\
md C:\backup\cacti_xml\
forfiles /P "C:\Apache24\htdocs\cacti\rra" /M "*.rrd" /S /C "cmd /c C:\rrdtool\rrdtool.exe dump @file > "C:\backup\cacti_xml\@FNAME.xml""
```
This will dump all `.rrd` files found in `C:\Apache24\htdocs\cacti\rra` recursively to `C:\backup\cacti_xml\`.
Remark: each `.rrd` file needs to have a different filename, otherwise you can add `@RELPATH`.
For further details using `forfiles`, see: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/forfiles

If you are only interested in the .rrd files in the subdirectory "3", `C:\Apache24\htdocs\cacti\rra\3`, you could use:
```cmd
md C:\backup\cacti_xml\
for %a in ("C:\Apache24\htdocs\cacti\rra\3\*.rrd") do C:\rrdtool\rrdtool.exe dump "%a" > "C:\backup\cacti_xml\%~na.xml"
```

If you prefer the bash script from above, inside cygwin:
> `ls -1 *.rrd | awk '{print "rrdtool dump "$1" > /backup/cacti_xml/"$1".xml"}' | sh -x`

You need to specifiy, where `rrdtool` is, otherwise it will not be found.

**Comment by Asterix785** [comment]
Thank you very much for your help! 
I will do the manipulation tomorrow at work.

**Comment by Asterix785** [comment]
The dump worked. I compressed the folder and transferred it to my new server.
I tried to modify your command to do the opposite:
forfiles /P "C:\backup\cacti_xml" /M "*.xml" /S /C "cmd /c C:\rrdtool\rrdtool.exe restore @file > "C:\backup\new\@FNAME.rrd"

But it doesn't seem to get the right xml file name.

![image](https://user-images.githubusercontent.com/74353977/135052034-48482a2b-ac75-42c1-be32-6e09e06a5cf0.png)

I would like to restore them to the C:\backup\new location before placing it in the cacti location.

![image](https://user-images.githubusercontent.com/74353977/135052160-7a3c5f2c-842d-4033-94bc-5c1f3e93dd6b.png)

I'm still looking upstream, I'll put the command if it works

**Comment by c72578** [comment]
@Asterix785 please remove the ">" from the restore command.
https://oss.oetiker.ch/rrdtool/doc/rrdrestore.en.html

**Comment by Asterix785** [comment]
I ran the command :

`forfiles /P "C:\backup\backup\cacti_xml" /M "*.xml" /S /C "cmd /c C:\rrdtool\rrdtool.exe restore @file @fname.rrd"`

The restoration is successful. I then copy and paste the rrd files in the original folder of the old cacti.

In order to keep the paths. The graphics are all back. 

Thank you very much for your help and responsiveness. I hope my problem can help other users.
