### ISSUE TITLE
rrdtool first returns a timestamp that is 0x100000000 too high on Windows

### ISSUE THREAD

**Issue by PBudmark** [oetiker/rrdtool-1.x#1140]
**Describe the bug**
rrdtool first returns a timestamp that is 0x100000000 too high on Windows

**To Reproduce**
Create a rrd like this 
`rrdtool create temp.rrd --start epoch+400000000 --step 60s DS:Outside:GAUGE:1800:-50:+80 RRA:AVERAGE:0.5:60s:10`
The problem can be seen already when no data is loaded,
rrdtool dump states first timestamp in rra is 399999420
rrdtool first states first timestamp in rra is 4694966716,
which is exactly 4294967296 (0x100000000) to big

Updating the rrd with values (two) makes no difference
`rrdtool update temp.rrd epoch+400000060@10.0`
`rrdtool update temp.rrd epoch+400000600@10.0`
rrdtool dump now states first timestamp in rra is 400000020
rrdtool first states first timestamp in rra is 4694967316,
which is still exactly 4294967296 (0x100000000) to big
 
**Expected behavior**
Equal or almost equal timestamps in dump and first

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 20H2
 - rrdtool-1.7.2_vs2017_x64 or rrdtool-1.7.2_vs2017

**Comment by c72578** [comment]
@PBudmark thanks for your report and for providing details to reproduce the issue.
Please find builds for testing, which include a fix, here:
https://github.com/oetiker/rrdtool-1.x/pull/1168#issuecomment-1086259258

**Comment by PBudmark** [comment]
I have run my tests on both provided builds and they work as intended regarding the issue, nothing else verified.
Thanks / Per.Ake
