### ISSUE TITLE
rrdtool dump not works with rrdcached

### ISSUE THREAD

**Issue by landy2005** [oetiker/rrdtool-1.x#1141]
**Describe the bug**
Man page said that rrdcached is supported by dump command, but really not works.

**To Reproduce**
check if rrd exist:
```
$ rrdtool last spb-sdn-local2/uptime.rrd --daemon 127.0.0.1:42217
1637163600
```
try dump:
```
$ rrdtool dump spb-sdn-local2/uptime.rrd --daemon 127.0.0.1:42217
ERROR: opening 'spb-sdn-local2/uptime.rrd': No such file or directory
```
(dump without rrdcached is works):
```
$ rrdtool dump /opt/observium/rrd/spb-sdn-local2/uptime.rrd |head
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rrd SYSTEM "https://oss.oetiker.ch/rrdtool/rrdtool.dtd">
<!-- Round Robin Database Dump -->
<rrd>
        <version>0003</version>
        <step>300</step> <!-- Seconds -->
        <lastupdate>1637163709</lastupdate> <!-- 2021-11-17 18:41:49 MSK -->
```

RRDtool on Ubuntu 20.04:
```
RRDtool 1.7.2  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Feb 26 2020 17:10:48
```

**Comment by thz** [comment]
There is no client or daemon handler implemented for `dump`. So I would say the bug is in the documentation: 
https://github.com/oetiker/rrdtool-1.x/blob/d8923c5c01904880c218fd94844eb8ea21f815f0/doc/rrdcached.pod?plain=1#L329
Where it says `dump` would be supported per rrdcached.
