### ISSUE TITLE
Problem with RPN: IF and GT

### ISSUE THREAD

**Issue by krystiankgb** [oetiker/rrdtool-1.x#1146]
I draw a graph and sometimes I get a big values on input so the graph isn't very usefull. I created a RPN to filter all greater values than 50 and replace that with 50: IF input > 50 then 50 else input.
CDEF:error_final=error,50,GT,50,error,IF

I can still see on my graph values like 200m.

Could you help me if the sentence is correct or not?

**Comment by oetiker** [comment]
Note that 200m == 0.2  (m stands for milli or 1/1000ths)
