### ISSUE TITLE
Wrong chart when using CDEF

### ISSUE THREAD

**Issue by Yufiel** [oetiker/rrdtool-1.x#1175]
**Describe the bug**
Only when using a CDEF the resulting chart is wrong. Even with CDEF:usedmegabytes=used,0,+

**To Reproduce**
1. Download the rrd file
2. Create the correct chart without CDEF:
`rrdtool graph disspace.png --full-size-mode -w 1128 -h 180 --start 1650434400 --end start+72000 --title '172.27.141.3: Disk space on /dev/sda2 ( tmp )' --vertical-label 'Disk space in MB' --lower-limit 0 DEF:used=diskspace.rrd:kbused:MAX DEF:avail=diskspace.rrd:kbavailable:MAX DEF:currentUsed=diskspace.rrd:kbused:LAST DEF:currentAvail=diskspace.rrd:kbavailable:LAST AREA:currentUsed#FFFF00:Used AREA:currentAvail#80C455:Available:STACK`
3. Create the wrong chart with CDEF
`rrdtool graph disspace.png --full-size-mode -w 1128 -h 180 --start 1650434400 --end start+72000 --title '172.27.141.3: Disk space on /dev/sda2 ( tmp )' --vertical-label 'Disk space in MB' --lower-limit 0 DEF:used=diskspace.rrd:kbused:MAX DEF:avail=diskspace.rrd:kbavailable:MAX DEF:currentUsed=diskspace.rrd:kbused:LAST DEF:currentAvail=diskspace.rrd:kbavailable:LAST CDEF:usedmegabytes=used,0,+ CDEF:availmegabytes=avail,0,+ AREA:usedmegabytes#FFFF00:Used AREA:availmegabytes#80C455:Available:STACK`
4. Compare the charts.
(5. For end times below start+69000 it works perfectly fine.)

**Expected behavior**
Even with CDEF:usedmegabytes=used,0,+ or in our case usedmegabytes=used,1024,/ it should look like the chart from 2.

**Screenshots**
Added.

**Desktop (please complete the following information):**
 - CentOS 7 + 8
 - tested with rrdtool version 1.4.8 and 1.7.0
![diskspace-correct](https://user-images.githubusercontent.com/584219/164176262-b1ba8b8b-2749-42fe-bf39-cf6203550d6f.png)
![diskspace-wrong](https://user-images.githubusercontent.com/584219/164176268-57f5541b-cc99-4203-816e-5126b79b9c8a.png)
[diskspace.rrd.tar.gz](https://github.com/oetiker/rrdtool-1.x/files/8519401/diskspace.rrd.tar.gz)

**Comment by oetiker** [comment]
Since you are using the MAX consolidation, chances are high that the total of used plus avail will be higher than the total disk space ... that it does not show in graph1 is nice, but not what I would expect ... please try your experiment with AVERAGE consolidation ...

**Comment by Yufiel** [comment]
Looks promising with AVERAGE instead of MAX.

**Comment by Yufiel** [comment]
Thx. 
Using AVERAGE confirmed as a solution.
