### ISSUE TITLE
Some man pages installed in wrong place

### ISSUE THREAD

**Issue by gdsotirov** [oetiker/rrdtool-1.x#1177]
**Describe the bug**
No matter `--mandir` option to `configure` the following man pages are installed in wrong place:

- `/usr/local/share/man/man3/RRDp.3`
- `/usr/local/share/man/man3/RRDs.3`

**To Reproduce**
1. Configure with `./configure --mandir=/usr/man`;
2. `make` and `make install`;

**Expected behavior**
All man pages are installed in the directory pointed by `--mandir` option.

**Comment by ferdnyc** [comment]
Confirmed, the Perl installation ignores any path arguments other than `--prefix=` when generating its Makefile.

This can be fixed by adding `INSTALLSITEMAN3DIR=$mandir/man3` to the `PERL_MAKE_OPTIONS` generated by `configure`.
