### ISSUE TITLE
Error: Invalid step

### ISSUE THREAD

**Issue by lazna** [oetiker/rrdtool-1.x#1182]
**Describe the bug**
It produce errormessage 'ERROR: Invalid step 0.5: value has trailing garbage'

**To Reproduce**
rrdtool create newdata.rrd --step 60 DS:data:GAUGE:120:U:U RRA:AVERAGE:0.5:0.5:86400 RRA:AVERAGE:0.5:30:17520

**Expected behavior**
Trying to monitor value every minute, my command is generated by this web page https://eccentric.one/misc/rrdcalc.html

What am I doing wrong?

rrdtool 1.8.0

**Comment by c72578** [comment]
Concerning `Invalid step 0.5`, please have a look at:
https://oss.oetiker.ch/rrdtool/doc/rrdcreate.en.html#STEP%2C_HEARTBEAT%2C_and_Rows_As_Durations

> `steps` defines how many of these primary data points are used to build a consolidated data point which then goes into the archive.

**Comment by lazna** [comment]
Yes, it is a bug of this RRD calculator. Already reporteto to its author. 

Thanks for reply
