### ISSUE TITLE
Introduce the code coverage status badge to README.md

### ISSUE THREAD

**Issue by youpong** [oetiker/rrdtool-1.x#1193]
**Is your feature request related to a problem? Please describe.**

Add status badges for coverage tests introduced in the PR #1192 to README.md.

A Markdown sample of the status badge is described at the following URL.
I do not have access to it, so please do so @oetiker .
https://app.codecov.io/github/oetiker/rrdtool-1.x/settings

For detailed procedures, please refer to the following URL.
https://docs.codecov.com/docs/status-badges

**Comment by oetiker** [comment]
thanks, fixed
