### ISSUE TITLE
Use blocking `F_SETLKW`

### ISSUE THREAD

**Issue by ensc** [oetiker/rrdtool-1.x#1204]
Atm, rrd uses non-blocking locking

https://github.com/oetiker/rrdtool-1.x/blob/b7d2007791b50d1c5c2d6af1ecd789182fcc102a/src/rrd_open.c#L804

This causes problems when data gathering and processing are done in separate processes.  E.g. when

- `rrdupdate foo.rrd ...`
- `rrdtool graph foo.rrd ...`

are executed at the same time, one of the two process might fail with "ERROR: could not lock RRD".

In case of `rrdupdate` this can lead to the loss of data; especially because there is no way to detect this kind of temporary error.

It would be better to use blocking wait (`F_SETLKW` instead of `F_SETLK` at the place above).  This will allow the later process to continue after the earlier one has finished.

**Comment by oetiker** [comment]
Hi @ensc 

I see your point ... could you provid a PR which adds a blocking lock but with a short timeout ... after all an update should not take a long time, and if there is a problem we don't want rrdtool processes piling up, causing a potentially even bigger problem.

**Comment by ensc** [comment]
It is not trivial to implement a timeout at the place where `F_SETLK*` is called; I see the following ways:

- setting an [alarm()](https://man7.org/linux/man-pages/man2/alarm.2.html)
  - this might interfere with other alarms and signal setup when the C API is used
- `pipe2()` + run `F_SETLKW` in a `fork()` + `select()` on the pipe-fd
  - compatibility issues (setting `O_CLOEXEC` in `pipe2()` is a GNU thing)
  - extra `SIGCHLD` signal (--> might interfere with users of the C API)
  - unexpected `fork()` (--> might exceeds ulimits which were set for security reasons)

I would rather:
- replace `F_SETLK` by `F_SETLKW`
- set an `alarm()` + do the signal setup in the CLI tools
- users of the C API would have to do similar things

Alternatively:
- change the API so that the three kinds of locking (none, blocking + non-blocking) can be selected by e.g. the `flags` parameter or command line arguments

What do you suggest?

**Comment by oetiker** [comment]
Making the behavior configurable sounds like a plan ... I want to avoid breaking backward compatibility.

**Comment by oetiker** [comment]
another idea ... instead of waiting, you could implement retry, obviously this does not have exactly the same effect but then a timeout is easy to implement.

**Comment by ensc** [comment]
I made it configurable by adding an `$RRD_LOCKING` environment variable and flags in the `updatex` api.  There exists also a `--locking` cli option but only for `rrdupdate`.  Defaults should not have been changed.

When somebody wants to implement a timeout, he can select the `none` strategy and do the locking on the rrd file manually before calling the C api or the tools.

**Comment by mnalis** [comment]
@oetiker Would it be possible to release rrdtool `1.8.1`? It has been more than 2 years since `1.8.0`, and I'd like to use this functionality in particular...

**Comment by oetiker** [comment]
rrdtool 1.9.0 is released
