### ISSUE TITLE
Page NOT found for Link to GitHub Action Release Windows

### ISSUE THREAD

**Issue by hdell** [oetiker/rrdtool-1.x#1250]
**Describe the bug**
I am really a noob with git. When I end up at https://github.com/oetiker/rrdtool-1.x/releases/tag/v1.8.0 looking for the merged current release for Visual Studio 2019 builds (MSVC). I click on the URL Link as part of the text: "The builds have been prepared using GitHub Action Release Windows" I then get the Git error "This page is not the page you were looking for.". I also went to Actions looking for a download and "Release Windows" was empty.

**To Reproduce**
Click on the URL Link as part of the text: "The builds have been prepared using GitHub Action Release Windows" I get the Git error "This page is not the page you were looking for.". The Link https://github.com/oetiker/rrdtool-1.x/actions/runs/1982986648.

**Expected behavior**
I had expected to get a ZIP of the binaries...

**Server (please complete the following information):
- Windows Server 2019

**Comment by oetiker** [comment]
the link is only available for a limited amount of thime ... the 1.8 release is already a bit old ... but the assets linked below should be fine ...
