### ISSUE TITLE
`error: use of undeclared identifier 'SOCK_CLOEXEC'` for macos builds

### ISSUE THREAD

**Issue by chenrui333** [oetiker/rrdtool-1.x#1261]
👋 SOCK_CLOEXEC does not exist for macos builds

```
  rrd_client.c:799:48: error: use of undeclared identifier 'SOCK_CLOEXEC'
      client->sd = socket(PF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, /* protocol = */ 0);
                                                 ^
  1 error generated.
```

relates to https://github.com/Homebrew/homebrew-core/pull/178899

**Comment by c72578** [comment]
@ensc Could you please have a look?
Link to PR: #1206

**Comment by ensc** [comment]
mmh... should be catched by https://github.com/oetiker/rrdtool-1.x/blob/019abc72c8018cfa14671feb395e599cbd78677d/src/compat-cloexec.h#L10-L12 which is covered by https://github.com/oetiker/rrdtool-1.x/blob/019abc72c8018cfa14671feb395e599cbd78677d/configure.ac#L513

Can you look in the ./configure output for the result of this check?

**Comment by ensc** [comment]
see https://github.com/oetiker/rrdtool-1.x/pull/1262

**Comment by chenrui333** [comment]
Thanks, the patch works for me in my local, just added the change and pushed to CI.

**Comment by chenrui333** [comment]
Thanks for the quick fix!

**Comment by ann0see** [comment]
Ok. Seems to compile with the latest version on master. Sorry for the noise.
