### ISSUE TITLE
Build failure on armhf: time_t can be 64bits

### ISSUE THREAD

**Issue by panlinux** [oetiker/rrdtool-1.x#1264]
**Describe the bug**
In Ubuntu and Debian, armhf packages are being built with a time_t of 64bits, to avoid the impending 2038 year problem[1]. This is done by adding `-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64` to the build flags.

When rrdtool 1.7.2 and current master are rebuilt with those flags, the build fails (logs from master):
```
rrd_fetch_libdbi.c:625:45: error: passing argument 2 of '_sql_fetchrow' from incompatible pointer type [-Wincompatible-pointer-types]
  625 |   while((r_status=_sql_fetchrow(&table_help,&r_timestamp,&r_value,derive))>0) {
      |                                             ^~~~~~~~~~~~
      |                                             |
      |                                             long int *
rrd_fetch_libdbi.c:220:62: note: expected 'time_t *' {aka 'long long int *'} but argument is of type 'long int *'
  220 | static int _sql_fetchrow(struct sql_table_helper* th,time_t *timestamp, rrd_value_t *value,int ordered) {
      |                                                      ~~~~~~~~^~~~~~~~~
make[2]: *** [Makefile:1010: librrd_la-rrd_fetch_libdbi.lo] Error 1
```

The fix for that is:
```diff
--- a/src/rrd_fetch_libdbi.c
+++ b/src/rrd_fetch_libdbi.c
@@ -410,7 +470,7 @@ rrd_fetch_fn_libdbi(
   int isunixtime=1;
   long gmt_offset=0;
   /* the result-set */
-  long r_timestamp,l_timestamp,d_timestamp;
+  time_t r_timestamp,l_timestamp,d_timestamp;
   double r_value,l_value,d_value;
   int r_status;
   int rows;
```
There are however many more warnings around the size of time_t, and as they are warnings, they are not yet failing the build, but they should be fixed too. I have a bigger patch for those, and will suggest this all in a PR.

One thing to worry about is if this fix will introduce binary incompatibilities in the database. I think not, but I'm not familiar with the code.

1. https://en.wikipedia.org/wiki/Year_2038_problem

**To Reproduce**
1. Set build flags to include `-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64`
2. Build rrdtool current master in the armhf architecture (I suppose another 32bits architecture would also show the problem).

**Expected behavior**
The build completes without errors or warnings around time_t.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 24.10 (Oracular, current devel release)
 - Version: rrdtool git master branch

**Comment by oetiker** [comment]
when you `-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64` the db format will be incompatible but ok :) the patch looks fine by my

**Comment by panlinux** [comment]
> when you `-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64` the db format will be incompatible but ok :) the patch looks fine by me.

Oh, that's true, and that boat has already sailed. Ubuntu 24.04 used those flags already, buy that compiler version didn't fail the build like gcc-14 is doing.
