### ISSUE TITLE
RRDtool 1.9.0 and 1.8.0 on Cacti 1.3 Dev problem

### ISSUE THREAD

**Issue by morganfw** [oetiker/rrdtool-1.x#1268]
Hi,
I'm using Cacti 1.3 Dev on Ubuntu 24.04 LTS with compiled RRDtool v1.9.0, 1.8.0 and 1.7.2
After create a new graph it will be displayed:

![image](https://github.com/user-attachments/assets/83446f0f-f0a1-4b78-b524-47a9ca5d87e2)

then enabling a Threshold in 'Console - Management - Graphs' by selecting Graph and Create Aggregate from Template, Graph going into error then in segmentation fault

![image](https://github.com/user-attachments/assets/a0520ab9-689c-4743-8795-8336cbeb170a)

![image](https://github.com/user-attachments/assets/2c216c0c-f3a7-4952-86eb-9664a4df05be)

If delete the Threshold, Graph works again.

I report below the detailed informations.

RRDtool version:

![image](https://github.com/user-attachments/assets/28a23929-9c13-4712-8b60-4b01b7275ead)

RRDtool path:

![image](https://github.com/user-attachments/assets/af05c959-d41d-4cc4-abcf-0630fa75be64)

RRDtool CLI version:

```
# /opt/rrdtool-1.9.0/bin/rrdtool
RRDtool 1.9.0  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Nov  4 2024 22:40:11

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
                last, lastupdate, first, info, list, fetch, tune,
                resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages
```

RRDtool graph syntax:

```
/opt/rrdtool-1.9.0/bin/rrdtool graph - \
--imgformat=SVG \
--start='-86400' \
--end='-70' \
--pango-markup  \
--title='Local Linux Machine - CPU Utilization - CPUTotal' \
--vertical-label='percent' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--tabwidth '40' \
--rigid \
--upper-limit='110' \
--lower-limit='0' \
COMMENT:"From 2024-11-11 20\:01\:11 To 2024-11-12 20\:00\:01\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 \
--font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
DEF:a='/var/www/html/cacti/rra/local_linux_machine_cpu_204.rrd':'cpu':AVERAGE \
DEF:b='/var/www/html/cacti/rra/local_linux_machine_cpu_204.rrd':'cpu':MAX \
AREA:a#FF00007F:'CPU Utilization'  \
GPRINT:a:LAST:'Current\:%8.0lf'  \
GPRINT:a:AVERAGE:'Average\:%8.0lf'  \
GPRINT:a:MAX:'Maximum\:%8.0lf\n'  \
LINE1:b#FF0000FF: \
COMMENT:' \n' \
COMMENT:'<u><b>Threshold Alert/Warning Values</b></u>\n' \
LINE1:95#800517:'Alert Hi for Local Linux Machine - CPU Utilization - CPUTotal (95)' \
LINE1:90#0000FF:'Warning Hi for Local Linux Machine - CPU Utilization - CPUTotal (90)' \
RRDtool Command lengths = 1320 characters.
								RRDtool Says:

SVG/XML Output OK	
```

Graph syntax executed from CLI in attachment.

[Cacti_RRDtool_Graph_Syntax_CLI.txt](https://github.com/user-attachments/files/17721642/Cacti_RRDtool_Graph_Syntax_CLI.txt)

if try to enable Real-time, the Graph works:

![image](https://github.com/user-attachments/assets/e629ec41-46e0-45c9-9435-400f27c53c11)

even converting the Graph Templates to PNG, same behaviour.

Downgrading RRDtool to 1.8+ with binary path `/opt/rrdtool-1.8.0/bin/rrdtool` or `/opt/rrdtool-1.9.0/bin/rrdtool` nothing changed.

By downgrade to 1.7.2+ or 1.7+ on General tab, with binary path `/opt/rrdtool-1.8.0/bin/rrdtool` or  `/opt/rrdtool-1.9.0/bin/rrdtool` the Graph still works again.

I opened an issue on Cacti Github too, that suggested me to open this issue here as well.

**Comment by morganfw** [comment]
Trying to execute graph CLI changing `graph` with `graphv` command and by adding `--add-jsontime` option, process crashes:

```
/opt/rrdtool-1.9.0/bin/rrdtool graphv - \
--add-jsontime \
--imgformat=PNG \
--start='1731477900' \
--end='1731564277' \
--pango-markup  \
--title='Local Linux Machine - CPU Utilization - CPUTotal' \
--vertical-label='percent' \
--slope-mode \
--base=1000 \
--height=200 \
--width=700 \
--tabwidth '40' \
--rigid \
--upper-limit='110' \
--lower-limit='0' \
COMMENT:"From 2024-11-13 07\:05\:00 To 2024-11-14 07\:04\:37\c" \
COMMENT:"  \n" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 \
--font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Generated by Cacti®' \
LINE1:90#0000FF:'Warning Hi for Local Linux Machine - CPU Utilization - CPUTotal (90)' \
>
Segmentation fault (core dumped)
```

**Comment by oetiker** [comment]
can you try to drop as many cli arguments as necessary to still cause the segfault ?

**Comment by oetiker** [comment]
another option would be to compile with -g and then do a backtrace on the coredump

here are some instructions
https://claude.site/artifacts/4246e5c1-4755-47a8-8c5b-43eb58232bb2

**Comment by TheWitness** [comment]
@oetiker,

I think it's the legend buffer.  For the -add-jsontime as the hrule text can be fairly long.  There is likely a buffering issue with the legend json output.

What's weird is that in his example, it shows that long legend on the LINE1 object.  So, I'm a little confused.  I could have sworn they were hrules, but then again, age has this habit of clearing ones registers.

Larry

**Comment by morganfw** [comment]
> another option would be to compile with -g and then do a backtrace on the coredump
> 
> here are some instructions https://claude.site/artifacts/4246e5c1-4755-47a8-8c5b-43eb58232bb2

I will try to do backtrace.

**Comment by morganfw** [comment]
@oetiker backtrace attached

[rrdtool-1.9.0-debug_coredump_backtrace.txt](https://github.com/user-attachments/files/17778380/rrdtool-1.9.0-debug_coredump_backtrace.txt)
