### ISSUE TITLE
RRDTool Process stuck on windows server 2003

### ISSUE THREAD

**Issue by winterpinn** [oetiker/rrdtool-1.x#361]
I use rrd(build version 1.4.7) as part of my project. The rrd executable is periodically called by my process to update the value. 
And sometime RRDTool process stuck after calling update operation.

There's 2 thread in the stuck process, here's the thread stack 

Thread1:
ntkrnlpa.exe+0x8db9e
ntkrnlpa.exe+0x2823c
ntdll.dll!KiFastSystemCallRet
ntdll.dll!RtlLockHeap+0x252
ntdll.dll!LdrLockLoaderLock+0x6b
!GetModuleFileNameW+0x51
!IsSetup+0x39
!LuaShouldApplyShim+0x5
!NS_LUARedirectFS::InitializeHooksMulti+0x54
!ShimLib::InitializeHooksEx+0x70
!ShimLib::NotifyShims+0x37
!NotifyShims+0xd2
!SE_ProcessDying+0x9
ntdll.dll!RtlIpv4StringToAddressExW+0x6ee6
!GetVolumeInformationW+0x28e
!ExitProcess+0x14
!amsg_exit+0x75
!get_pgmptr+0x196
!exit+0x11
mfeavfk.sys+0x1b74
mfeavfk.sys!strftime_+0x369f
!ProcessIdToSessionId+0x209

Thead2:
ntkrnlpa.exe+0x8db9e
ntkrnlpa.exe+0x29ac8
ntkrnlpa.exe+0x138e0e
ntkrnlpa.exe+0x8983c
ntdll.dll!KiFastSystemCallRet
ntdll.dll!RtlLockHeap+0x252
ntdll.dll!RtlAllocateActivationContextStack+0x172
ntdll.dll!CsrClientCallServer+0xcc
ntdll.dll!KiUserApcDispatcher+0x25

**Comment by c72578** [comment]
If this is still relevant, please feel free to try current RRDtool 1.7.2
