### ISSUE TITLE
rrdtool-1.4 branch (rrdtool-1.4.8)

### ISSUE THREAD

**Issue by ChristianKrausse** [oetiker/rrdtool-1.x#400]
The include is not found +#include "../rrd_config.h"

Added here
 https://github.com/oetiker/rrdtool-1.x/commit/f860a1c88ad1eb2d46b69c9b5fe9f357d2f9d28e#src/rrd_create.c

Output on Visual C++ 2010 Express (1.4.7 is building only with Warnings)
Ausgabe:
1>------ Neues Erstellen gestartet: Projekt: rrdlib, Konfiguration: Debug Win32 ------
1>  strftime.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src\strftime.h(18): warning C4273: 'strftime_': Inkonsistente DLL-Bindung.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\time.h(172): Siehe vorherige Definition von 'strftime_'
1>  rrd_xport.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_version.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_utils.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_update.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_update.c(290): warning C4244: '+=': Konvertierung von 'long double' in 'long', möglicher Datenverlust
1>..\src\rrd_update.c(988): warning C4244: '=': Konvertierung von 'double' in 'time_t', möglicher Datenverlust
1>..\src\rrd_update.c(1240): warning C4244: '+=': Konvertierung von 'double' in 'unsigned long', möglicher Datenverlust
1>..\src\rrd_update.c(1388): warning C4244: '=': Konvertierung von 'double' in 'unsigned long', möglicher Datenverlust
1>  rrd_tune.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_tune.c(396): warning C4244: '=': Konvertierung von 'unsigned long' in 'short', möglicher Datenverlust
1>..\src\rrd_tune.c(431): warning C4244: '=': Konvertierung von 'unsigned long' in 'short', möglicher Datenverlust
1>..\src\rrd_tune.c(462): warning C4244: '=': Konvertierung von 'unsigned long' in 'short', möglicher Datenverlust
1>..\src\rrd_tune.c(495): warning C4244: '=': Konvertierung von 'unsigned long' in 'short', möglicher Datenverlust
1>  rrd_thread_safe_nt.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_rpncalc.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_rpncalc.c(805): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_rpncalc.c(807): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_rpncalc.c(833): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_rpncalc.c(835): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_restore.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_restore.c(235): fatal error C1189: #error :  "Don't know how to deal with TIME_T other than 4 or 8 bytes"
1>  rrd_resize.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_parsetime.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_open.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_nan_inf.c
1>  rrd_lastupdate.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_last.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_info.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_hw_update.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_hw_update.c(461): warning C4244: '=': Konvertierung von 'unsigned long' in 'unsigned short', möglicher Datenverlust
1>..\src\rrd_hw_update.c(474): warning C4244: 'return': Konvertierung von 'rrd_value_t' in 'int', möglicher Datenverlust
1>  rrd_hw_math.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_hw.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_hw.c(114): warning C4244: '=': Konvertierung von 'unsigned long' in 'unsigned short', möglicher Datenverlust
1>..\src\rrd_hw.c(147): warning C4244: '=': Konvertierung von 'double' in 'unsigned long', möglicher Datenverlust
1>..\src\rrd_hw.c(149): warning C4244: '=': Konvertierung von 'double' in 'unsigned long', möglicher Datenverlust
1>  rrd_graph_helper.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph_helper.c(545): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph_helper.c(550): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph_helper.c(552): warning C4244: '=': Konvertierung von 'float' in 'int', möglicher Datenverlust
1>..\src\rrd_graph_helper.c(1138): warning C4244: '=': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>  Code wird generiert...
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src\rrd_utils.c(155): warning C4700: Die nicht initialisierte lokale Variable "base_dir" wurde verwendet.
1>  Kompilieren...
1>  rrd_graph.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src\strftime.h(18): warning C4273: 'strftime_': Inkonsistente DLL-Bindung.
1>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\time.h(172): Siehe vorherige Definition von 'strftime_'
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(409): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(468): warning C4244: '=': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(661): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1010): warning C4244: '=': Konvertierung von 'double' in 'time_t', möglicher Datenverlust
1>..\src\rrd_graph.c(1243): warning C4244: '=': Konvertierung von 'double' in 'unsigned long', möglicher Datenverlust
1>..\src\rrd_graph.c(1359): warning C4244: 'Argument': Konvertierung von 'rrd_value_t' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(1359): warning C4244: 'Argument': Konvertierung von 'rrd_value_t' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(1366): warning C4244: 'Argument': Konvertierung von 'rrd_value_t' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(1708): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1709): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1819): warning C4244: '+=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1891): warning C4244: '+=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1893): warning C4244: '-=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1895): warning C4244: '-=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1911): warning C4244: '=': Konvertierung von 'double' in 'long', möglicher Datenverlust
1>..\src\rrd_graph.c(1914): warning C4244: '=': Konvertierung von 'double' in 'long', möglicher Datenverlust
1>..\src\rrd_graph.c(1954): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(1983): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2002): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2169): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2250): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2260): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(2260): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(2283): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2342): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2346): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2347): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2409): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2413): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2414): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2948): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2953): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2958): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2970): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2980): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(2987): warning C4244: '=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(3068): warning C4244: '-=': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(3124): warning C4244: '+=': Konvertierung von 'double' in 'long', möglicher Datenverlust
1>..\src\rrd_graph.c(3128): warning C4244: '+=': Konvertierung von 'double' in 'long', möglicher Datenverlust
1>..\src\rrd_graph.c(3364): warning C4244: 'Argument': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(3364): warning C4244: 'Argument': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_graph.c(3546): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3546): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3592): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3592): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3597): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3597): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3612): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3612): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3618): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3618): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3631): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3631): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3637): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3637): warning C4244: 'Argument': Konvertierung von 'double' in 'float', möglicher Datenverlust
1>..\src\rrd_graph.c(3832): warning C4244: '=': Konvertierung von 'double' in 'time_t', möglicher Datenverlust
1>..\src\rrd_graph.c(4062): warning C4244: 'Argument': Konvertierung von 'double' in 'gint', möglicher Datenverlust
1>  rrd_gfx.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_gfx.c(139): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'long', möglicher Datenverlust
1>..\src\rrd_gfx.c(140): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>..\src\rrd_gfx.c(152): warning C4244: 'Argument': Konvertierung von 'double' in 'gint', möglicher Datenverlust
1>  rrd_getopt1.c
1>  rrd_getopt.c
1>  rrd_format.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_first.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_fetch.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_error.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_dump.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_diff.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  rrd_create.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../rrd_config.h(13): warning C4005: 'PACKAGE_VERSION': Makro-Neudefinition
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(36): Siehe vorherige Definition von 'PACKAGE_VERSION'
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../rrd_config.h(14): warning C4005: 'NUMVERS': Makro-Neudefinition
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(34): Siehe vorherige Definition von 'NUMVERS'
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../rrd_config.h(52): warning C4005: 'HAVE_RRD_GRAPH': Makro-Neudefinition
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(29): Siehe vorherige Definition von 'HAVE_RRD_GRAPH'
1>c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h(18): error C2371: 'int16_t': Neudefinition; unterschiedliche Basistypen
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src\rrd_client.h(44): Siehe Deklaration von 'int16_t'
1>c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h(19): error C2371: 'int32_t': Neudefinition; unterschiedliche Basistypen
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src\rrd_client.h(46): Siehe Deklaration von 'int32_t'
1>c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h(22): error C2371: 'uint16_t': Neudefinition; unterschiedliche Basistypen
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src\rrd_client.h(45): Siehe Deklaration von 'uint16_t'
1>c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h(23): error C2371: 'uint32_t': Neudefinition; unterschiedliche Basistypen
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src\rrd_client.h(47): Siehe Deklaration von 'uint32_t'
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../rrd_config.h(89): error C2084: Funktion 'int round(double)' hat bereits einen Funktionsrumpf
1>          c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): Siehe vorherige Definition von 'round'
1>  pngsize.c
1>c:\rrdbuild\rrdtool-1.4.8\rrdtool-1.4.8\src../win32/config.h(60): warning C4244: 'Initialisierung': Konvertierung von 'double' in 'int', möglicher Datenverlust
1>  plbasename.c
1>  hash_32.c
1>  Code wird generiert...
========== Alles neu erstellen: 0 erfolgreich, Fehler bei 1, 0 übersprungen ==========

**Comment by c72578** [comment]
Thanks for your report.
This has been fixed in the meantime.
Feel free to try RRDtool 1.7.2 or current master.
