### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [oetiker/rrdtool-1.x#429]
I would like to point out that identifiers like "[`_RRDLIB_H`](https://github.com/oetiker/rrdtool-1.x/blob/e6b9363c11cf587b1e9fc0e6068e217eb1279f4f/src/rrd.h#L52)" and "[`__RRD_CLIENT_H`](https://github.com/oetiker/rrdtool-1.x/blob/c5794b2d8561e19762a5acd56506934e00b66978/src/rrd_client.h#L27)"  [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by c72578** [comment]
The include guards are now compliant with the C naming specification.
Leading underscores have been removed and furthermore, unique identifiers have been added to the include guards.

These UUID like identifiers (uppercase, without hyphens) can be generated e.g. with the following command:
`uuidgen | tr '[:lower:]' '[:upper:]' | sed 's/-//g'`
