### ISSUE TITLE
Win32 Compliation Failed

### ISSUE THREAD

**Issue by raspserver** [oetiker/rrdtool-1.x#444]
I follow the steps from "WIN32-BUILD-TIPS.txt" & created a folder contrib with all unzipped files merged into common folders like bin, include, lib etc.

MS Visual C++ 2008 version is 9.0.21022.8.  I start build rrdlib solution but output below error:-
1>------ Build started: Project: rrdlib, Configuration: Release Win32 ------
1>Compiling...
1>rrd_restore.c
1>e:\install\rrd_tool\rrdtool-1.4.8\src../win32/config.h(60) : warning C4244: 'initializing' : conversion from 'double' to 'int', possible loss of data
1>..\src\rrd_restore.c(235) : fatal error C1189: #error :  "Don't know how to deal with TIME_T other than 4 or 8 bytes"
1>rrd_create.c
1>e:\install\rrd_tool\rrdtool-1.4.8\src../win32/config.h(60) : warning C4244: 'initializing' : conversion from 'double' to 'int', possible loss of data
1>..\src\rrd_create.c(15) : fatal error C1083: Cannot open include file: '../rrd_config.h': No such file or directory
1>Build log was saved at "file://e:\install\RRD_Tool\rrdtool-1.4.8\win32\Release\BuildLog.htm"
1>rrdlib - 2 error(s), 2 warning(s)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Please help what other steps I have missed.

Thanks you.

**Comment by c72578** [comment]
Windows build instructions have been updated and support for building under Windows has been enhanced in the meantime. Feel free to try current RRDtool v1.7.2
