### ISSUE TITLE
Less rigid '--rigid' option

### ISSUE THREAD

**Issue by oetiker** [oetiker/rrdtool-1.x#48]
I'd like to see an option that would allow autoscaling when the  
displayed values were all below upper-limit (or above lower-limit),  
but would function like rigid when the limit was reached.  For  
example, suppose that upper-limit was 100, and we had three datapoints  
at 5, 9, 12.  The Y axis would go from 0 to 15.  If we added three more  
points at 20, 27, 35, the Y axis would go to 40.  Add three more  
points at 50, 90, 120, and the Y axis would go up to 100, and the  
final datapoint would be "off the chart".                                                            

I'd like this feature because I have several data feeds that have  
occasional large spikes.  If I don't put in a --rigid limit, a single  
datapoint that's 10x the rest of the data will get me a graph with a  
bumpy line across the bottom and one big spike.  If I put in a --rigid  
limit, I can get a decent compromise for the whole dataset, but then  
if I look at a period that has no spike, the Y axis goes to a value  
that's far too high for the displayed data.

**Comment by mdujava** [comment]
Hello,

Do you have idea what name should option have? Do "--not-expand" beyond limits (but shrink if needed)?

What if data has datapoints at 5, 9, 12 and 120 and upper-limit is 100, should it keep upper limit on 100 or ajust it to 15? If we say it will ignore all datapoints above it can ajust and set upper limit to 15, in either way datapoint at 120 will not be visible, but detail in lower datapoints will be clearer visible in second option.

**Comment by oetiker** [comment]
that is an imported ticket ... so I don't know what the original poster wold say ... :) `--allow-shrink` comes to mind (I like positive options).

**Comment by mdujava** [comment]
Hello,

This issue should be closed. As #843 was merged.

Thank you.
