### ISSUE TITLE
rrdtool fetch gives only nan values

### ISSUE THREAD

**Issue by fansari** [oetiker/rrdtool-1.x#503]
My Cacti installation gives only nan values. The .rrd files look good when I use "rrdtool info". But with "rrdtool fetch <filename> AVERAGE" I see only nan values. I already read that the MIN and MAX values are important. But this does not seem to be the reason for the issue.

What else can be the reason for only getting nan values?

I use rrdtool 1.4.8.

rrdtool info localhost_proc_37.rrd  | grep ds

ds[proc].index = 0
ds[proc].type = "GAUGE"
ds[proc].minimal_heartbeat = 600
ds[proc].min = 0.0000000000e+00
ds[proc].max = 1.0000000000e+03
ds[proc].last_ds = "94"
ds[proc].value = 1.8800000000e+02
ds[proc].unknown_sec = 0

rrdtool fetch localhost_proc_37.rrd AVERAGE

1402757400: -nan
1402757700: -nan
1402758000: -nan
1402758300: -nan
1402758600: -nan

But it is strange. It works after restarting the snmpd. What does this mean?

402772100: 8.5000000000e+01
402772400: 8.5000000000e+01
1402772700: 8.5000000000e+01
1402773000: 8.5000000000e+01
1402773300: 8.5000000000e+01

**Comment by hachpai** [comment]
Same issue.
hachpai@faismoilamour testrrd % rrdtool fetch test3.rrd AVERAGE                                                                                                                                                                           [0]
                     traffic_in         traffic_out

1449502800: nan nan
1449503100: nan nan
1449503400: nan nan
1449503700: nan nan
1449504000: nan nan
1449504300: nan nan
1449504600: nan nan
1449504900: nan nan
