### ISSUE TITLE
Python Bindings fail loading when RRDTool is built without rrdgraph

### ISSUE THREAD

**Issue by pavankrish123** [oetiker/rrdtool-1.x#505]
I have compiled rrdtool source without rrdgraph and rrdcgi using  --disable-rrdcgi,  --disable-rrd_graph
in the configuration file. Using the same configuration file I have generated python-rrdtool rpm for the bindings 

Now loading python-rrdtool bindings complains about missing rrd_graph symbols.

> > > import rrdtool
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: /usr/lib/python2.7/site-packages/rrdtoolmodule.so: undefined symbol: rrd_graph

It looks like we are building rrdmodule.so for all components without conditional flags that we use while building the actual rrdtool source.

**Comment by Keleir** [comment]
I Occurs the same error: :confused: 
```
ImportError: /usr/local/python2.7.3/lib/python2.7/site-packages/rrdtool.so: undefined symbol: rrd_flushcached
```
