### ISSUE TITLE
rrdtool 1.4.7 --left-axis-format option missing

### ISSUE THREAD

**Issue by kaamil1984** [oetiker/rrdtool-1.x#522]
I have no --left-axis-format option in rrdtool graph.

pi@raspberrypi ~/rrd $ cat graph.sh

#!/bin/bash

rrdtool graph /home/pi/rrd/test.png \
    --end now --start now-6000s --width 900 --height 600 \
    --right-axis 1:0 \
    --left-axis-format %2.1lf \
    DEF:ds0a=/home/pi/rrd/temperature.rrd:temperature:AVERAGE \
    AREA:ds0a#0000FF:"Temperature ('C)\l" \

pi@raspberrypi ~/rrd $ ./graph.sh
ERROR: unknown option '--left-axis-format'

Im using rrdtool 1.4.7 Compiled Sep  4 2012 23:43:06.

--right-axis-format is working

--left-axis-format option is missing also in my man.

Is this normal?

**Comment by Narkhelek** [comment]
According to the change log --left-axis-format was not added until 1.4.9.  However, I have the exact same issue with 1.4.9 that I compiled from source.

**Comment by oetiker** [comment]
@Narkhelek hmmm at least in my copy it works fine and the github source also says it should ... https://github.com/oetiker/rrdtool-1.x/blob/v1.4.9/src/rrd_graph.c
