### ISSUE TITLE
Pango-CRITICAL **: pango_cairo_font_map_create_context: assertion 'PANGO_IS_CAIRO_FONT_MAP (fontmap)' failed

### ISSUE THREAD

**Issue by ghost** [oetiker/rrdtool-1.x#527]
Frequently rrdtool graph fails with "Pango-CRITICAL *_: pango_cairo_font_map_create_context: assertion 'PANGO_IS_CAIRO_FONT_MAP (fontmap)' failed" then it starts spewing in a loop the following (never ending loop):
GLib-GObject-CRITICAL *_: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
GLib-GObject-CRITICAL **: g_object_replace_qdata: assertion 'G_IS_OBJECT (object)' failed

**Comment by bitsonforfun** [comment]
fork a child process works!

**Comment by john-dgi-vof-com** [comment]
@ace-han, where do I import 'available_attrs' ? 

I already found that wraps is imported from functools

`
from functools import wraps
`

**Comment by ace-han** [comment]
@john-dgi-vof-com I think you can just copy the implementation from Django as your own lib to serve this `available_attrs`

```python
# your_lib/utils.py
# other utils functions
# ...
def available_attrs(fn):
    """
    Return the list of functools-wrappable attributes on a callable.
    This is required as a workaround for http://bugs.python.org/issue3445
    under Python 2.
    """
    if six.PY3:
        return WRAPPER_ASSIGNMENTS
    else:
        return tuple(a for a in WRAPPER_ASSIGNMENTS if hasattr(fn, a))
```
