### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by urbalazs** [oetiker/rrdtool-1.x#571]
I'd like to translate rrdtool into Hungarian. Can you generate me a .pot file and put "hu" entry in the po/LINGUAS file?

**Comment by oetiker** [comment]
just compile rrdtool and you will find the rrdtool.pot file in the po subdirectory.

**Comment by urbalazs** [comment]
I found the rrdtool.pot, see https://github.com/oetiker/rrdtool-1.x/pull/777 for Hungarian translation.
