### ISSUE TITLE
Common crash at apply_smoother (rrd_hw.c:224) in 683c8db765

### ISSUE THREAD

**Issue by jccleaver** [oetiker/rrdtool-1.x#583]
I don't have a minimal reproducer on this, but we've seen it approx once a day on our high volume system running 683c8db765. An example GDB stack trace is http://pastebin.com/15bpjFWi , but they all show the crash at line 224 of src/rrd_hw.c:

working_average[j] += rrd_values_cpy[k * row_length + j];

After coming back up, reading and writing to the file over time seems fine. (Values on disk don't appear to be invalid.)

We'd very occasionally seen this before while tracking master, but it seems to be occurring more regularly since 4b1eecc9cd. More stack traces can be provided if needed; this is on EL6/x86_64.

**Comment by oetiker** [comment]
could you try running with valgrind ?

**Comment by oetiker** [comment]
if you could run this under valgrind, chances are we would  see directly where this is going wrong

**Comment by jccleaver** [comment]
Sorry for the delay. I'll be trying this today. (Valgrind gives us a huge performance hit, alas…). I can confirm that we still see it with 83251c9e51.

**Comment by jccleaver** [comment]
Crash info here: http://pastebin.com/1BZBR1Z1

**Comment by oetiker** [comment]
please try 8051bbe

**Comment by jccleaver** [comment]
Thanks. 3 hours now and no crashes so far…

**Comment by oetiker** [comment]
with valgrind?

**Comment by jccleaver** [comment]
Correct, still running under valgrind on the system I've been watching. 

I'll push it out shortly onto other boxes running on the same streams of data for comparison; although I can't run valgrind there, we'll at least be able to see if we still have issues.

**Comment by oetiker** [comment]
so that fix, I integrated for the smoother a few months back was causing this ... not only a crash, but actually wrong data in case it did not crash

**Comment by jccleaver** [comment]
Yikes. That might explain it then.

We haven't crashed yet, but on a graceful exit valgrind did highlight this possibly similar issue on our test system:

==3735== 4496 errors in context 1 of 1:
==3735== Source and destination overlap in memcpy(0x403e790, 0x403e790, 1040)
==3735==    at 0x4C29BCE: memcpy (mc_replace_strmem.c:882)
==3735==    by 0x5AFA78C: rrd_write (string3.h:52)
==3735==    by 0x5AF7D18: apply_smoother (rrd_hw.c:290)
==3735==    by 0x5B06111: _rrd_updatex (rrd_update.c:2402)
==3735==    by 0x5B0672F: rrd_update (rrd_update.c:745)
==3735==    by 0x405E1B: flush_cached_updates (do_rrd.c:252)
==3735==    by 0x407506: create_and_update_rrd (do_rrd.c:519)
==3735==    by 0x413C49: do_ncv_rrd (do_ncv.c:182)
==3735==    by 0x414B01: update_rrd (do_rrd.c:753)
==3735==    by 0x403E7B: main (xymond_rrd.c:453)

**Comment by oetiker** [comment]
oh :) nice one ... I think we don't even have to write the cdp back to disk in MMAP mode ... do you agree ? f0dbf02

**Comment by jccleaver** [comment]
Nice! Hmm. Yeah, does seem like it... I'll put that build into play.

No crash on 8051bbe overnight; it seems like that did it for the first issue.

**Comment by jccleaver** [comment]
Was about to update that we were still seeing the second issue, but as you see in the commit update I think that should be #ifndef HAVE_MMAP instead :)

**Comment by oetiker** [comment]
oops :) 55e03f4

**Comment by jccleaver** [comment]
So far we haven't seen any problems. Looks good!
