### ISSUE TITLE
Graph antialiasing not working in rrdtool > 1.2

### ISSUE THREAD

**Issue by XNRL** [oetiker/rrdtool-1.x#588]
Greetings,

I've been moving old Cacti to a new server and noticed that graphs are not anitaliased now. Checking/uncheking '--slope-mode' option seemingly does nothing. 

Between the servers the only noteworthy difference is rrdtool version.

Tested with several versions of rrdtool on a local machine:
* 1.4.8 (from Debian Wheezy unstable repo)
* 1.2.28 (compiled from source)
* 1.5.0-rc2 (compiled from source)
Unfortunately I couldn't make comparison with version 1.3 as it gave the 'rrd was created on different architecture' error.

The only version in which antialiasing works properly is 1.2.28. Screenshots of the graphs in questions are as follows:
1.2 — 
![test-1 2](https://cloud.githubusercontent.com/assets/5425662/6482233/fbe3d7f8-c274-11e4-96bc-50e3148eb670.png)

1.4 — 
![test-1 4](https://cloud.githubusercontent.com/assets/5425662/6482237/0251a976-c275-11e4-8c10-631b253afecc.png)

1.5 — 
![test-1 5](https://cloud.githubusercontent.com/assets/5425662/6482241/062bf3ee-c275-11e4-8569-ceded6eafd5e.png)

Graphs were created with the following command:

> rrdtool graph - \
 --imgformat=PNG \
 --start='1425300565' \
--end='1425386965' \
--title='bsr1' \
--base='1000' \
--height='120' \
--width='500' \
--alt-autoscale-max \
--lower-limit='0' \
--vertical-label='Leases' \
--slope-mode \
--font TITLE:8: \
--font AXIS:7: \
--font LEGEND:7: \
--font UNIT:7: \
DEF:a='<path>/test.rrd':'mx_dhcpd_leases':AVERAGE \
AREA:a#35962BFF:'leases'  \
GPRINT:a:LAST:'Current\:%8.0lf'  \
GPRINT:a:AVERAGE:'Average\:%8.0lf'  \
GPRINT:a:MAX:'Maximum\:%8.0lf\n' > test-1.3.png

The hosts involved in testing:
* FreeBSD 6.3 : the old Cacti server with rrdtool 1.2.30 (manually compiled)
* Debian Wheezy : new Cacti server with rrdtool 1.4.7-2 (from stable repo)
* Debian Wheezy : clone of the previous host for testing purposes

There also was a separate test on another user host with versions 1.2.30 and 1.4.7, results reportedly confirm to the pattern: in v1.2 AA works, in 1.4 doesn't. Graph creation command and images could be procured if needed.

Just in case here is a list of dependencies I could determine versions for on the local machine (via ldd for rrdtool from repo):

> librrd — 1.4.8-1.2
libc — 2.18-7
libxml2 — 2.9.2+dfsg1-3
libdbi — 0.9.0-4
libpng12 — 1.2.50-2
libpangocairo-1 — 1.36.7-1
libpango-1 — 1.36.7-1
libcairo — 1.12.16-2
liblzma — 5.1.1alpha+20120614-2
libpangoft2-1 — 1.36.7-1
libfontconfig — 2.11.0-6.1
libfreetype — 2.5.2-2
libthai — 0.1.21-1
libffi — 3.0.10-3 3.1-2
libpcre — 1:8.35-3
libpixman-1 — 0.32.6-3
libxcb-shm — 1.10-3
libxcb-render — 1.10-3
libxcb — 1.10-3
libexpat — 2.1.0-6
libdatrie — 0.2.8-1
libxcb-dri2 — 1.10-3
libxcb-xfixes — 1.10-3
libxcb-shape — 1.10-3
libwayland-client — 1.6.0-1
libwayland-server — 1.6.0-1
libgbm — 10.2.6-1
libdrm — 2.4.56-1
libxcb-glx — 1.10-3
libxcb-dri3 — 1.10-3
libxcb-present — 1.10-2
libxcb-sync — 1.10-3
libxshmfence — 1.1-3
libgraphite2 — 1.2.4-3

**Comment by oetiker** [comment]
There is still antialiasing, but since I switched to the cairo drawing library, the rendering is slightly different, it looks less smooth on one hand, but busy charts look crisper that way. Look at this blow up of a section of your example graphs ... the differences are even more pronounced with LINE charts.

![untitled](https://cloud.githubusercontent.com/assets/429279/6485163/f9589f52-c281-11e4-831d-bad943efa081.png)

**Comment by XNRL** [comment]
Thank you, the --no-gridfit option did the trick.
