### ISSUE TITLE
rra average value not expected

### ISSUE THREAD

**Issue by UlricQin** [oetiker/rrdtool-1.x#589]
hi,
we use rrdtool as our backend tsdb and use https://github.com/ziutek/rrd to read/write rrd
#### metric: cpu.idle time: last 12hour cf: AVERAGE `expected`

![cpu.idle_12hour_average.png . . .](http://dinp.qiniudn.com/cpu.idle_12hour_average.png)
#### metric: cpu.idle time: last 24hour cf: MAX `expected`

![cpu.idle_24h_max](http://dinp.qiniudn.com/cpu.idle_24hour_max.png)
#### metric: cpu.idle time: last 24hour cf: AVERAGE `not expected`

![cpu.idle_24h_average](http://dinp.qiniudn.com/cpu.idle_24hour_average.jpg)

our rra settings:

```
// step:60s, heartbeat:  12h
c.RRA("AVERAGE", 0.5, 1, 720)

// 5m 2d
c.RRA("AVERAGE", 0.5, 5, 576)
c.RRA("MAX", 0.5, 5, 576)
c.RRA("MIN", 0.5, 5, 576)

// 20m 7d
c.RRA("AVERAGE", 0.5, 20, 504)
c.RRA("MAX", 0.5, 20, 504)
c.RRA("MIN", 0.5, 20, 504)

// 3h 3month
c.RRA("AVERAGE", 0.5, 180, 766)
c.RRA("MAX", 0.5, 180, 766)
c.RRA("MIN", 0.5, 180, 766)

// 1day 5year
c.RRA("AVERAGE", 0.5, 720, 730)
c.RRA("MAX", 0.5, 720, 730)
c.RRA("MIN", 0.5, 720, 730)
```

as you see, there are some point > 100 in the third graph. I'm confused...

**Comment by oetiker** [comment]
In order to debug this, you have to look at the original data you fed to rrdtool.

**Comment by UlricQin** [comment]
The original data are all less than 100. The first graph and second graph are all less than 100. These three graph use the same original data

**Comment by oetiker** [comment]
So please create a little shell script, which creates the rrd file, fills it with data and then produces the offending charts. Then I can look at what is going on. Also, which version of rrdtool are you using?

**Comment by UlricQin** [comment]
We use version origin/1.4
It is not stable repetition...

The three charts use the same original data and build from one rrd file.
The second chart's cf is MAX and the thrid chart's cf is AVERAGE. All MAX points are less than 100. Why some AVERAGE points greater than 100?

I'll create a little script to test.

**Comment by oetiker** [comment]
when doing a sample script, make sure to work with fixed timestamps ... if a problem is not reproducible, the reason is often that it only occurs with specific values.
