### ISSUE TITLE
--left-axis-format option missing from 1.4.9 - 1.5.0-rc2

### ISSUE THREAD

**Issue by Narkhelek** [oetiker/rrdtool-1.x#591]
I've compiled 1.4.9 and 1.5.0-rc2 from source and both version are missing the --left-axis-format option which was suppose to have been added in 1.4.9.  Output below shows version running and it complaining about unknown option:

mgleed@raspberrypi ~ $ rrdtool
RRDtool 1.5.0-rc2  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Mar  7 2015 10:34:11

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
		last, lastupdate, first, info, fetch, tune
		resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages

mgleed@raspberrypi ~ $ rrdtool graph test.png --only graph --left-axis-format %2.1lf
ERROR: unknown option '--left-axis-format'

**Comment by oetiker** [comment]
Sorry @Narkhelek I can't reproduce this ... also your command lines above seem to be 'hand made' since `--only graph` is missing a hyphen.

**Comment by Narkhelek** [comment]
Thanks for taking a look at this so quickly.  The example above was hand made as it seemed like the simplest way to show the error message.  Here is some additional info:

If I feed this:

#!/usr/local/bin/rrdcgi
 <HTML>
 <HEAD><TITLE>Upstairs Temperature/Humidity</TITLE></HEAD>
 <meta http-equiv="refresh" content="300">
 <BODY>
 <H1>Upstairs Temperature</H1>
 <RRD::GRAPH
  /var/www/hvac/pngs/daily_avg_temp.png
  --imginfo '<IMG SRC=/pngs/%s WIDTH=%lu HEIGHT=%lu >'
  --title 'Daily Temperature'
  --lazy --start -1d --end now --alt-autoscale --width 600 --height 200
  --alt-y-grid --left-axis-format %2.1lf
  DEF:temp=/var/rrd/upstairs_hvac.rrd:temp:AVERAGE:step=300:start=-1d:end=now
  AREA:temp#00ff00:"CUR Temp\:"
  VDEF:templast=temp,LAST
  GPRINT:templast:"%2.1lfF\\n"
  DEF:tempavg=/var/rrd/upstairs_hvac.rrd:temp:AVERAGE:step=3600:start=-1d:end=now
  LINE:tempavg#ff00ff:"AVG Temp\:"
  VDEF:tempavgval=tempavg,AVERAGE
  GPRINT:tempavgval:"%2.1lfF\\n"
  VDEF:tempmax=temp,MAXIMUM
  LINE:tempmax#ff0000:"MAX Temp\:"
  GPRINT:tempmax:"%2.1lfF\\n"
  VDEF:tempmin=temp,MINIMUM
  LINE:tempmin#0000ff:"MIN Temp\:"
  GPRINT:tempmin:"%2.1lfF\\n"
 >
[rest trunicated]

through rrdcgi I get this error:

[ERROR: unknown option '--left-axis-format']

I don't know how to get rrdcgi to spit out it's version but here I can show that /usr/local/bin/rrdtool is 1.5.0-rc2 as it should be since I compiled it from source and installed it there.

mgleed@raspberrypi ~ $ /usr/local/bin/rrdtool
RRDtool 1.5.0-rc2  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Mar  7 2015 10:34:11

Proof that I don't have another stale version laying around:

mgleed@raspberrypi ~ $ sudo find / -name rrdtool -type f
/usr/local/bin/rrdtool
/usr/share/bash-completion/completions/rrdtool
mgleed@raspberrypi ~ $

mgleed@raspberrypi ~ $ sudo find / -name rrdcgi -type f
/usr/local/bin/rrdcgi
mgleed@raspberrypi ~ $

If I execute 'rrdtool graph' it does state that -left-axis-format is an option.  Additionally I also cannot get it to recognize skipscale as a valid option either.  I'm stumped why a version that obviously is suppose to support these features is complaining when I specify them.

**Comment by oetiker** [comment]
you could try `ldd` on the rrdtool binary

also strings on the librrd that is linked to the rrdtool binary

**Comment by Narkhelek** [comment]
Thank you!  Your hunch was right. I had libraries still from a prior
version.  I was about to pull my hair out.  I really appreciate you
pointing me in the right direction.

On Sat, Mar 7, 2015 at 9:54 PM, Tobias Oetiker <notifications@github.com>
wrote:

> you could try ldd on the rrdtool binary
>
> also strings on the librrd that is linked to the rrdtool binary
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oetiker/rrdtool-1.x/issues/591#issuecomment-77733266>.
>



-- 

Matthew Gleed
Email: mgleed@gleed.us
Cell: 801-648-9653

**Comment by gjmkoper** [comment]
Dear all, 

it looks like the above information solves a problem I have:

I have the rrdtool installation on Jessie (tiny) installation of Debian (Raspberry Pi).
Both
--left-axis-formatter
--left-axis-format
are not recognized.
I have done the regular update/upgrade cycles but have no further clue how clue how to address this issue following the above remarks by the author. Can someone give clear instructions?

Thanks in advance,

Ger

**Comment by oetiker** [comment]
please make sure you are using rrdtool 1.6.0 OR rrdtool 1.5.6

**Comment by gjmkoper** [comment]
Thanks for your answer. 

Indeed, the version number is 1.4.8, the one that is distributed "apt-get" for the Raspberry Pi.

This would mean I would have to install rrdtool in another way, probably directly from github. Never done so before so if there is a simple workaround - I just want to use the package - then I will be most grateful.

Ger

**Comment by oetiker** [comment]
yes if your distro does not provide an up to date version of rrdtool you have to compile it ...

**Comment by gjmkoper** [comment]
Well, I managed to make the version 1.6.0 for a clean RPi with Raspbian Jessie Lite. The script to achieve this and the config.log file as well as a copy of the screen output can be studied using the following dropbox link: [https://www.dropbox.com/sh/d34je54d0h9fvu4/AADGLMvRw0RQ6cxlGolyxxlya?dl=0](url). 
I ran some of the test programs without any problem, so it seems to be ok as is although it is probably not complete. But so far I can use it for my purpose.

There is one small nagging thing: the rrdtool and associated commands are not readily included in the PATH statement. I am not sure what is the optimal method to achieve this so I request for an advice here. It should be added to the script that I made.

Thanks in advance for the advice,

Ger

**Comment by gjmkoper** [comment]
On another platform I was suggested to pre-upgrade to Raspian Stretch and that worked ( so far). See the discussion [](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=149933&p=996828#p996828)

**Comment by gjmkoper** [comment]
Dear all,

So the final answer is that version 1.6.0 will work with the Raspbian Stretch but when this will be released is unclear.  I tend to stick to my own solution then and maybe someone can tell me the preferred way to include the applications in the PATH.

Ger

**Comment by oetiker** [comment]
quite an adventure you are having here :) congratulations to your success!

**Comment by gjmkoper** [comment]
To complete, a prgamatic end to the above script

`# Replace previous RRD-files (previously installed with apt-get install rrdtool, links remain in place)
 cd /usr/bin
 sudo cp /opt/rrdtool-1.6.0/bin/rrdcgi .
 sudo cp /opt/rrdtool-1.6.0/bin/rrdupdate .
 sudo cp /opt/rrdtool-1.6.0/bin/rrdtool .
`
Not particurly bright but it works.

Ger

**Comment by DTFgithub** [comment]
@gjmkoper 
I have tried to install rrdtool with the use of your script on fresh new 2016-11-25-raspbian-jessie-lite and it was unsuccessful. Can you tell me onto which raspian-jessie-lite you successfully install rrdtool with the script?

**Comment by gjmkoper** [comment]
It was 2016-05-27 . I can send you a link to the binary or try it with yours if you would like to.

**Comment by DTFgithub** [comment]
I have tried with 2016-11-25 and 2016-05-27 and both was without success. Neither bash or python can find module named rrdtool. Just to double check your 2016-05-27 was jessie-lite? After installation of firmware did you only apply your script? Did you apply it with sudo or there is no need for it? Can you now reproduce successful installation of rrdtool from bare 2016-05-27? You said:" I ran some of the test programs without any problem, so it seems to be ok as is although it is probably not complete." Did you manage to use rrdtool with bash and python? This are two programs with which I need rrdtool to be functional.

**Comment by gjmkoper** [comment]
Today I installed a fresh version of raspbian on SD, the version of 2016-05-27 that I am still working with. Using `sudo raspi-config` I change hostname, internationalization options, switch on ssh and expand the filesystem after I ask for a restart.
I transfer a batch file using ssh, `chmod +x` it and launch it with `./install_rrdtool`. The batch file is available for an undetermined time available from this [link](https://www.dropbox.com/s/sg806nt4rdtd30t/install_rrdtool?dl=0).

It takes quite some time to process but after that, I do
```
pi@TestPi:~ $ rrdtool info
RRDtool 1.6.0  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Jan  4 2017 11:55:19

Usage: rrdtool [options] command command_options
* info - returns the configuration and status of the RRD

        rrdtool info [--daemon|-d <addr> [--noflush|-F]] filename.rrd

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages

```
As far as I know it then works if called as a system function for instance from python or c. 

Ger

**Comment by DTFgithub** [comment]
Strange, I also always after new install change all options which you stated with sudo raspi-config and also one which you did not, password. But after applying script rrdtool is unavailable by bash. 
But I follow one suggestion which was given to you to update to stretch and in it rrdtool 1.6 works 
Nevertheless, thank you.

**Comment by gjmkoper** [comment]
It seems that in your use of bash the path is not defined. In that case, as suggested by the author of the program, you should use the full path, i.e. `/usr/bin/rrdtool`.

Enjoy stretch but be aware of sudden malfunctions, it is still in development.

Ger

**Comment by Sawadee2u** [comment]
@gjmkoper,
First, thanks for the script, install_rrdtool. It works great and I have used it several times on my RPI 3B.
With the updating of rrdtool from 1.6.0 to 1.7.0 I tried to modify the file but have not had any luck. I changed the version from 1.6.0 to 1.7.0 and pkg-config-0.28.7 to 0.29.2...  No joy.
Could you please update this script or give me some guidance. 
Thank-you.
sawadee

**Comment by gjmkoper** [comment]
Yes, well that in itself does not surprise me. It will be some time from now before I have time to look into that. Should be back by september.

Ger

**Comment by gjmkoper** [comment]
Dear Sawadee2u

I had a look around, but it seems there is not yet an official version 1.7.0. Or am I mistaken? And if so, is there a particular reason for upgrading?

Ger

**Comment by oetiker** [comment]
see here https://github.com/oetiker/rrdtool-1.x/releases

**Comment by gjmkoper** [comment]
Thanks Tobias

I gave it a try, but instead of downloading and building pkgconfig I just installed it as a package for Raspbian: added to the apt-get install line with the other two packages. The modified script concluded successfully for Jessie Lite. 

Ger
