### ISSUE TITLE
Is it possible to show timezone abbreviation on graph?

### ISSUE THREAD

**Issue by deltamaster** [oetiker/rrdtool-1.x#593]
I would like to at least give the reader of the graph a hint about what the timezone is used in x-axis value.

Or an even better solution in my mind is to give rrdtool a parameter as "timezone", and rrd use that information to generate graph, and have x-axis time match the given timezone.

I do not find a way to do this, so I would like to ask if there is a way to achieve this.

**Comment by oetiker** [comment]
this will draw your chart in GMT and add the timezone to the chart.
    env TZ='GMT' rrdtool graph ... COMMENT:$TZ
