### ISSUE TITLE
1.4.8's xport/graph uses 40 x RAM and takes 8 x time compared to 1.4.7

### ISSUE THREAD

**Issue by pmorch** [oetiker/rrdtool-1.x#596]
The real-life scenario that caused us to investigate this was more complicated, but this simple test case demonstrates the issue:

I have an `.rrd` file with 200 ds-es in it, 1 RRA with 2 weeks worth of 5min samples.

2200 XPORT statements (on the same ds over these 2 weeks) uses > 6 GB RAM and takes about 4.5 s in 1.4.8, but uses about 165 MB and takes 0.5 s in 1.4.7. Memory usage just goes up as the 2200 goes up.

`git bisect` shows that this was introduced by commit 2948dde97fa8cef4f6c72e345601de566fc28e23:

    commit 2948dde97fa8cef4f6c72e345601de566fc28e23
    Author: Tobias Oetiker <tobi@oetiker.ch>
    Date:   Tue Apr 30 11:28:20 2013 +0200

        backport of the (C)DEF hash patch to accelerate processing of large (+100 statements) graph instructions.

It reverts cleanly on the 1.4.8 tag, and once reverted, the problem goes away.

So perhaps it speeds up +100 statements, but +2000 statements causes the out-of-memory-killer to start. We clearly see this as a regression.

Here is a script to reproduce this. For my 8GB RAM virtual machine, running `script.pl 2200` uses about 6GB of RAM. `script.pl 4000` causes the script to be killed by OOM-killer, but it doesn't even break a sweat in 1.4.7 (or 1.4.8 with 2948dde97fa8cef4f6c72e345601de566fc28e23 reverted).

    #!/usr/bin/perl -w
    use RRDs;
    use Time::HiRes;

    print "PID: $$\n";

    # 2200 works good for me to see it grow to about 6GB RAM before it finishes
    # "nicely" here on my 8GB x64 virtual machine.
    my $numberOfXports = $ARGV[0] or die "need numberOfXports";

    my $parent = $$;

    # Fork off a child to print memory usage of the parent process...
    my $child = fork;
    if (! $child) {
        # I'm the child
        while (1) {
            my $psout = `ps h -p $parent -o vsz,rss`;
            if ($?) {
                print "Exiting\n";
                exit;
            }
            my ($vsz, $rsz) = split(/\s+/, $psout);
            printf "%d/%d %5.0f MB(VSZ) %5.0f MB(RSS)\n", $parent, $$, $vsz/1024, $rsz/1024;
            sleep 1;
        }
        exit;
    }

    my $rrdFile = "file.rrd";
    my $ds = "ds1";

    if (-e $rrdFile) {
        unlink $rrdFile;
    }

    my $days = 15;
    my $rows = $days * 24 * 12;
    my $numberOfStats = 200;

    my @createParams = (
        '--start', sprintf('now - %dd', $days+1),
        $rrdFile,
    );

    foreach (1..$numberOfStats) {
        push @createParams, "DS:ds$_:GAUGE:600:U:U";
    }

    push @createParams, sprintf("RRA:AVERAGE:0.5:1:%d", $rows);

    RRDs::create(@createParams);

    my $startTime = time - $rows * 300;
    foreach (0..$rows) {
        RRDs::update($rrdFile, sprintf "%d:%d", $startTime, $_);
        $startTime += 300;
    }

    my $info = RRDs::info($rrdFile);
    my $lastUpdate = $info->{last_update};

    print scalar(localtime $lastUpdate), "\n";

    my @xportLines;

    # xport-ing the same $ds over and over again is of course useless, but this
    # is enough to trigger the high memory usage. Real-life test uses different $ds
    # - it doesn't matter
    foreach (1..$numberOfXports) {
        push @xportLines, (
            sprintf("DEF:stat%d=%s:%s:AVERAGE", $_, $rrdFile, $ds),
            sprintf("XPORT:stat%d", $_),
        );
    }

    # This corresponds to a row for every minute in 10 years.
    # That is a lot of rows!
    #                               => 10 * 366 * 24 * 60
    # We want "full data resolution"
    use constant MAX_ROWS_WORSTCASE => 5270400;
    push @xportLines, '--maxrows', MAX_ROWS_WORSTCASE;

    my $end =   $lastUpdate - 5 * 60;
    my $begin = $end - 7 * 24 * 60 * 60;

    printf "XPORTs: %d\n", scalar grep { /^XPORT:/ } @xportLines;

    my $t0 = Time::HiRes::time;

    my ( $xbegin, $xend, $xstep, $col, $legends, $values ) = RRDs::xport(
        "--start" => $begin,
        "--end"   => $end,
        @xportLines,
    );

    if (RRDs::error) {
        printf "Error: %s\n", RRDs::error;
    }

    printf "RRDs::xport took: %.2fs xstep: %d\n", Time::HiRes::time - $t0, $xstep;
    sleep 10;

**Comment by oetiker** [comment]
a hash map with 2000 entries should not take up 6GB or RAM ... hmmm

**Comment by oetiker** [comment]
I tried to reproduce this with the latest master, all seems fine there

**Comment by pmorch** [comment]
Good to know. But do we agree that it is broken in 1.4.8? I've seen this with a vanilla 1.4.8 package from Debian jessie and also when I built it from source.

When I reverted the commit in question, the RAM/time usage went back to normal...

**Comment by oetiker** [comment]
I don't know about 1.4.8 ... this is a past release ... current in the 1.4 series in 1.4.9 ... I have not run your test script with that yet ... will do ... and let you know.

**Comment by pmorch** [comment]
I [see](http://oss.oetiker.ch/rrdtool/pub/?M=D) that there is a [rrdtool-1.5.0-rc2.tar.gz](http://oss.oetiker.ch/rrdtool/pub/rrdtool-1.5.0-rc2.tar.gz) (soon to be 1.5.0?), so yeah, if its only in 1.4.8 and not in 1.5.0, then never mind - it not present in the (soon to be) current stable release.

Perhaps mention it in the change log?

We've already patched 1.4.8 so we're good here. Our itch has been scratched. Just wanted to share our findings. It caused the OOM to kick in in production after an upgrade to jessie, so that was not our proudest hour! :-)

Peter

**Comment by oetiker** [comment]
it is still present in 1.4.9 ... hmpf ... I am not aware of fixing it ... the patch for introducing this features was done for 1.5 and 1.4 in parallel, so my guess is the 1.4 implementation has an issue some how

**Comment by oetiker** [comment]
please use 1.5
