### ISSUE TITLE
Cannot use -INF in CDEF anymore

### ISSUE THREAD

**Issue by odoucet** [oetiker/rrdtool-1.x#597]
The following graph instruction stopped working around 1.4.9 :
```
CDEF:waboveeqxoutbits=aboveeqxoutbits,UN,-INF,UNKN,IF
```
Error returned : ERROR don't undestand '-INF,UNKN,IF'

Following is OK : 
```
CDEF:waboveeqxoutbits=aboveeqxoutbits,UN,INF,UNKN,IF
CDEF:waboveeqxoutbits=aboveeqxoutbits,UN,0,UNKN,IF
```

**Comment by oetiker** [comment]
hmmm ````-INF```` is ````NEGINF```` and has been like that for quite a while, at least in the 1.2 series, it has already been that

**Comment by odoucet** [comment]
I'm sure -INF was working on 1.4 serie (but maybe deprecated ?). It stopped working after a minor update.

**Comment by oetiker** [comment]
hmmm I can't find any evidence of that in the code or the documentation, but feel free to provide a patch.
