### ISSUE TITLE
modification date of rrd files not change on update

### ISSUE THREAD

**Issue by iHeadRu** [oetiker/rrdtool-1.x#603]
I migrate mrtg+rrdtool from FreeBSD 9.3 jail on ufs to FreeBSD 10.1 jail on zfs.
After that rrd files and graphs updated ok, but modification date of rrd files do not change on update.

**Comment by stevenh** [comment]
Do you mean the file timestamps don't change when you access them?

If so them maybe you have atime=off on the zfs filesystem?

**Comment by iHeadRu** [comment]
Yes, atime=off. But modification time != access time. Modification timestamps of rrd files are not changed on RRDs::update when called from mrtg.

**Comment by oetiker** [comment]
we had this problem on linux too at some point ... modification time and inode change time were not affected when memory mapped files were changed ... some kernel issue which was later fixed ... 

in any event, to compensate, rrdtool configure tries to figure out if this problem exists ... so if you recompile rrdtool on a zfs filesystem thus affected, it will compensate by touching the file after unmapping it.

**Comment by iHeadRu** [comment]
The problem was gone after recompiling rrdtool.
Thank you.
