### ISSUE TITLE
VERSION file is missing from rrdtool-1.5.0 archive causing bootstrap to fail

### ISSUE THREAD

**Issue by yarda** [oetiker/rrdtool-1.x#605]
$ ./bootstrap 
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal -I m4 --force -I m4
sh: VERSION: No such file or directory
configure.ac:40: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.14/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:40: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

$ echo 1.5.0 > VERSION
seems to resolve the problem.

**Comment by oetiker** [comment]
fixed by 20cea03889f18991b79f7ed759a6f3daaad5b255
