### ISSUE TITLE
One problem may exist in VDEF TOTAL

### ISSUE THREAD

**Issue by straywarrior** [oetiker/rrdtool-1.x#613]
I meet a problem when using TOTAL. 
When I change the width of the graph, the value calculated by TOTAL is changed...

For example, I made a script like this:
/usr/bin/rrdtool graph test.png  \
         --imgformat=PNG \
         --start=1429863100 \
         --end=1429949500 \
         --base=1000 \
         --height=160 \
         --width=1000 \
         --alt-autoscale-max \
         --lower-limit='0' \
         DEF:a="traffic_in.rrd":'traffic_in':AVERAGE \
         CDEF:cdefa='a,8,*' \
         VDEF:vdefa='a,TOTAL' \
         LINE1:cdefa#0000FFFF:"Inbound"  \
         GPRINT:vdefa:"Total\:%8.2lf %s" \

As you can see, I use a VDEF expression here and I print as Total on the graph...
At the beginning, the width is 1000 and then the Total will be 174 T
But If I change the width to 100, the Total may change to 183 T.
This kind of change always happens when I change the width of the graph...

**Comment by oetiker** [comment]
what version are you using ?

**Comment by straywarrior** [comment]
Thank you for your reply...
I used different versions, from 1.4.7 to 1.5.2... The problem looks like this... I'm sure that I do not change anything except the "width"..
![test](https://cloud.githubusercontent.com/assets/6890059/7336875/5a2bf96e-ec44-11e4-8110-ab0be5596b3c.png)
![test2](https://cloud.githubusercontent.com/assets/6890059/7336877/5f08622e-ec44-11e4-9192-a880b1c644d5.png)

**Comment by oetiker** [comment]
the total is always calculated from the data actually shown in the graph. But since we take pains to build averages, the total 'should' remain the same ... 

you could use rrdtool xport to look at the actual data involved ... 

or also try to do a test with artificial data.

**Comment by straywarrior** [comment]
Oh I see it... Thanks so much and I will try again... But there is another question: Can I export the result of TOTAL directly as a string rather than paint it on the graph? It will be more convenient to test it and  TOTAL is really a useful function so I want to use it without generating a graph... Thanks again for your reply.

**Comment by oetiker** [comment]
use PRINT instead of GPRINT ... and you get the number out ... either directly into your scripting language or on STDOUT if you are calling this as a command.
