### ISSUE TITLE
xff value parsing depends on locale

### ISSUE THREAD

**Issue by techms** [oetiker/rrdtool-1.x#617]
When creating a new rrd file, rrdtool tries to parse xff value according to the active locale and silently ignores a dot as a decimal separator. So we get unusable rrd file (xff=0) and don't know about it until the first portion of UNKNOWN data is collected.

How to reproduce:

$ cat ./test.sh
#!/bin/sh 
echo test 1
LC_ALL=C rrdtool create test1.rrd DS:test:GAUGE:600:U:U RRA:AVERAGE:0.5:3:700
rrdtool info test1.rrd | grep xff
echo test 2
LC_ALL=ru_RU.UTF-8 rrdtool create test2.rrd DS:test:GAUGE:600:U:U RRA:AVERAGE:0.5:3:700
rrdtool info test2.rrd | grep xff
rrdtool -v | head -1

$ ./test.sh
test 1
rra[0].xff = 5,0000000000e-01
test 2
rra[0].xff = 0,0000000000e+00
RRDtool 1.5.3  Copyright by Tobias Oetiker <tobi@oetiker.ch>

**Comment by oetiker** [comment]
working on a fix in 9656454

**Comment by oetiker** [comment]
please ceck!

**Comment by techms** [comment]
Now it works, thanks!
