### ISSUE TITLE
libdbi sql 

### ISSUE THREAD

**Issue by OsvaldoTCF** [oetiker/rrdtool-1.x#619]
Hi, 
I'm trying to build graphics using rrdtool and libdbi .
We are encountering problems because we can not understand the generated graphics.

A test we did, using the script and data below did not return the expected, the graph shows nothing .

Script:
#!/bin/sh

IP=122.22.174.251%2F32
s=-6600
e=-2000

DS_IBASE="sql//pgsql/host=hppqdbhost/dbname=hpdb/username=mkapi/password=mkdbdbaa/rrdminstepsize=300//queue/*hora/bytesin/ip='$IP'"
RRDDEBUGSQL=1 rrdtool graph "./consumo.png" --imgformat=PNG --start=$s --end=$e --step=300 -A -E --width=400 --height=300 --title="Consumo $IP" --vertical-label="Bytes" -F \
"DEF:mini=$DS_IBASE:min:AVERAGE" \
"LINE1:mini#00FFFFD0:download"

Result:
RRDDEBUGSQL: 1431733349: initialize libDBI
RRDDEBUGSQL: 1431733349: setting option host to hppqdbhost
RRDDEBUGSQL: 1431733349: setting option dbname to hpdb
RRDDEBUGSQL: 1431733349: setting option username to mkapi
RRDDEBUGSQL: 1431733349: setting option password to mkdbdbaa
RRDDEBUGSQL: 1431733349: connect to DB
RRDDEBUGSQL: 1431733349: executing SELECT hora as rrd_time, bytesin as rrd_value FROM queue WHERE ip='122.22.174.251/32' AND '2015-05-15 18:50:00' < hora AND hora < '2015-05-15 20:05:00'
RRDDEBUGSQL: 1431733349: timing 0
RRDDEBUGSQL: 1431733349: reached last table to connect to
RRDDEBUGSQL: 1431733349: close connection
RRDDEBUGSQL: 1431733349: shutting down libdbi
497x373

Data returned by the sql:
"2015-05-15 18:38:02.000475-03";53231
"2015-05-15 18:43:50.767194-03";317582
"2015-05-15 18:49:39.979604-03";343708
"2015-05-15 18:55:29.435003-03";455730
"2015-05-15 19:01:17.926812-03";3122790
"2015-05-15 19:07:05.17841-03";1463898
"2015-05-15 19:12:49.597242-03";2318801
"2015-05-15 19:18:34.088838-03";304948
"2015-05-15 19:24:20.507765-03";2085401
"2015-05-15 19:30:02.189282-03";1893864
"2015-05-15 19:35:46.073502-03";2049714
"2015-05-15 19:41:30.458964-03";1279752
"2015-05-15 19:47:11.932701-03";1170082
"2015-05-15 19:52:58.792726-03";765023

**Comment by oetiker** [comment]
I don't really have any experience with the libdbi bindings ... you might want to look into using the new cb// interface and provide the db interface using a perl callback.
