### ISSUE TITLE
Resolution seems not to work correctly when using RRDtool fetch

### ISSUE THREAD

**Issue by straywarrior** [oetiker/rrdtool-1.x#622]
RRDTool Version: 1.4.7
There is a rrd file which step is set to 60. That can be verified by rrdtool info:
````
rrd_version = "0003"
step = 60
last_update = 1433578208
header_size = 896
ds[traffic_in].index = 0
ds[traffic_in].type = "COUNTER"
.......
````
Then, when I execute
````
rrdtool fetch test.rrd AVERAGE -s e-2400 -e $((1433570000/600*600)) -r 600
````
It returns
````
......
1433569320: 2.0898873801e+07 2.6417223697e+07
1433569380: 2.0381825015e+07 2.6037986178e+07
1433569440: 2.2785677392e+07 2.7327018849e+07
1433569500: 2.1380392139e+07 2.4509891839e+07
1433569560: 2.1275919812e+07 2.1702734630e+07
1433569620: 2.2640017490e+07 2.1615265773e+07
1433569680: 2.2639382386e+07 2.2016332458e+07
1433569740: 2.2004986976e+07 2.3263099806e+07
1433569800: 2.0429678267e+07 2.3463282943e+07
1433569860: 1.9294841556e+07 1.9326364626e+07
````
Obviously the resolution set does not take effect. 
Is there something wrong?
Thank you...

**Comment by oetiker** [comment]
note that fetch does not change the data it returns, it simply figures out from the rrd file, which RRA holds data at the resolution requested (or higher) and provides coverage for the whole time range. It then returns this data. Also make sure to use a current version of RRDtool.
