### ISSUE TITLE
"rrdtool tune a.rrd --maximum ds:U" is not working

### ISSUE THREAD

**Issue by techms** [oetiker/rrdtool-1.x#624]
I'm trying to set the maximum DS value to 'U' according to the documentation, but get the following error:

$ rrdtool create test.rrd DS:test:GAUGE:600:0:100 RRA:AVERAGE:0.5:3:700
$ rrdtool tune test.rrd --maximum test:U
ERROR: invalid arguments for maximum ds value

I get the same error when trying to set the minimum DS value. I looked into the sources and there is no processing of 'U' values. Could you fix it please?

**Comment by oetiker** [comment]
fix is in ea33bd9 ... thanks!

**Comment by techms** [comment]
Thank you!

**Comment by ajcorrea** [comment]
We had this same problem here in some situations.

Running:

`rrdtool tune <filename.rrd> --maximum traffic_out:1.0000000000e+11 --maximum traffic_in:1.0000000000e+11`

did the trick.
