### ISSUE TITLE
ruby librrd graph stdout broken

### ISSUE THREAD

**Issue by avongluck-r1soft** [oetiker/rrdtool-1.x#625]
At this point in time, it seems you are unable to generate an rrdgraph to stdout in ruby.

The following code produces an array:
command: RRD.graph("-", *options)

Output: [[],324,543]

It looks like the ruby rrd bindings aren't catching stdout currently. The PNG data shows up on the ruby console, but there is no way to obtain it as it is executing through the bindings.  Having a way to stream RRD graph data would be super handy for all ruby RRD projects :-)

For now i'm writing the data out to disk and reading it back in :-\

**Comment by oetiker** [comment]
have you tried your luck with the `RRD.graphv("-",*options)`? Sending the graph to stdout seems a very crude method.

**Comment by avongluck-r1soft** [comment]
nope... graphv doesn't work either.

Not crude at all if you're generating rrdgraphs at-access via http and want to serve them up without writing out temporary files then reading them back in ;-)

**Comment by oetiker** [comment]
Since everything is in memory anyway send it via stdout in the first place ... with the graphv interface you get everything in memory ... so the thing dodo would be to fix the ruby bindings for graphv ... I am unfortunately not a ruby wizard.
