### ISSUE TITLE
RRDCACHED spaces in filenames

### ISSUE THREAD

**Issue by AaronTHolt** [oetiker/rrdtool-1.x#626]
I have found what I believe to be an issue with rrdcached. I'm using ganglia with rrdcached. When spaces are present in filenames the writes fail. I think it's an rrdcached issue because the writes succeed without rrdcached (but then I'm stuck with a file i/o issue instead). Below is some output from the write as well as the error from the log file. 

strace -s 999 -f -p $(pgrep gmetad) 2>&1 | grep write | grep -i rack
[pid 31108] write(65, "UPDATE /var/lib/ganglia/rrds/Rack 12/node1232-general.rc.colorado.edu/rx_bytes_eth1.rrd 1434749985:0.0000\n", 106 <unfinished ...>

tail -f /var/log/messages
Jun 19 15:20:34 rcstat1 rrdcached[29221]: handle_request_update: stat (/var/lib/ganglia/rrds/Rack) failed.

**Comment by oetiker** [comment]
hmm could it be that ganglia is using its own code for generating the updates it sends to rrdcached? In rrd_client.c (which is could use) strings with spaces do get escaped ... also rrd_client.c sends "update" and not "UPDATE" ...

**Comment by AaronTHolt** [comment]
It certainly could be. I couldn't convince myself whether or not it was rrdcached or ganglia with rrdcached so I posted on both. Thanks for the speedy response!
