### ISSUE TITLE
test suite is failing when using http://oss.oetiker.ch/rrdtool/pub/rrdtool-1.5.3.tar.gz, missing DIST files

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#631]
Hi

When running the tests, I get:
(...)
make  check-TESTS
make[3]: Entering directory '/home/nirgal/kod/debian/rrdtool/tests'
make[4]: Entering directory '/home/nirgal/kod/debian/rrdtool/tests'
PASS: modify1
PASS: modify2
PASS: modify3
PASS: modify4
PASS: modify5
PASS: tune1
PASS: tune2
make[4]: *** No rule to make target 'rpn1', needed by 'rpn1.log'.  Stop.

I think some files are missing in EXTRA_DIST in tests/Makefile.am

For example, ***there is no file tests/rpn1 in the tar.gz***

Here's the list of tests that fails:
rpn1
dump-restore
create-with-source-1
create-with-source-2
create-with-source-3
create-with-source-4
create-with-source-and-mapping-1
create-from-template-1

**Comment by oetiker** [comment]
fix is in fa10619
