### ISSUE TITLE
Missing dependency on libpng

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#632]
On Debian GNU/Linux stable, using http://oss.oetiker.ch/rrdtool/pub/rrdtool-1.5.3.tar.gz and

./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-silent-rules --disable-python --disable-ruby --docdir=/usr/share/doc/rrdtool "--with-perl-options=INSTALLDIRS=vendor INSTALL_BASE=" --with-tcllib=/usr/lib/x86_64-linux-gnu/tcl8.6 "CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security" CPPFLAGS=-D_FORTIFY_SOURCE=2 "CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security" "FCFLAGS=-g -O2 -fstack-protector-strong" "FFLAGS=-g -O2 -fstack-protector-strong" "GCJFLAGS=-g -O2 -fstack-protector-strong" LDFLAGS=-Wl,-z,relro "OBJCFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security" "OBJCXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security" RRDDOCDIR=/usr/share/doc/rrdtool

I get:
Libraries: -lm  -ldbi -ldl -lglib-2.0  -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lcairo  -lxml2 

which is missing libpng

Note that with version 1.4.8, I used to have:
Libraries: -lxml2 -lglib-2.0 -lcairo -lcairo -lcairo -lm  -ldbi -ldl -lcairo -lpng12  -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lcairo

this results in more warnings later when building the package:
```
dpkg-shlibdeps: warning: symbol png_read_info used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_destroy_read_struct used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_get_image_width used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_init_io used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_create_read_struct used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_get_image_height used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_create_info_struct used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_read_info used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd_th.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_get_image_width used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd_th.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_destroy_read_struct used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd_th.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_create_read_struct used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd_th.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_init_io used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd_th.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_create_info_struct used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd_th.so.4.3.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol png_get_image_height used by debian/librrd4/usr/lib/x86_64-linux-gnu/librrd_th.so.4.3.0 found in none of the libraries
```
and ultimately in a missing dependency for the newly created package.

I resolved the issue by uncommenting (removing the dnl) on that line in configure.ac:
```
EX_CHECK_ALL(png,        png_access_version_number, png.h,                  libpng,      1.4.8,  ftp://ftp.simplesystems.org/pub/libpng/png/src/, "")
```

I suspect this might be a real issue when building a static version.

**Comment by oetiker** [comment]
Hmmm that is odd. The reason I removed all these dependencies is that pango has a cairo dependency anyway and cairo has a png dependency and so on ... does your cairo not have a png dependency ?

**Comment by nirgal** [comment]
I dig a little more in that issue.

First thing: You are right. The dependency come transitively.

However, I believe code should link against libraries it uses.

As far as I can tell, rrdtool doesn't uses  fontconfig nor freetype directly. But it does use png directly, for example in src/pngsize.c.

Debian has some nice tools, like dpkg-shlibdeps that will explore the used symbols and set the minimal version of any used lib, so that all these symbols are provided. This system didn't work there. I made a patch of my work around, that is good enough for me.

Fell free to close that issue. I will dig more when I have time, I don't like patches. ^^

**Comment by oetiker** [comment]
a2e41a7 adds the check back in
