### ISSUE TITLE
Documentation for rrddump/restore XML

### ISSUE THREAD

**Issue by iaean** [oetiker/rrdtool-1.x#644]
Hi @oetiker,

Some day I was impelled to delete some data from RRD files. I modified the `rrddump` XML via XSLT before doing a `rrdrestore`, to achieve this.

I created
  https://gist.github.com/iaean/1ea62ddea3c63d584c44
for people who have similar problems.

It would be great, if you could provide a little bit of documentation for the XML interchange format.
If you like the solution in the gist, feel free to publish it forwards to your users.

Thanks for your patience.
I'm always excited to hear from you.
Best regards

**Comment by oetiker** [comment]
Hi iaean, could you add this to the wiki ?

**Comment by iaean** [comment]
Sure. Give me some days...

**Comment by iaean** [comment]
Hi @oetiker,

created a new Wiki page for that. Hoping someone provides short doc for the rrddump/restore XML or provides a patch to move comments into XML attributes...

Issue finished. Am I right?

Thanks for your patience.
I'm always excited to hear from you.
Best regards

**Comment by oetiker** [comment]
thanks!
