### ISSUE TITLE
Using -A for making a graph will result in erratic y-axis labeling

### ISSUE THREAD

**Issue by Kabuse** [oetiker/rrdtool-1.x#647]
I am making a graph for barometric pressure and use -A for getting the full scale on the y-axis, but the labeling will be someting like 1010, 1018,1020.

The lines inbetween have no values. This looks strange and kind of faulty.

Using --ridgig, the y-axis is labeled more regularly, but I don't want the line of the graph to touch the top and the bottom.

**Comment by oetiker** [comment]
what version of rrdtool are you using ?

**Comment by Kabuse** [comment]
Sorry, I am using 1.4.7.

I've seen that 1.5.3. is available already.

I just thought with this, I will get the latest version already (Raspberry
Pi 2 with Raspian, Debian 7.8):

sudo apt-get update
sudo apt-get install rrdtool

How can I upgrade?

Thanks,

Bernd

2015-08-04 23:09 GMT+02:00 Tobias Oetiker <notifications@github.com>:

**Comment by oetiker** [comment]
for now you have to compile from source ... since you are running on arm, you may want to wait for 1.5.4 or compile the tip of the 1.5 branch since a few arm fixes went in since 1.5.3
