### ISSUE TITLE
librrd should not call exit()

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#653]
Hi

When you enable extra lintian tests, one can see this warning:
https://lintian.debian.org/tags/shlib-calls-exit.html

Basically, a library should never kill the calling process.

I could find only one instance of exit() in the librrd code: in rrd_graph.c, in reduce_data().
It make sense to yell a lot if a rrd file is corrupted; But I don't think the calling process should be killed altogether. (I wonder if this triggers a daemon hard shutdown?)

**Comment by oetiker** [comment]
fixed

**Comment by nirgal** [comment]
thanks :)
