### ISSUE TITLE
Build failure if pod2html is not installed

### ISSUE THREAD

**Issue by yarda** [oetiker/rrdtool-1.x#656]
rrdtool-1.5.4:
...
checking for pod2html... no
...
GEN      rrdbuild.html
/bin/sh: no: command not found
Makefile:706: recipe for target 'rrdbuild.html' failed

By checking doc/Makefile:706:
.pm.html .pod.html .pl.html:
  $(AM_V_GEN)no --infile=$< --outfile=$@ --noindex --htmlroot=. --podpath=. --title=$*

I think it should be conditional.

**Comment by oetiker** [comment]
thanks!
