### ISSUE TITLE
(minor) Incorrect permission of RRDCached.pm

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#658]
Hi

After installation, RRDCached.pm has permission 755 (executable).
However, that file is neither a ELF nor starts with #!, so it should not.

I don't know much about perl. So my guess is that:
- If you'd like to make it an executable, it should be renamed to .pl, and a proper shebang should be added.
- If you're happy to keep it as a perl module and not a perl script, then in `examples/rrdcached/Makefile.am`, it should be moved from section `examples_SCRIPTS` to `examples_DATA`

**Comment by oetiker** [comment]
yes ... it does not have to be executable ... do you want to patch, or should I (will take a bit since I am on another task atm).

**Comment by nirgal** [comment]
I'll do it in a minute
