### ISSUE TITLE
xport does not show the timestamp

### ISSUE THREAD

**Issue by lilorox** [oetiker/rrdtool-1.x#672]
Hello,

In version 1.5.4, xport does not include the timestamp in the data returned.

Example:
```
$ rrdtool xport --start now-10min \
DEF:loss=my.rrd:loss:AVERAGE CDEF:trend=loss,300,TREND XPORT:loss XPORT:trend
<?xml version="1.0" encoding="ISO-8859-1"?>
<xport>
  <meta>
    <start>1442909880</start>
    <end>1442910480</end>
    <step>60</step>
    <rows>10</rows>
    <columns>2</columns>
    <legend>
      <entry></entry>
      <entry></entry>
    </legend>
  </meta>
  <data>
    <row><v>0.0000000000e+00</v><v>NaN</v></row>
    <row><v>0.0000000000e+00</v><v>NaN</v></row>
    <row><v>0.0000000000e+00</v><v>NaN</v></row>
    <row><v>0.0000000000e+00</v><v>7.5000000000e-01</v></row>
    <row><v>0.0000000000e+00</v><v>0.0000000000e+00</v></row>
    <row><v>0.0000000000e+00</v><v>0.0000000000e+00</v></row>
    <row><v>0.0000000000e+00</v><v>0.0000000000e+00</v></row>
    <row><v>0.0000000000e+00</v><v>0.0000000000e+00</v></row>
    <row><v>NaN</v><v>NaN</v></row>
    <row><v>NaN</v><v>NaN</v></row>
  </data>
</xport>
```

There does not seem to be an option to add it in the result according to the manpage.

Is this normal?

Regards,
Pierre

**Comment by oetiker** [comment]
since you do have start and step (and end) a timestamp would be redundant information.

**Comment by lilorox** [comment]
Ok so this behavior is slightly different from v1.4 where the timestamp is specified.
Thanks

**Comment by oetiker** [comment]
hmmm ... looking through the code I see that the time was indeed included by default ... the whole xml xport code has been rewritten from scratch for 1.5 and that column became optional ... but there is no user accessible API to activate it ... would 67b0cde make things work for you again ?

**Comment by lilorox** [comment]
Nope this commit does seem to be enough to reactivate the timestamp in xport.

**Comment by lilorox** [comment]
sorry didn't see the --showtime
It's perfect !

**Comment by oetiker** [comment]
ok change is merged into 1.5.x branch

**Comment by petmue** [comment]
When I compile rrdtool from the master branch it claims to version 1.5.4 and --showtime is avaible.
But when I download the source code 1.5.5 from the website and look into the code, --showtime is missing.
Have you forgotten to merge it into 1.5.5.? I'm a little confused!

**Comment by oetiker** [comment]
yea there was a change of plan ... 1.5.x gets only bugfixes no new features ... in a few weeks you will see 1.6 with new features including this one ...

**Comment by oetiker** [comment]
e33b6ea
