### ISSUE TITLE
Wrong package uploaded to http://oss.oetiker.ch/rrdtool/pub/?M=D

### ISSUE THREAD

**Issue by alex88** [oetiker/rrdtool-1.x#674]
Seems that 1.5.3 is the same file as 1.5.4 (discovered since homebrew throws a checksum error when installing it)

**Comment by oetiker** [comment]
oops ... thanks ... fixed (I must have executed the publication task before properly updating the version)

**Comment by alex88** [comment]
Thanks, in the meantime i've upgraded the brew formula to 1.5.4
