### ISSUE TITLE
Locking issues when using RRDs in a threaded application (freeradius plugin)

### ISSUE THREAD

**Issue by ezanolin** [oetiker/rrdtool-1.x#675]
I have written a perl plugin for Freeradius that uses the RRDs library. The Freeradius Perl module spawns multiple threads  based on load, and I seem to be running into some issues under load.

When 2 threads try to update different RRD files at the same time using "RRDs::update" I get the following errors out of "RRDs::error".

Thread A: `opening 'dummy': No such file or directory`
Thread B: `/var/lib/rrd/u/username@test.domain.rrd: opening 'dummy': No such file or directory`

Yes they really are different files  I promise :)

Thread B mentions the filename I am updating whereas thread A does not. It always does this. Sometimes they appear in the reverse order in the log, but we can assume this is just because of timing and timeslicing artefacts.

Is RDDs not using the librrd thread safe calls (*_r variant)?
Should I be using RRDp instead?

**Comment by oetiker** [comment]
please check rrdtool 1.5 it is now fully threadsafe
