### ISSUE TITLE
Export rrdc_create and rrdc_create_r2 symbols

### ISSUE THREAD

**Issue by GrayTShirt** [oetiker/rrdtool-1.x#686]
I was attempting to duplicate logic in a C daemon to connect to the cache daemon if the daemon was configured, and if not create the rrd manually here's a snippet:

``` C
  if (OPTION && ! rrdc_is_connected(OPTION)) {
    rc = rrd_create_r2(...);
  } else {
    rc = rrdc_create_r2(...);
  }
  if (rc != 0)
```                    
but it turns out I was getting an undefined reference when I compiled, because the symbol wasn't exported.

I can probably work around it but calling rrd_create with the daemon option but rrdc_update is already exported so I figured maybe we can export the daemon create methods too.

**Comment by oetiker** [comment]
how about makeing this complete, exporting all the *interesting* rrdc functions and updating doc/librrd.pod accordingly ... that would be a worthy patch :)

**Comment by GrayTShirt** [comment]
you opensource maintainers are all the same, so demanding of free labor ;)

Sure I can do that, may take a little longer though

**Comment by oetiker** [comment]
a greedy bunch we are I know ...

**Comment by GrayTShirt** [comment]
Ok, updated the PR, and rebased my branch. Have fun o7

**Comment by GrayTShirt** [comment]
ok, going to go ahead and close this ticket then!

**Comment by jhunt** [comment]
Doesn't look like this made it into the Nov 10 1.5.5 release (missed it by a day!)

Any ETA on getting this into a "stable" dist, like a 1.5.6?

**Comment by jhunt** [comment]
here's my `nm` output:

```
→  nm -a ~/sw/lib/librrd.so.4.3.5 | grep rrdc
00000000000486fa T rrdc_connect
0000000000048334 t rrdc_connect_network
00000000000481e9 t rrdc_connect_unix
000000000004993d t rrdc_create
000000000004998c t rrdc_create_r2
00000000000488ae T rrdc_disconnect
0000000000049e90 t rrdc_fetch
0000000000048b96 t rrdc_filebased_command
000000000004962c t rrdc_first
0000000000048deb T rrdc_flush
000000000004b946 t rrdc_flush_if_daemon
0000000000048e0c t rrdc_forget
0000000000048e2d t rrdc_info
00000000000481d5 t rrdc_is_any_connected
0000000000048159 T rrdc_is_connected
000000000004937a t rrdc_last
000000000004bd2f T rrdc_stats_free
000000000004b9ef T rrdc_stats_get
00000000000488d6 T rrdc_update
```

**Comment by oetiker** [comment]
#687 went into master ... it is an api change so it will be included in 1.6 due out in a few weeks ... just got funding approval for this.

**Comment by jhunt** [comment]
Thanks!

**Comment by GrayTShirt** [comment]
bump
on an aside, what needs to be done for 1.6? I would be happy to help out.

**Comment by oetiker** [comment]
I need to implement a percentile cdef function ... almost done ... but other tasks keep taking up time ... if nothing bad happens I should be able to get everything done to get master into a pre 1.6 state before the end of the week.
