### ISSUE TITLE
Same bug as "Issue with DEF in 1.5.0_rc1 #581" with other error message in 1.5.51.5.5

### ISSUE THREAD

**Issue by danieldelacrua** [oetiker/rrdtool-1.x#697]
Same bug as in: https://github.com/oetiker/rrdtool-1.x/issues/581
with DEF = 'cf' or 'rrd' or 'vname'

but with other error message

example:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start=-86400 \
--end=-300 \
--title='temperature' \
--base=1000 \
--height=120 \
--width=800 \
--alt-autoscale-max \
--lower-limit='0' \
--vertical-label='Temperature' \
--slope-mode \
--font TITLE:10: \
--font AXIS:7: \
--font LEGEND:8: \
--font UNIT:7: \
DEF:cf="temperature.rrd":'temp':AVERAGE \
LINE1:cf#0000FFFF:"Temperature" \
GPRINT:cf:LAST:"Current:%8.2lf %s" \
GPRINT:cf:AVERAGE:"Average:%8.2lf %s" \
GPRINT:cf:MAX:"Maximum:%8.2lf %s\n" \

ERROR: cf is not a vname nor a number

**Comment by oetiker** [comment]
this is because you are using a deprecated syntax for GPRINT ... us VDEF and GPRINT, then things should work out fine ...
