### ISSUE TITLE
debian/README is outdated

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#705]
The git repository currently is at
https://anonscm.debian.org/cgit/pkg-rrdtool/rrdtool.git
so that debian/README should be updated.

That file was last updated 7 years ago. Since august 2012, debian policy is to write the location of the packaging repository directly in the debian/control file, so that the information is well exposed, for example at: https://packages.qa.debian.org/rrdtool
So I wonder whether that file should be entirely removed...

**Comment by oetiker** [comment]
sure ... I am not current with debian customs ... create a PR for what you think makes most sense ...
