### ISSUE TITLE
rrdtool restore sets a limit of 19 characters when reading (version: 1.5.4 on ubuntu)

### ISSUE THREAD

**Issue by eg-altapay-com** [oetiker/rrdtool-1.x#713]
'xapi_free_memory_kib' is longer than 20

**Comment by oetiker** [comment]
data source names can not be longer than 19 characters that intrinsic to the rrd format ... see  https://github.com/oetiker/rrdtool-1.x/blob/master/src/rrd_format.h#L162

**Comment by eg-altapay-com** [comment]
Ahh, that explains it. For reference, the XML received from XenServer contains many names longer than that.

**Comment by oetiker** [comment]
does xenserver export an rrd dump xml fil ? wow :)

**Comment by eg-altapay-com** [comment]
Yes: http://wiki.xen.org/wiki/XAPI_RRDs and they allow updates in "xport" format

**Comment by dmak** [comment]
I still think that error message is erroneous, as the string is 'longer or equals to 20':
```
$ rrdtool restore file.dump file.rra
ERROR: 'usb2_corruption_errs' is longer than 20
$ echo -n 'usb2_corruption_errs' | wc -c
20
```
Is it in general possible to increase this limitation? I would like to have UUID or drive ID as datasource name (I would vote for ultimate 255 size = 254 length).

**Comment by oetiker** [comment]
you can alter the size of the label, but your rrd files will be incompatible with other rrd files ... see rrd_format.h to alter the size

**Comment by dmak** [comment]
Technically that is possible but then I would need to patch every future RRDTool release (and say goodbuy to automatic updates from package repository). On the other side I understand that doing that kind of change in master means that all users would need to dump and restore all their rrd files :( There is no nice way out.
