### ISSUE TITLE
rrdtool tune delrra

### ISSUE THREAD

**Issue by cptkrabs** [oetiker/rrdtool-1.x#719]
Hi there !

I want to delete a rra from a rrd file (cacti) but when I run the command, it just shows DS information and nothing is removed : 

   rrdtool tune 11416.rrd DELRRA:5
DS[traffic_in] typ: COUNTER     hbt: 120        min: 0,0000     max: 1000000000,0000
DS[traffic_out] typ: COUNTER    hbt: 120        min: 0,0000     max: 1000000000,0000

If I check with "rrdtool info", rra[5] is still there... what's wrong ?
Thanks !!

debian 7.4
rrdtool 1.4.7-2

**Comment by oetiker** [comment]
that is a feature that was added in rrdtool 1.5
