### ISSUE TITLE
rrdtool.dump() AttributeError: 'module' object has no attribute 'dump'

### ISSUE THREAD

**Issue by helgisteinar** [oetiker/rrdtool-1.x#720]
Hi, I got RRDtool V 1.4.8 installed.  Testing out Python bindings I ran into a issue.

    >>> import rrdtool
    >>> rrdtool.graph()
          Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          rrdtool.error: missing filename
    >>> rrdtool.dump()
          Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          AttributeError: 'module' object has no attribute 'dump'
    >>>

Looks like something is not working with dump. Same error happens when including a filename.

**Comment by oetiker** [comment]
in the current version of rrdtool (1.6.0) dump is part of the python bindings ...
