### ISSUE TITLE
Easy way to compare 2 RRDs

### ISSUE THREAD

**Issue by michalbachowski** [oetiker/rrdtool-1.x#725]
Hi,

I'm looking for simple way to compare 2 RRD files. Our first solution was to use `dump` on both RRDs and compare output. This was most accurate but also the slowest so we added additional check before doing `dump` - we do `info` and compare last update times and `unknown_datapoints`. This is better but it still takes significant amount of time to finish.
The obvious choice here would be to calculate checksum for the files and if they differ then do `dump` to find out why the difference.
However there is a problem - initial checksums for empty file differ. If I create two files using same create string, eg.: `rrdtool create source1.rrd --start "epoch+1469791397" --step 300 RRA:AVERAGE:0.5:1:1200 RRA:AVERAGE:0.5:6:1536 RRA:AVERAGE:0.5:24:1550 RRA:AVERAGE:0.5:228:1594 DS:value:GAUGE:600:U:U` created RRDs have different checksums. Is there an option to make `rrdtool create` produce same output each time it is called with the same input (step and schema)?

**Comment by oetiker** [comment]
rrdtool creates fresh rrds with randomized starting points for their rras, to spread the load on disks as RRAs wrap to the next diskblock.

also if rrd info is slower than building a checksum of an entire rrd file, I am pretty sure you are doing something wrong ... 

make sure you use the language bindings, to avoid having to reload rrdtool every time ... or use the pipe interface by starting 'rrdtool -'

**Comment by michalbachowski** [comment]
Wow, that was super fast reply :-) Thank you.
