### ISSUE TITLE
segfault error 6 in librrd.so.4.3.5

### ISSUE THREAD

**Issue by openUser1** [oetiker/rrdtool-1.x#728]
This is an ubuntu xenial container running on lxd/lxc ubuntu
Container host
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

Container
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

via dmesg
rrdtool[145441]: segfault at 0 ip 00007fb18f24decb sp 00007ffc2f594800 error 6 in librrd.so.4.3.5[7fb18f217000+51000]

The app creating the rrd's is librenms
8aa5699 - Wed Aug 03 2016 08:38:18 GMT+1200

**Comment by oetiker** [comment]
please report this to the ubuntu bugtracker
