### ISSUE TITLE
xport json - large values missing on 32-bit system

### ISSUE THREAD

**Issue by ahenning** [oetiker/rrdtool-1.x#736]
I noticed some values above 4GB were missing using json output on a 32-bit system:
rrdtool graph file.json --imgformat JSONTIME -s -1Month 
                DEF:out=$db:out:AVERAGE 
                CDEF:bits=out,8,*
                CDEF:test=out,10,/
                VDEF:testb=test,TOTAL
                VDEF:tot=out,TOTAL
                "AREA:bits#556E0ACC:Out    \t"
                "LINE1:bits#556E0A"
                "GPRINT:testb:%5.1lf %sB"
                "GPRINT:tot:%5.1lf %sB"

test divides by 10 to reduce the test number and would successfully print 3GB while the total is actually about 30GB which is missing. Once the number goes above 4GB it seems to go missing from the json output e.g.:
        { "gprint": "3142614492 B" },
        { "gprint": "" },

This seems to only occur on a 32-bit system. After some trial and error it seems to be in rrd_snprint that drops the value if its too large. Replacing rrd_snprintf with snprintf somehow resolved the issue. This line was changed in rrd_xport.c:

//        rrd_snprintf(dbuf,sizeof(dbuf), im->gdes[i].format, printval,"");
           snprintf(dbuf,sizeof(dbuf), im->gdes[i].format, printval,"");

I am not sure if this is the correct solution, whether the change might help someone else or it may cause other issues. Please close this issue if not applicable to normal conditions.

Tested on versions 1.5.4, 1.5.6. 1.6.0

**Comment by oetiker** [comment]
going (back) to sprintf unfortunately is not the solution, the output of sprintf is locale dependent, causing your json will contain localized numbers if someone runs rrdtool with an appropriate locale setting ... see also the man page for sprintf (search for locale)

**Comment by oetiker** [comment]
what happens if you use %0.10e as your output formatting char

**Comment by ahenning** [comment]
escape JSON 3.142614492e+09:
escape JSON 3.142614492e+10:

Actually tried that earlier and still had the output. That is with rrd_snprintf and %0.10e.

If its only locale settings I have to worry about then I can live with the not so great work around for now since I am not expecting locale setting changes.

**Comment by ahenning** [comment]
if this is not a general problem for everyone with xport jsontime on 32-bit, then we can close this issue.

**Comment by oetiker** [comment]
I guess it is ... I am all for a patch if you have one but it needs tobe for rrd_sprintf

**Comment by ahenning** [comment]
Ok, I'll create a pull request if I figure it out.
