### ISSUE TITLE
Undocumented, unenforced 19 character limit on ds-names

### ISSUE THREAD

**Issue by schnoebe** [oetiker/rrdtool-1.x#738]
In tracking down a core dump from within a perl program using rrdtool's RRDs module, I discovered that the ds-name field of a CDEF is limited to 19 characters.

This limit is not documented, nor is it checked.  However, if the caller exceeds the 19 character limit, there is a core dump (at least on Intel systems) as the ds-name string is copied onto other internal structure elements.

The limit is defined in src/rrd_format.h, as DS_NAM_SIZE (20), and used in src/rrd_format.h inside struct ds_def_t.  It is used in src/rrd_graph.h, in the structure graph_desc_t.

A small perl script using the fetch call back functionally demonstrates the issue.
[fetch_cb-failure-ex.pl.txt](https://github.com/oetiker/rrdtool-1.x/files/460410/fetch_cb-failure-ex.pl.txt)

**Comment by oetiker** [comment]
#739 should fixes this
