### ISSUE TITLE
rrdcached: can't create pid file '/var/rrdtool/rrdcached/rrdcached.pid' (File exists) rrdcached: daemonize failed, exiting.

### ISSUE THREAD

**Issue by Manoj-red-hat** [oetiker/rrdtool-1.x#740]
If somehow got corrupted, rrdcached cannot be started.

There are three possibilities of failure of RRD Daemon with existing pid file
1) File exist but contains garbage other than numeric 16 byte data which results atoi fail.
[ before returning -1 we should remove pid file]
2) File exist but truncated to zero size in which condition read fails.
[ before returning -1 we should remove pid file]
3) File exist but system unable to open file with r/w permissions.

`rrd_deamon

		main
		|
		|
		\
		  \		
		   \
			status=deamonize
					|
					|
					\
					 \	
					  pid_fd=open_pidfile("create", O_CREAT|O_EXCL|O_WRONLY)   
					  ( If file exixt open_pidfile fails with error message 
			            can't create pid file '/var/rrdtool/rrdcached/rrdcached.pid' (File exists))
					    |
						|
						if (pid_fd < 0)
						|	  \
							 pid_fd = check_pidfile();
						|			|
								   pid_fd = open_pidfile("open", O_RDWR);
									|
						|          if (pid_fd < 0)
												   \
						|							return pid_fd;

								   if (read(pid_fd, pid_str, sizeof(pid_str)) <= 0)
						|	                     	\
													   return -1;  (if Trucated file)

						|		   pid = atoi(pid_str);
												   \
						|							if (pid <= 0)  (if string to integer conversion returns negative)
													 \
						|							  return -1;

						|
					    if (pid_fd < 0)
					        \
							 return pid_fd;
							 
			if (status != 0)  
			{
				fprintf (stderr, "rrdcached: daemonize failed, exiting.\n");
				return (1);
			}`

**Comment by oetiker** [comment]
nice analysis ... a PR would be great

**Comment by Manoj-red-hat** [comment]
Thanks @oetiker Sir,

Sorry, but i didn't understand what is PR ?

Need your opinion,
 
Approach 1:-
1) File exist but contains garbage other than numeric 16 byte data which results atoi fail.
[ before returning -1 we should remove pid file]
2) File exist but truncated to zero size in which condition read fails.
[ before returning -1 we should remove pid file]
3) File exist but system unable to open file with r/w permissions.
[ before returning -1 we should remove pid file]

Approach 2:-
/etc/init.d/rrdcached : change start logic 
if stale file exist, which is corrupted than remove it,
rest is handled but our rrd_deamon existing code.

 1 corner case that need to be handled:-
[[  
     If pid file of a running rrd daemon get corrupted, then how do we ensure 
     that before starting a new rrd daemon it will check for existing rrd daemon 
     in system.
  ]]

Please suggest me, if there is some alternative approach 
i will try to fix this issue :)

**Comment by oetiker** [comment]
Hi @Manoj-red-hat, a PR is a Pull Request ... that is how you can provide your changes to projects on github.

If the pid files exists but contains the PID of a process that is not currently existing (test with kill -0) then start regardless and create a new pid file.

In all other cases where the pid file exists, exit with an error code, and also output an error message about the nature of the problem.

**Comment by Manoj-red-hat** [comment]
I understand i will update error messages according to nature of PID file status.

**Comment by Manoj-red-hat** [comment]
Hello @oetiker  sir,

remote: Permission to oetiker/rrdtool-1.x.git denied to Manoj-red-hat.
fatal: unable to access 'https://github.com/oetiker/rrdtool-1.x.git/': The requested URL returned error: 403
I am getting error during push

**Comment by oetiker** [comment]
you can not push directly into my repo ... you first have to fork the repo, the in your own clone do a

git checkout -b errors
... edit ... 
git push

and then create a pull request within github from your changes ... as soon as github sees your changes it will offer you to create a pull request

**Comment by Manoj-red-hat** [comment]
Sir,

I am getting again this error on another development environment
Starting rrdcached: rrdcached: can't create pid file '/var/rrdtool/rrdcached/rrdcached.pid' (File exists)
rrdcached: daemonize failed, exiting.

OS stop start gracefully.
Is there any other reason for the above message ?

**Comment by Manoj-red-hat** [comment]
@oetiker Sir,

stat /var/rrdtool/rrdcached/rrdcached.pid
  File: `/var/rrdtool/rrdcached/rrdcached.pid'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 806h/2054d	Inode: 262886      Links: 1
Access: (0644/-rw-r--r--)  Uid: (  600/john)   Gid: (  600/john)
Access: 2016-09-27 00:57:50.763898127 +0000
Modify: 2016-09-27 00:57:50.764898127 +0000
Change: 2016-09-27 00:57:50.764898127 +0000

Using dummy code i found that below read call failed
https://github.com/oetiker/rrdtool-1.x/blob/master/src/rrd_daemon.c#L532

But its confusing how only this file  /var/rrdtool/rrdcached/rrdcached.pid getting truncated on reboot ?

--------Suggestion---------------
rrdcached manual page:
`The daemon will blindly write to any file it gets told, so you really 
should create a separate user just for this daemon.`

Should also create a separate rrdtool directory under /var/run/,
Give permission to RRD belonging user, So that during reboots OS take care of 
PID files, it increase robustness of rrdcached.

**Comment by oetiker** [comment]
running daemons under a separate user is nothing but common sense, but feel free to create a PR.

**Comment by Manoj-red-hat** [comment]
Committed
