### ISSUE TITLE
Mis-handling timestamps when sizeof(time_t) != sizeof(long) (?)

### ISSUE THREAD

**Issue by he32** [oetiker/rrdtool-1.x#749]
It seems that rrdtool 1.60.0 mis-handles timestamps in an rrd database when it does
"rrdtool dump" when the host system has a time_t type which is larger than long, as is
the case on NetBSD/i386 where time_t is 64 bits, while long is 32 bits.

A recently created rrd database filled with a few samples and given to "rrdtool dump" produces

```
                    <!-- 2152-11-24 22:28:16 CET / 1476802800 --> <row><v>1.113549608e+02</v><v>1.069877135e+01</v></row>
                    <!-- 2152-11-24 22:58:16 CET / 1476804600 --> <row><v>1.202089651e+02</v><v>8.446735203e+01</v></row>
                    <!-- 2152-11-24 23:28:16 CET / 1476806400 --> <row><v>1.506548764e+05</v><v>4.057508256e+06</v></row>
                    <!-- 2152-11-24 23:58:16 CET / 1476808200 --> <row><v>2.785666863e+05</v><v>3.966554052e+07</v></row>
                    <!-- 2152-11-25 00:28:16 CET / 1476810000 --> <row><v>1.744465412e+05</v><v>2.087267285e+07</v></row>
                    <!-- 2152-11-25 00:58:16 CET / 1476811800 --> <row><v>7.064252154e+06</v><v>1.907582096e+07</v></row>
                    <!-- 2152-11-25 01:28:16 CET / 1476813600 --> <row><v>3.792049204e+06</v><v>1.311867946e+07</v></row>
                    <!-- 2016-10-18 20:30:00 CEST / 1476815400 --> <row><v>3.071464893e+06</v><v>1.002659453e+07</v></row>
            </database>
```

Only the last timestamp is correctly decoded into something similar to today's date.

No fix supplied as of yet.

(it looks like the graphing from this data isn't affected by this so far apparently cosmetic issue)

**Comment by he32** [comment]
Debugging reveals that this calculation is problematical:

    422                 now = (rrd.live_head->last_up
    423                        - rrd.live_head->last_up
    424                        % (rrd.rra_def[i].pdp_cnt * rrd.stat_head->pdp_step))
    425                     + (timer * rrd.rra_def[i].pdp_cnt * rrd.stat_head->pdp_step);

In my case, timer is negative, and pdp_cnt and pdp_step are both unsigned long, while timer is long.  This appears to cause overflow of some sort, in GDB i have:

(gdb) p rrd.rra_def[i].pdp_cnt
$14 = 1
(gdb) p rrd.stat_head->pdp_step
$15 = 300
(gdb) p timer
$16 = -863
(gdb) p (timer * rrd.rra_def[i].pdp_cnt * rrd.stat_head->pdp_step)
$17 = 4294708396
(gdb) 

"Oops!"

**Comment by he32** [comment]
And ... in GDB, adding casts to long restores sanity:

(gdb) p (rrd.live_head->last_up - rrd.live_head->last_up % (rrd.rra_def[i].pdp_cnt * rrd.stat_head->pdp_step)) + (timer * (long)rrd.rra_def[i].pdp_cnt * (long)rrd.stat_head->pdp_step)
$19 = 1476565200
(gdb)

**Comment by c72578** [comment]
This issue can be closed

**Comment by oetiker** [comment]
thanks
