### ISSUE TITLE
librrd should not call exit()

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#760]
Hi

Some code checker [1] is complaining that librrd calls exit(). It looks like this comes from rrd_open.c

On line 190/191, we have:
```
#ifdef DEBUG
        rrd_set_error("in read/write request mask");
        exit(-1);
#endif
```

and on line 46:
```
#define DEBUG 1
```

Obviously, a library should return an error when a problem occurs, and never kill the calling process.

[1] https://lintian.debian.org/full/pkg-rrdtool-maint@lists.alioth.debian.org.html

**Comment by bangert** [comment]
@oetiker seems like you mistyped the bug number in the commit...

**Comment by oetiker** [comment]
aargh ... commited the wrong change ...

**Comment by nirgal** [comment]
Hi.

9e44f1d3779cfdd5620de89110108cf6fd65bcb0 was about exit() that were both in `#ifdef DEBUG` and `#if 0`, so these were not an issue. This is nice anyway.

But in rrd_open.c, there is a real problem, with the `#define DEBUG 1` on line 46 and the consequences bellow. See original issue report.

**Comment by oetiker** [comment]
you are right

**Comment by nirgal** [comment]
Thank you for the fix :+1:
