### ISSUE TITLE
Setting timezone in php

### ISSUE THREAD

**Issue by hosseinko** [oetiker/rrdtool-1.x#762]
Hi 
I have a question about timezone issues when working with php extension. I am using RDDCreator, RRDUpdater and RRDGraph classes to manage my rrd dbs.

The problem is I have to change my server timezone to Asia/Tehran if I want time to be shown correctly in x axis. I have searched a lot but it seems that there is no solution to fix this.

I am using these packages on centos 7:
rrdtool-1.4.8-9.el7.x86_64
php-pecl-rrd-2.0.1-1.el7.remi.7.0.x86_64
 and will be more than happy you help me to work out this problem

**Comment by oetiker** [comment]
please use stackexchange to ask rrdtool questions ... as for the timezone, all you should have is set the TZ environment variable prior to launching php ... 

if you want to change the timezone dynamically, you have to call tzset  after setting the TZ environment variable ... I think this is not available directly in php, but it could be provided as part of the rrd bindings ...
