### ISSUE TITLE
Graph with multiple resolutions plotting all lines at same resolution

### ISSUE THREAD

**Issue by allgoewer** [oetiker/rrdtool-1.x#763]
Hello,

I'm basically following the first example at https://oss.oetiker.ch/rrdtool/doc/rrdgraph_examples.en.html to plot a graph with multiple resolutions.

In fact, I used the following script to generate a test database and the plot.

```python
#/usr/bin/env python3

import subprocess
import math

subprocess.call("rrdtool create test.rrd -s 60 -b 01/01/1980 DS:temp:GAUGE:600:-1:1 RRA:AVERAGE:0.5:1:1440".split())

update = subprocess.Popen("rrdtool -".split(), stdin=subprocess.PIPE)

for i in range(315529260, 315529260 + 86400, 60):
	y = math.sin(2 * math.pi / 86400 * i)
	s = "updatev test.rrd -- {}:{}\n".format(i, y)
	print(s, end='')
	update.stdin.write(s.encode("UTF-8"))

update.stdin.close()
update.wait()

subprocess.call("rrdtool graph test.png -s 01/01/1980 -e 01/02/1980 DEF:temp=test.rrd:temp:AVERAGE LINE1:temp#FF0000:temp DEF:temp2h=test.rrd:temp:AVERAGE:step=7200 LINE1:temp2h#00FF00:temp2h".split())
```

When I run this script on my personal machine (Arch Linux, x86_64), I get the following plot:
![test_arch](https://cloud.githubusercontent.com/assets/6408150/21982178/6a76d166-dbeb-11e6-9868-36a8d526ef01.png)

When I run it on a CentOS 6 server (x86_64), I get the following, correct plot
![test_centos](https://cloud.githubusercontent.com/assets/6408150/21982256/ca2bee70-dbeb-11e6-8134-768ad19c42b3.png)

On my Arch machine, i have

```
$ rrdtool
RRDtool 1.6.0  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Jan  9 2017 18:17:41

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
		last, lastupdate, first, info, fetch, tune
		resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages
```

The centos' rrdtool is much older
```
$ rrdtool
RRDtool 1.3.8  Copyright 1997-2009 by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Apr  3 2014 13:07:03

Usage: rrdtool [options] command command_options

Valid commands: create, update, updatev, graph, graphv,  dump, restore,
		last, lastupdate, first, info, fetch, tune,
		resize, xport

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages
```

**Comment by bangert** [comment]
@oetiker maybe step needs to be added to the cacheindex as well?

**Comment by oetiker** [comment]
indeed ... that might be the case

**Comment by allgoewer** [comment]
Do you maybe have an idea for a workaround until this gets fixed?

**Comment by oetiker** [comment]
try this patch ...

**Comment by bangert** [comment]
i tried to verify this, and it does not work.

the number of fmt arguments is wrong, though. if you add another ':%d', it works.

**Comment by oetiker** [comment]
:blush: indeed ... fixed

**Comment by bangert** [comment]
@allgoewer Thanks for the report. The best way to get your hands on this fix, is to compile rrdtool yourself.
