### ISSUE TITLE
SVG output dimensions in points not pixels

### ISSUE THREAD

**Issue by murrant** [oetiker/rrdtool-1.x#769]
When specifying graph size with SVG output, the dimensions are in points instead of pixels.

for example:
```
rrdtool graph /tmp/tmp.svg --only-graph --imgformat=SVG --width 150 --height 45 
```

svg output snippet:
```
width="150pt" height="45pt"
```

The man page for rrdgraph states that --width and --height are in pixels and for PNG at least, this is correct.

**Comment by oetiker** [comment]
yes ... that is just the way `cairo_svg_surface_create` not much we can do about it afaik
there was a patch once proposed https://lists.cairographics.org/archives/cairo/2005-August/004891.html but it seems it did not get in.

**Comment by michaelsalmon** [comment]
You could use points = pixels * 72 / 96 which I found on Wikipedia

The man page should reflect reality.
