### ISSUE TITLE
Missing Dependency to libpcre.so.0

### ISSUE THREAD

**Issue by adanburg** [oetiker/rrdtool-1.x#778]
Hello - this is more of a question. I installed rrdcached as part of the OMD distro on a new RHEL 7.3 machine, however it will not start. Digging into things I found the following:
ldd /opt/omd/sites/test/bin/rrdcached
        linux-vdso.so.1 =>  (0x00007fffbb39c000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f368eb90000)
        librrd_th.so.4 => /omd/versions/1.2.8p20.cre/lib/librrd_th.so.4 (0x00007f368e93c000)
        libpng12.so.0 => /lib64/libpng12.so.0 (0x00007f368e715000)
        libpcre.so.0 => not found

It looks like libpcre comes from pcre version 6.* which I cannot find on the pcre website to download and install. Any ideas on how to resolve this? Thanks.

**Comment by oetiker** [comment]
this is a problem with the omd distro ... I guess you need to install the appropriate  libpcre rpm
