### ISSUE TITLE
Enhancement Request: Hover cursor on line in multi-line graph, get info box with label for line

### ISSUE THREAD

**Issue by WyoMurf** [oetiker/rrdtool-1.x#779]
I am contemplating a personal project for rrdtool graphs, wherein when I am graphing several systems on a single graph, perhaps 40+, and I am having trouble determining exactly which system is responsible for a particular outlying line (because there are several systems with similar colors), I would find it very handy if I could hover my cursor over the single line, and get a little info pop-up with the label for that system's name.
Right at the moment, I have to go back to all the individual graphs, and pick out that particular graph. This isn't fun.

I have an algorithm in mind:

A. Add each line segment of all the systems graphed, to to a kd-tree database, with the associated system name.
B. Follow each system graph line, and for those segments that do not have any other line segment from other systems overlapping it, generate an html region box in a separate file (or where the html is located, that defines where the graph image is to be displayed).

By "overlapping", I might define the imaginary box around each line segment to be expanded by a couple pixels, and I might also include the data if the majority of the line segment is NOT overlapped.
When the user actually clicks on a blank spot, the normal thing happens. If the user clicks on a line segment, I suppose the individual graph corresponding to that particular line segment will be called up. This is pretty much user-definable.
Using k-d tree, or some other geographic data structure, the algorithm should run very quickly. 
And, normally, in multi-system graphs, usually most of the data is highly overlapping, so the number
of regions defined (map.area?) should not be overwhelming. 

Is this already a feature? If so, I didn't spot it in the list of options.

I believe this project would add value to the rrdtool graphs (if not already done), don't you?

To get me off to a quick start, I'd appreciate any suggestions as to where the new html constructs could best be added, etc.

murf

**Comment by oetiker** [comment]
@WyoMurf rrdtool generates png files (or svg or pdf) they are not interactive by nature ... if you want interactivity, have a look at https://github.com/oetiker/RrdGraphJS
