### ISSUE TITLE
graph: line is invisible if all values stay on lower boundary

### ISSUE THREAD

**Issue by deltamaster** [oetiker/rrdtool-1.x#786]
In old version (1.2.x), I am able to see the color line coincide with the x-axis.

Now in newer 1.5.3, I can see nothing. This looks bad because I am not able to tell if a value is missing (NaN) or it just equals to the lower boundary.

**Comment by oetiker** [comment]
well that is a layering problem. the grid does get drawn OVER the lines and can thus obscure them ... what you could do, is use a semi transparent color for the grid #00000088 for example, then you should see any obscured lines ... OR you could make the lines wider.

**Comment by deltamaster** [comment]
Sorry I have problem uploading the graph from corporate network.

**Comment by oetiker** [comment]
the grid is dotted, so there is no problem

try `--color AXIS#00000088` 

another option to try might be `--no-gridfit`

**Comment by deltamaster** [comment]
`--no-gridfit` does exactly what I want. Thank you so much.
