### ISSUE TITLE
RRD Fetch / Xport Step Incorrect

### ISSUE THREAD

**Issue by arrmo** [oetiker/rrdtool-1.x#796]
Hi,

I have an RRD file / archive created with the following definition,
```
' --step 1s --no-overwrite DS:sent:GAUGE:5m:0:U DS:recd:GAUGE:5m:0:U ' \
            'RRA:AVERAGE:0.5:1s:2h ' \
            'RRA:AVERAGE:0.5:1m:2d ' \
            'RRA:AVERAGE:0.5:10m:3M ' \
            'RRA:AVERAGE:0.5:1d:3y'
```

The file works fine, I can update and add data. What's odd is that I find in some cases, the fetch or xport output does not have the desired / prescribed output step. For example, if I select the following data,
1) '-s -60s --json --step 1 ' => the step is correct, and the data looks like the following (reformatted on my end),
```
   0: 17-Jun-2017 06:12:53 =    9944,   19336
   1: 17-Jun-2017 06:12:54 =    8208,    7168
   2: 17-Jun-2017 06:12:55 =   14256,   11088
   3: 17-Jun-2017 06:12:56 =    6000,    6880
   4: 17-Jun-2017 06:12:57 =   40968,   29952
   5: 17-Jun-2017 06:12:58 =    6184,   23008
```

2) But, if i just change 60s to 1m ('-s -1m --json --step 1 ' => exactly the same, right?), then I get a step of 2 hours! and the data looks like,
```
   0: 17-May-2017 07:00:00 =       0,       0
   1: 17-May-2017 09:00:00 =       0,       0
   2: 17-May-2017 11:00:00 =       0,       0
   3: 17-May-2017 13:00:00 =       0,       0
   4: 17-May-2017 15:00:00 =       0,       0
   5: 17-May-2017 17:00:00 =       0,       0
```

Thoughts? Is this a known issue? Or am I doing something stupid?

Thanks!

**Comment by oetiker** [comment]
it does look odd indeed ... for reproducible results, please work with absolute start times bother when creating the archive as well as when fetching ...

if you can provide a sample shell script to demonstrate the behavior that would help.

**Comment by arrmo** [comment]
Hi,

I do find that it seems to work reliably if I use seconds always (i.e. no suffix). The suffix seems to be causing the grief (i.e. delta time is OK, if seconds is used).

Sorry, not sure what you want in a script. The items above are one line commands. Or am I missing your point?

Thanks!

**Comment by oetiker** [comment]
a script like this:

```
#!/bin/sh
rrdtool create ..
rrdtool update ... 
rrdtool xport ...
```
all with absolute time so that the result does not depend on when the thing was run ...

my guess from what you write is that you are using suffixes in an argument that does not support it ... the suffixes were only introduced recently mainly for use in create arguments ...

**Comment by arrmo** [comment]
I found the issue! It's from this little caveat ("TIME OFFSET SPECIFICATION", from rrdfetch),

`Out of context (i.e. right after the + or - sign) the meaning of m is guessed from the number it directly follows. Currently, if the number's absolute value is below 25 it is assumed that m means months, otherwise it is treated as minutes. (e.g., -25m == -25 minutes, while +24m == +24 months)
`

=> the 24/25 isn't quite right ... rather, it seems that the switch point is 6/5. With 6m I get 6 minutes, 5m = 5 months. Just a thought, but use M for months, m for minutes to avoid the confusion / issue?

Thanks!

**Comment by oetiker** [comment]
hihi perfect analysis ... in the source code it even sais

```
            if (delta < 6)  /* it may be some other value but in the context
                             * of RRD who needs less than 6 min deltas? */
```

since this code has been there for a very long time, changeing the interpretation of m will only produce misery ... I am going to update the documentation.

**Comment by arrmo** [comment]
Works for me - thanks!
