### ISSUE TITLE
possible improvements in rrd locking

### ISSUE THREAD

**Issue by sourcejedi** [oetiker/rrdtool-1.x#799]
> I guess since writes and reads may not be atomic in any event a
sensible locking for fetch might make sense in any way ...
>
> your patches are welcome ...
>
> cheers
> tobi 

Here is my implementation plan.

I believe it is possible to take a read lock in `rrd_open()`.  Or write lock, depending.  `rrd_lock()` would be deprecated.  For backwards compatibility, the locking could be conditional on a new option to `rrd_open()`.  This would avoid potentially triggering deadlocks in unusual uses of librrd.  At the same time, it would be straightforward to audit a codebase for uses of `rrd_open()` which did not lock.

I've looked at rrdcached, rados, and win32.

I found one issue, with win32.  win32 currently uses non-blocking locks.  The `_locking` function used supports a "blocking" lock where "If the bytes cannot be locked, the program immediately tries again after 1 second. If, after 10 attempts, the bytes cannot be locked, the constant returns an error."  This sounds likely to cause problems.  So I suggest using the `select()` trick for sub-second sleeps in our own loop, e.g. 100 times per second, especially as we already have some winsocket usage.  We can use the same max delay as rados (2 seconds).

This is not an ideal architecture.  On my SheevaPlug (old 1.6ghz ARM), cacti takes ~0.7s to render one graph.  On a page with five graphs, Firefox shows that it fetches the graphs in parallel and they take just under 5 seconds.

So it is probably best for the grapher to opt out of locking, unless someone decides to implement a [seqlock](https://en.wikipedia.org/wiki/Seqlock).  (This might temporarily grab a read lock while checking the mtime, before and after rendering the graph).  Having the grapher opt out will help minimize regressions.

This will still allow `rrdtool dump` to be used for backups without fear of inconsistency.  And implementing this will highlight the locking issue, when developers look at librrd.

Other already-existing issues:

* Readers can block writers indefinitely. E.g. on unix, any user that can read the file can take a standard `fcntl()` advisory read lock.  This would be a Denial of Service on the rrdtool writer.  This is a valid tradeoff, except that it's not documented in RRD.  This should be documented e.g. for applications like smokeping and packages thereof - the current Debian smokeping package leaves these files world-readable. ftp://ftp.sendmail.org/pub/sendmail/LockingAdvisory.txt
* The widely-available `fcntl()` locks are also defined to unlock when the process closes *any* fd which points to the same file.  I don't think this causes no problem inside rrdtool, but it would be good to note in the API comment for the benefit of librrd.

**Comment by oetiker** [comment]
hmm, changing the behavior of existing functions like rrd_open and rrd_lock are drastic measures which will affect many people ... so the benefits would have to be equally large ...

maybe it would be best to first figure out what exactly the error states are that may occur in the present design and then look at ways to combat the problems specifically.

**Comment by sourcejedi** [comment]
> For backwards compatibility, the locking could be conditional on a new option to rrd_open().  This would avoid potentially triggering deadlocks in unusual uses of librrd.

I.e. RRD_LOCK.  Not RRD_NOLOCK.

**Comment by oetiker** [comment]
changing the call arguments for an existing functions if not a good thing ...

**Comment by sourcejedi** [comment]
it is?

https://github.com/oetiker/rrdtool-1.x/blame/bfc82d5242855628b826018479df00e0ec4e8360/src/rrd_tool.h#L135

**Comment by oetiker** [comment]
oh adding additional bits that is fine ... the problem is when you modify the number of arguments ...

**Comment by sourcejedi** [comment]
Looks like there's plenty of bits left there, we can probably afford to use another one :).  Any further reviews welcome.

**Comment by oetiker** [comment]
hihi lets see some code!
