### ISSUE TITLE
xport - Correct timestamp for data?

### ISSUE THREAD

**Issue by arrmo** [oetiker/rrdtool-1.x#805]
Hi,

No issues here with the timestamp not being in xport any more, but ... need to know how it's aligned. For example, I'm xport'ing data over a period of 36000 seconds, with an interval of 3600 => 10 data points. So is it correct to assume that the timestamp is the "middle" of the period? What I mean is below ...

```
"start":1498780800,
"end":1498816800,
"step":3600,
```

So then the data, is the timestamp for the first data point = start, or start + 0.5*step? I assume it's +0.5*step, or I need one more output data point, but to make sure.

Thanks!

**Comment by arrmo** [comment]
BTW, forgot to mention, this is somewhat related to #672.

Thanks!

**Comment by oetiker** [comment]
no the timestamp always marks the END of the periode

**Comment by arrmo** [comment]
OK, that makes sense - and it's the average over that period, right? So the first point will be at start + step, correct?

Thanks!

**Comment by oetiker** [comment]
this depends on the consolidation function you chose

Tobias Oetiker
tobi@oetiker.ch
062 775 9902

**Comment by arrmo** [comment]
NP, that's fine. Is this captured somewhere in the documentation? More than happy to go through that, I just haven't been able to find it.

Thanks!!!

**Comment by oetiker** [comment]
I would think so ... but I cant point you to the right place ...
