### ISSUE TITLE
xport Error, Compiled Without Graphics

### ISSUE THREAD

**Issue by arrmo** [oetiker/rrdtool-1.x#806]
Hi,

Trying to run rrdtool to get some data out (xport), but I get the error message,
`ERROR: the instance of rrdtool has been compiled without graphics
`

Hmmm ... I'm not looking for graphics, rather only xport (data output, for post processing). Why is graphics support needed for xport output?

Thanks!

**Comment by oetiker** [comment]
because rrd_xport.c is just a thin wrapper around rrd_graph.c ... BUT it would certainly be doable to untangle them ...

**Comment by arrmo** [comment]
OK, thanks. I'll try to dig into it.
