### ISSUE TITLE
Build Fails, Static Program

### ISSUE THREAD

**Issue by arrmo** [oetiker/rrdtool-1.x#807]
Hi,

This may be me, but pulling my hair out ... :(. If I pull the latest code from here (Github), and configure and build ... all is fine. But, if I --enable-static-programs (need to do this, to run on another machine that doesn't have the libraries), I get the error,
`/usr/bin/ld: cannot find -lpangocairo-1.0
`

But ... the checks (in configure) seem to say that this is fine, and also,
```
$ ls -alF /usr/local/lib/libpangocairo*
lrwxr-xr-x  1 root  wheel     29 Jul 10 17:14 /usr/local/lib/libpangocairo-1.0.so@ -> libpangocairo-1.0.so.0.3800.0
lrwxr-xr-x  1 root  wheel     29 Jul 10 17:14 /usr/local/lib/libpangocairo-1.0.so.0@ -> libpangocairo-1.0.so.0.3800.0
-rwxr-xr-x  1 root  wheel  53616 Jul 10 17:14 /usr/local/lib/libpangocairo-1.0.so.0.3800.0*
```

So the needed library is there. Thoughts?

Thanks!

**Comment by oetiker** [comment]
to build static, you need a *.a version of the library

**Comment by arrmo** [comment]
My mistake, thanks for clarifying!!!
