### ISSUE TITLE
The direction of rendering area with gradient color

### ISSUE THREAD

**Issue by sylin113** [oetiker/rrdtool-1.x#811]
Hi Sir,

Not sure what went wrong but the same Perl script with rrdtool 1.7.0 produces the three different gradient styles as follows. I had upgraded most of the backend engines such as cairo-1.14.10, but still got the same result.

For the process count, the Perl script generates the following code for area rendering.

`AREA:vpm#927A10#422A00:process\:\g:gradheight=0`

Thanks.

Lawrence
-------

(draw gradient vertically)
![image](https://user-images.githubusercontent.com/30255095/28305241-7f659856-6bcd-11e7-8679-a0b9209be2d9.png)

(draw gradient horizontally that is not my intention)
![image](https://user-images.githubusercontent.com/30255095/28304988-947a3d7e-6bcc-11e7-803f-186793d829de.png)
![image](https://user-images.githubusercontent.com/30255095/28305074-e3564b0e-6bcc-11e7-9935-e695caa8aa50.png)

(or even mixed that is not my intention either)
![image](https://user-images.githubusercontent.com/30255095/28305015-abb06b44-6bcc-11e7-8f2f-c885a9644db1.png)

**Comment by oetiker** [comment]
> The gradheight parameter can create three different behaviors. If gradheight > 0, then the gradient is a fixed height, starting at the line going down. If gradheight < 0, then the gradient starts at a fixed height above the x-axis, going down to the x-axis. If height == 0, then the gradient goes from the line to x-axis.

**Comment by oetiker** [comment]
```c
void gfx_add_rect_fadey(
    image_desc_t *im,
    double x1,double y1,
	double x2,double y2,
	double py,
    gfx_color_t color1,
	gfx_color_t color2,
	double height)
{
    cairo_t  *cr = im->cr;
    
	cairo_new_path(cr);
    gfx_area_fit(im, &x1, &y1);
    gfx_area_fit(im, &x2, &y2);
    cairo_line_to(cr, x1, y1);
    cairo_line_to(cr, x1, y2);
	cairo_line_to(cr, x2, y2);
	cairo_line_to(cr, x2, y1);
	cairo_close_path(cr);
	cairo_pattern_t* p;
	if (height < 0) {
		p = cairo_pattern_create_linear(x1,y1,x2,y1+height);
	} else if (height > 0) {
		p = cairo_pattern_create_linear(x1,(y2+py)/2+height,x2,(y2+py)/2);
	} else {
		p = cairo_pattern_create_linear(x1,y1,x2,(y2+py)/2);
	}
	//cairo_pattern_t* p = cairo_pattern_create_linear(x1,py+50,x2,py);
	cairo_pattern_add_color_stop_rgba(p, 1, color1.red,color1.green,color1.blue,color1.alpha);
	cairo_pattern_add_color_stop_rgba(p, 0, color2.red,color2.green,color2.blue,color2.alpha);
    cairo_set_source(cr, p);
	cairo_pattern_destroy(p);
	cairo_fill(cr);
}
```

**Comment by sylin113** [comment]
Hi Tobias,

I constantly assign 0 to gradheight in my Perl script. So the issue to me is that, is there any way to control the color1-to-color2 direction (i.e. vertically or horizontally) of gradient color between the line and x-axis? Supposedly it should go vertically without exception such as horizontally or even mixed, am I right?

I have traced the code as you had shown, but found nothing I could use.

Thank you.

Lawrence

**Comment by oetiker** [comment]
lawrence, I would also have to dig into cairo docs ... that code in rrdtool has not changed in quite some time afaik

**Comment by sylin113** [comment]
Hi Tobias, no problem. I will trace the codes further as well to see what I could do in this case.  Thank you.

**Comment by sylin113** [comment]
Hi Tobias,

The root cause is that the angle of the color1-to-color2 direction slants to the left while the square (line 3960 in rrd_graph.c, v1.7.0) with the same data value become wider.

Since I still cannot find how to maintain the angle of gradient pattern for cairo_pattern_create_linear, a temp solution for me is to add in some scrambling values (three lines starting from line 4179) to prevent drawing in square mode as follows.

`if ((ii > 0) && (ytop == ytr(im, im->gdes[i].p_data[ii - 1]))) {`
    `ytop += 0.0001 * ii;`
`}`

The other issue is that two space lines, instead of one, will remain at the head of data pattern if gradient is activated as in the graph.

![image](https://user-images.githubusercontent.com/30255095/28862054-361ac9da-7796-11e7-807e-05e0f9c7146f.png)

Hopefully the data is enough for debugging on this issue.

Thank you.

Lawrence

**Comment by sylin113** [comment]
The alternative solution above is incomplete. The following is better (the if clause around line 4188).

`

                        if (ybase > ytop) {
                            double    extra = ytop;
                            ytop = ybase;
                            ybase = extra - (0.0001 * ii);
                        } else {
                            ytop += 0.0001 * ii;
                        }

`

**Comment by oetiker** [comment]
hi sylin113, interesting stuff you are finding ... sorry for not being more involved atm ... but $work$ is taking precedence.

**Comment by sylin113** [comment]
Hi Oetiker,

Surely it's OK. Thank you for creating such a beautiful tool which makes my life easier. Here is the summary of the temp solutions to my case before closing the thread.

Issue two (an empty column at the head of a data segment) can be fixed by replace line 4131with the following code  in rrd_graph.c (the original value is 1).

`while (idxI > 0) {`

(plain color: everything is OK as usual)
![image](https://user-images.githubusercontent.com/30255095/29054790-e8b1e91e-7c2a-11e7-9d19-a8141c1cd374.png)

(original gradient: A is caused by issue one, B and C are caused by issue two) 
![image](https://user-images.githubusercontent.com/30255095/29054795-ef7b201c-7c2a-11e7-82b4-d8d9dee8e168.png)

(fixed gradient: a beautiful graph!)
![image](https://user-images.githubusercontent.com/30255095/29055191-b1125d4c-7c2d-11e7-9c43-b01ddad6de2b.png)

**Comment by oetiker** [comment]
hi @sylin113 
how about creating a PR with your changes ?

cheers
tobi

**Comment by sylin113** [comment]
Hi Tobi,

I just tried to create a PR, but found that there is no 1.7 available for code comparison. Please advise how to proceed.

Thanks.

Lawrence

**Comment by oetiker** [comment]
I have not branched 1.7 yet ... 1.7 = master

**Comment by Thomas-Gelf** [comment]
While wondering whether no one else faced issues with gradients, I stumbled over this issue. I applied the following patch, please see my test results below:

```patch
--- a/src/rrd_graph.c
+++ b/src/rrd_graph.c
@@ -4292,7 +4292,9 @@ int graph_paint_timestring(
                             double    extra = ytop;
 
                             ytop = ybase;
-                            ybase = extra;
+                            ybase = extra - (0.0001 * ii);
+                        } else {
+                            ytop += 0.0001 * ii;
                         }
                         if (im->slopemode == 0) {
                             backY[++idxI] = ybase - 0.2;
```
@oetiker: I can provide a PR with credits to @sylin113, if @sylin113 prefers to do so: even better. I'd really love to see this being merged, as it changes the first impression of gradients in rrdtool from "doesn't look so good" to "nice, just those shadows look strange". IMHO there are still other issues, pango

### gradheight=0, current master

![grafik](https://user-images.githubusercontent.com/553008/235349038-1653dceb-9c21-42c2-8247-cd28e0694ea2.png)

### gradheight=0, current master with patch

![grafik](https://user-images.githubusercontent.com/553008/235349014-671f64a6-80d5-44f7-8965-f382de95ec56.png)

### gradheight=30, current master

![grafik](https://user-images.githubusercontent.com/553008/235348839-a6f0755a-39eb-471f-aee3-0972131d20f4.png)

### gradheight=30, current master with patch

![grafik](https://user-images.githubusercontent.com/553008/235348886-b7e16e7a-01fa-459e-9a7f-35e24965e32c.png)

### gradheight=-30, current master

![grafik](https://user-images.githubusercontent.com/553008/235349074-3b39144b-3b26-49a0-b27a-4461558a2604.png)

### gradheight=30, current master with patch

![grafik](https://user-images.githubusercontent.com/553008/235349088-948f17dd-22ba-4ff7-aa95-2a948d33b6b6.png)

BTW, those "shadows" appear in SVGs only, this is what a PNG looks like, with and without patch:

![grafik](https://user-images.githubusercontent.com/553008/235349183-23c5929f-3fb4-4f8d-97d4-33f007157f7d.png)

![grafik](https://user-images.githubusercontent.com/553008/235349192-c4b66910-3132-45b1-bba9-e7b027eec0f0.png)

**Comment by Thomas-Gelf** [comment]
### Rendering times and file sizes

Not directly related to this issue, but might be interesting:

| Format            | Rendering Time |     File size | Compressed (gzip) |
|-------------------|---------------:|--------------:|------------------:|
| SVG with gradient |        10.87ms |  *422.30 KiB* |         33.10 KiB |
| SVG w/o gradient  |     **2.73ms** |     91.49 KiB |     **10.70 KiB** |
| PNG with gradient |      *43.59ms* |     94.23 KiB |       *91.63 KiB* |
| PNG w/o gradient  |        18.68ms | **24.28 KiB** |         20.39 KiB |

Image size was 1237x420. As you can see, gradients come with a cost. SVG greatly outperforms PNG when it comes to rendering performance, but generated images are way larger (factor 4-5 in this example). However, this can easily be addressed with HTTP compression. Above values have been achieved with gzip level 6, compression in the related web application took slightly more than 1ms.

So for me, SVG is a clear winner - and it usually looks better than PNG. Just, when it comes to gradients, with rrdtool PNG still has an advantage.
