### ISSUE TITLE
Unknown behavior of "rrdtune --step"

### ISSUE THREAD

**Issue by deltamaster** [oetiker/rrdtool-1.x#812]
The documentation about it is still in "TODO" state so I am not clear about the expected behavior.

For example, is it possible to tune the step from 300 seconds down to 60 seconds with this command?

**Comment by oetiker** [comment]
no, rrdtool tune will not let you change step ... since rrdtool 1.5 you can use rrdtool create to import data from existing rrds into new ones while changeing the storage parameters

**Comment by wolfgangr** [comment]
feature request:
just drop a message to the command line if newbie tries it anyway.
It took me three hours now to find this out ;-\
