### ISSUE TITLE
Inconsistent behavior of --enable-FEATURE / --disable-FEATURE in configure

### ISSUE THREAD

**Issue by yarda** [oetiker/rrdtool-1.x#861]
For example:
1. $ ./configure --disable-libdbi # doesn't build libdbi support
2. $./configure  # builds libdbi support if available
3. $ ./configure --enable-libdbi # doesn't build libdbi support

For 3. it's quite confusing that --enable behaves the same way as --disable.

I think you should code AC_ARG_ENABLE according to the example [1], i.e. use enable_libdbi=yes as the last argument of AC_ARG_ENABLE and then check the condition with AS_IF.

[1] https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/External-Software.html#External-Software

**Comment by yarda** [comment]
I tried to address it by #862.

**Comment by oetiker** [comment]
#862 is merged
