### ISSUE TITLE
Translations don't work

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#872]
Hi

I tried to see the translations at work in version 1.7, setting my locale to hu_HU.UTF-8.

But I only get English.

running ``LANG=hu_HU.UTF-8 strace rrdtool`` I can see:

```
open("/usr/share/locale/hu_HU.UTF-8/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/hu_HU.utf8/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/hu_HU/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/hu.UTF-8/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/hu.utf8/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/hu/LC_MESSAGES/messages.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
```

while the file is at ``/usr/share/locale/hu/LC_MESSAGES/rrdtool.mo``.

**Comment by oetiker** [comment]
hmmm I have to admit this is contributed code ... I never work with anything but english locales :) but a PR to fix would be highly appreciated.

**Comment by nirgal** [comment]
This quick and dirty patch fixes it for me:
```
Index: rrdtool/src/rrd_tool.c
===================================================================
--- rrdtool.orig/src/rrd_tool.c 
+++ rrdtool/src/rrd_tool.c 
@@ -454,11 +454,10 @@ int main( 
     setmode(fileno(stdin), O_BINARY); 
 #endif 
  
- 
-#if defined(HAVE_LIBINTL_H) && defined(BUILD_LIBINTL) 
-    bindtextdomain(GETTEXT_PACKAGE, LOCALEDIR); 
-    textdomain(GETTEXT_PACKAGE); 
-#endif 
+/*#if defined(HAVE_LIBINTL_H) && defined(BUILD_LIBINTL)*/ 
+    bindtextdomain("rrdtool", LOCALEDIR); 
+    textdomain("rrdtool"); 
+/*#endif*/ 
     if (argc == 1) { 
         PrintUsage(""); 
         return 0;
```

**Comment by oetiker** [comment]
so do HAVE_LIBINTL_H and BUILD_LIBINTL and GETTEXT_PACKAGE not get set properly when you configure rrdtool ?

**Comment by nirgal** [comment]
One of these sure isn't defined here.

According to https://ftp.gnu.org/old-gnu/Manuals/gettext-0.11.2/html_chapter/gettext_13.html#SEC196 the correct macro is:
#if ENABLE_NLS

This works for me.

Also GETTEXT_PACKAGE preprocessor macro is undefined at the moment. You may already have a proper macro for "rrdtool". I don't know which to use. Maybe we should dig at the install script and from there, find out how the final location is defined...

**Comment by oetiker** [comment]
yes just PACKAGE

**Comment by oetiker** [comment]
so I guess that whole i18n thing has not been working for some time :)

**Comment by nirgal** [comment]
po/Makevars says:
DOMAIN = $(PACKAGE)

Changing this changes the name of the .po files in the install target. So the correct macro for calls to bindtextdomain and textdomain is something like PACKAGE...
