### ISSUE TITLE
rrdruby mentions --interlace option, should be --interlaced

### ISSUE THREAD

**Issue by tpo** [oetiker/rrdtool-1.x#885]
Hello,

the rrdruby documentation here: https://oss.oetiker.ch/rrdtool/prog/rrdruby.en.html is showing an example that is using the option `--interlace`.

When I use that option I get:

    /home/me/bin/lib/rrd-grapher.rb:87:in `graph': invalid option -- 'interlace' (RRDError)

If instead I use `--interlaced` (notice the tailing `d` character) then the code works. It seems like the spelling of that option has changed at some point in the past (it was working under Debian jessie (aka rrdruby V1.4.8 and does not work under Debian stretch aka rrdruby V1.6.0).

Maybe there are other instances of using `--interlace` in other spots in the rrd code/docu that need to be updated.

Thanks a lot for RRD & greetings,
*t

**Comment by c72578** [comment]
Thanks for your report.
This is a typo in doc/rrdruby.pod and will be fixed soon.
Correct is: `--interlaced`
