### ISSUE TITLE
rrdtool update reports "ERROR: 'XXX.rrd' is too small (should be NNN bytes)" on Windows

### ISSUE THREAD

**Issue by weyou** [oetiker/rrdtool-1.x#889]
Hello,

Platform: Windows  
Version:   Build from the lastest source code from master branch

Use the following parameters to create a rrd file. Note that the row length in RRA is 10.
`rrdtool create all.rrd --start 978300900 DS:a:COUNTER:600:U:U DS:b:GAUGE:600:U:U DS:c:DERIVE:600:U:U DS:d:ABSOLUTE:600:U:U RRA:AVERAGE:0.5:1:10`

Now update the file with data:
         `rrdtool update all.rrd 978301200:300:1:600:300`

You will get the error:
        `ERROR: 'all.rrd' is too small (should be 83828 bytes)`

I traced the code.  When rrdtool writes the header, there is a extra byte `0x0d` prepended to the `rra_def->row_cnt`,  which should be 10(\x0a\x00\x00\x00) but now it's 2573(\x0d\x0a\x00\x00). It caused the wrong calculation of `file_len`.  Apparently, the file was opened in text mode instead of binary mode by mistake.  Checking the function mkstemp(), the file is opened without the flag O_BINARY.  We known that the default file open mode is TEXT mode under Windows platform. 

I will send a pull request later. 

Thanks

**Comment by oetiker** [comment]
cool! thanks

**Comment by weyou** [comment]
Closed for the patch has been merged. Thanks oetiker.
