### ISSUE TITLE
Bundled libtool is specific to Linux

### ISSUE THREAD

**Issue by ryandesign** [oetiker/rrdtool-1.x#898]
Hello, configuring rrdtool 1.7.0 on macOS results in these messages being printed:

```
./libtool: line 909: /bin/sed: No such file or directory
./libtool: line 915: /bin/sed: No such file or directory
./libtool: line 2640: /bin/sed: No such file or directory
```

Configuration continues, but these messages are unsettling and make me concerned that some aspect of the configuration has not been performed as intended.

The reason for the errors appears to be that the configure script calls the bundled libtool script (``eval `./libtool --config | grep pic_flag=`​``), but the bundled libtool script has been generated for Linux (`# Libtool was configured on host froburg:`; `host=x86_64-pc-linux-gnu`) and contains some assumptions that are not correct on macOS (such as `SED="/bin/sed"`).

The configure script regenerates libtool with a version appropriate for macOS—but not until the very end of the configuration process, when it calls config.status, which is after the point in the configure script where it calls libtool.

I'm not an autotools expert so I don't know how problems such as this are supposed to be resolved.

**Comment by oetiker** [comment]
so when you run configure twice, it works fine ?

**Comment by ryandesign** [comment]
Yes, if I run `./configure` a second time, the `/bin/sed` warnings don't appear. And if I disable silent rules, I can see that if I run `make` after running `./configure` a second time, the compiler flags `-fno-common -DPIC` are used, whereas if I only run `./configure` once, they aren't.

**Comment by oetiker** [comment]
hmmm I have removed the call for now ... b3f6be4

**Comment by ryandesign** [comment]
Thanks. Looks like you should regenerate configure after this change.
