### ISSUE TITLE
performance debug?

### ISSUE THREAD

**Issue by mdidomenico4** [oetiker/rrdtool-1.x#904]
is there any way to debug the performance when using rrdtool from perl and using a fetch_callback.  my program runs fine, but when i call RRDs::graphv it takes 5 seconds or so to return the graph.  the database calls return very quickly (less then 1 seconds) and the quantity of data isn't much (5 points of data every 5min over the last 24).   it seems like rrd::graph should return a lot faster then it does

**Comment by oetiker** [comment]
for performance I tend to use http://kcachegrind.sourceforge.net/html/Home.html

**Comment by mdidomenico4** [comment]
i've poked at this for a couple of days and figured out that it's the fonts (i have many installed).  when i strace the cgi program that calls RRDs::graphv, it seems to cycle through opening all the font files on my system.  i've run fc-cache -rv and have specific font names specified in the --font options that i'm passing to RRDs.  Running fc-match "DejaVu Sans Mono"  seems to return the font file without issue.  Any idea why RRD or Pango would be sifting through all my fonts instead of just using the ones i asked for?

**Comment by oetiker** [comment]
aah, this is a CGI ... yea, that will never be fast ... make sure you use fastcgi or some other means to make your script persistant ... that font indexing only happens on the first call to librrd

**Comment by oetiker** [comment]
oh my ... yes without font cache its much worse, but even now you are spending quite some time reading the cache which you would not if you were using FastCGI or some other means of keeping your server running between requests.
