### ISSUE TITLE
when we do rrd_fetch in perl the step will start with a space, so error out

### ISSUE THREAD

**Issue by sinkingsun2** [oetiker/rrdtool-1.x#906]
we used perl to fetch data in RRD, but we failed.
I checked the source code and found a workaround.
my ($start,$return_step,$names,$data) = RRDs::fetch (
      $filename,
      'AVERAGE',
      "-s $start",
      "-e $end",
      "-r$step"
);
this will be fine. 
did you notice that I deliberately removed the space between -r and $step?
the problem is in rrd_utils.c line 242 .

**Comment by oetiker** [comment]
the 'problem' is that "-s $start" ist wrong .. correct would be '-s',$start ... note on the shell the space character is used for separating arguments ...
