### ISSUE TITLE
GPRINT with %S is rejected with --imgformat JSON and XML

### ISSUE THREAD

**Issue by az143** [oetiker/rrdtool-1.x#908]
rrdtool 1.7.0 (compiled locally from git, HEAD at ecf80e6 so should be uptodate)
rejects any graph or graphv operations if you ask for json and have GPRINTs that use %S:
the input sanitising function spits out something like 
'ERROR: bad format for PRINT in "Current %lf %S bits/sec" and aborts.

running  the same graph/graphv operation works fine when the output is an image (or incapable of prints, e.g. CSV).

easy to reproduce:
```
rrdcreate testme.rrd -s 300 DS:one:GAUGE:300:U:U DS:two:COUNTER:300:U:U RRA:AVERAGE:0.5:1:1000
rrdupdate testme.rrd -t one:two N:34:56 
rrdupdate testme.rrd -t one:two N:68:89

# this fails: ERROR: bad format for PRINT in "Current %lf %S bits/sec'
rrdtool graph - --imgformat JSON DEF:one=testme.rrd:one:AVERAGE 'GPRINT:one:LAST:Current %lf %S bits/sec' LINE:one#ff00ff:one

# works: 
rrdtool graph ./pic.png --imgformat PNG DEF:one=testme.rrd:one:AVERAGE 'GPRINT:one:LAST:Current %lf %S bits/sec' LINE:one#ff00ff:one
```

changing the GPRINT to use %s 'works' in the sense of not being rejected, but doesn't produce any magnitude output either, as far as i could  determine. that's minor compared to the abort on %S though.

**Comment by az143** [comment]
i've created a patch that adds the %s/%S scaling functionality as implemented in rrd_graph.c to the relevant function in rrd_xport.c; i hope you'll consider that patch or something like it for the next release.

regards,
az

[unit-autoscaling-patch.txt](https://github.com/oetiker/rrdtool-1.x/files/2449173/unit-autoscaling-patch.txt)

**Comment by oetiker** [comment]
can you please turn this into a pull request ?

**Comment by vbastos** [comment]
This should be closed.

**Comment by oetiker** [comment]
the PR is still open
