### ISSUE TITLE
perl bindings report version that doesn't correspond to rrdtool version

### ISSUE THREAD

**Issue by az143** [oetiker/rrdtool-1.x#909]
as of HEAD at ecf80e and actual overall VERSION showing 1.7.0, 
 $RRDs::VERSION reports itself as 1.5.1 and  $RRDp::VERSION 1.4.3.
this makes it impossible to determine what rrdtool version you actually do have, at least from within perl.

is that lack of synchronisation just a simple oversight or a design decision, i.e. are the bindings _meant_ to report their internal version only?

**Comment by vbastos** [comment]
Is there a reason this why this was not accepted? Are the bindings supposed to have their own version?

**Comment by oetiker** [comment]
this is fixed in 1.7.1

**Comment by vbastos** [comment]
Why is it still 1.5 in the master branch? Is master not latest stable?

**Comment by c72578** [comment]
The version is updated by `make dist`, which creates the release tarball.
See Makefile.am:
<pre>
dist-hook: VERSION
$(AM_V_GEN)cd $(distdir) && $(PERL) -i -p -e 's/^\$$VERSION.+/\$$VERSION='$(NUMVERS)';/' bindings/perl-*/*.pm
</pre>
