### ISSUE TITLE
rrdtool graph exits with error when using --use-nan-for-all-missing-data

### ISSUE THREAD

**Issue by cjmayo** [oetiker/rrdtool-1.x#918]
To repeat, create an rrd using the example from the tutorial and then try and graph a DS that does not exist:
```
$ rrdtool create test.rrd              \
            --start 920804400          \
            DS:speed:COUNTER:600:U:U   \
            RRA:AVERAGE:0.5:1:24       \
            RRA:AVERAGE:0.5:6:10
$  rrdtool graph graph.png -Z -a PNG -h 100 -w 100 DEF:speed=test.rrd:aspeed:AVERAGE LINE1:speed#ff0000
ERROR: No DS called 'aspeed' in 'test.rrd'
```
I first encountered this using rrdcgi with more complex files were some requested DS's did exist and others didn't.

Maybe I've misunderstood but this error seems to contradict the option description:
> [ -Z|--use-nan-for-all-missing-data]
If one DS is missing, either because the RRD is not available or because it does not contain the requested DS name, just assume that we got empty values instead of raising a fatal error. 

Using rrdtool 1.7.0 from Gentoo Linux.

**Comment by c72578** [comment]
Thanks for your report and the minimal example to reproduce it.
The problem is coming from `rrd_graph.c:1059`
This was already implemented in the past [1] but must have been lost somehow ...
I will prepare a PR for the following:
```diff
diff --git a/src/rrd_graph.c b/src/rrd_graph.c
index bde30724..65cc723f 100644
--- a/src/rrd_graph.c
+++ b/src/rrd_graph.c
@@ -1056,7 +1056,7 @@ int data_fetch(
                 im->gdes[i].ds = ii;
             }
         }
-        if (im->gdes[i].ds == -1) {
+        if ((im->gdes[i].ds == -1) && !(im->extra_flags & ALLOW_MISSING_DS)) {
             rrd_set_error("No DS called '%s' in '%s'",
                           im->gdes[i].ds_nam, im->gdes[i].rrd);
             return -1;
```
[1] https://github.com/oetiker/rrdtool-1.x/commit/5687a92b75eaf0cc9fd6b41fe3b1d3dbcedf8c68
