### ISSUE TITLE
"Line0" is not processed any more

### ISSUE THREAD

**Issue by nirgal** [oetiker/rrdtool-1.x#930]
Hi

The original bug report is at https://bugs.debian.org/891491

Commit 1ace836524e58f4db3c30e7dea0e11207ac451f5 changed the LINE width sanity test:
```
                if (gdp->linewidth < 0) {
                    rrd_set_error
                        ("LINE width '%s' is less than 0 in line '%s'\n",
                         &line[*eaten], line);
                    return 1;
                }
```
into
```
      if ((getDouble(t,&linewidth,&x))||(linewidth<=0)) {
	rrd_set_error("Bad line width: %s",t); return NULL;
      }
```
so that LINE0 doesn't work anymore in 1.7.

I'm not quite sure how to handle that bug report. I suppose I should answer that LINE0 is no longer supported, and that's it?  Or would you consider re-adding 0-width support for compatibility?
In the former case, adding a note in the CHANGES would be nice.
In the later case, changing `linewidth<=0` into `linewidth<0` would probably do the trick.

**Comment by oetiker** [comment]
oh yes sure ... allow for 0 that is fine I guess that is an unintended side effect of the change
