### ISSUE TITLE
base_value

### ISSUE THREAD

**Issue by babyfenei** [oetiker/rrdtool-1.x#935]
Dear developer, thank you for developing rrdtool. The work I am doing now relies heavily on rrdtool and cacti. But in my work. The value of base_value in the rrdtool graph command needs to be 1126 or other non-1000 and non-1024 values of the author. However, the rrdtool graph command limits the value of base_value to only 1000 or 1024. Is there any way to solve it? Grateful

**Comment by oetiker** [comment]
you can remove the check ... it is simply there to prevent users from doing odd things ... if you know what you are doing ... feel free ... that, after all is part of the beauty of open source.

**Comment by babyfenei** [comment]
This problem has been solved, thank you for your reply.
