### ISSUE TITLE
`etc/rrdcached.socket', needed by `all-am'.  Stop.

### ISSUE THREAD

**Issue by whsir** [oetiker/rrdtool-1.x#967]
version 1.7.1 issue

make error

Making all in po
make[1]: Entering directory `/usr/local/src/rrdtool-1.7.1/po'
make[1]: Leaving directory `/usr/local/src/rrdtool-1.7.1/po'
Making all in src
make[1]: Entering directory `/usr/local/src/rrdtool-1.7.1/src'
make  all-am
make[2]: Entering directory `/usr/local/src/rrdtool-1.7.1/src'
  CC       librrd_la-rrd_version.lo
  CC       librrd_la-rrd_last.lo
  CC       librrd_la-rrd_lastupdate.lo
  CC       librrd_la-rrd_first.lo
  CC       librrd_la-rrd_dump.lo
  CC       librrd_la-rrd_flushcached.lo
  CC       librrd_la-rrd_fetch.lo
  CC       librrd_la-rrd_fetch_cb.lo
  CC       librrd_la-rrd_resize.lo
  CC       librrd_la-rrd_tune.lo
  CC       librrd_la-rrd_list.lo
  CC       librrd_la-rrd_graph.lo
  CC       librrd_la-rrd_graph_helper.lo
  CC       librrd_la-rrd_xport.lo
  CC       librrd_la-rrd_gfx.lo
  CC       librrd_la-pngsize.lo
  CC       librrd_la-rrd_restore.lo
  CC       librrdupd_la-mutex.lo
  CC       librrdupd_la-optparse.lo
  CC       librrdupd_la-rrd_strtod.lo
  CC       librrdupd_la-rrd_create.lo
  CC       librrdupd_la-hash_32.lo
  CC       librrdupd_la-rrd_parsetime.lo
  CC       librrdupd_la-rrd_hw.lo
  CC       librrdupd_la-rrd_hw_math.lo
  CC       librrdupd_la-rrd_hw_update.lo
  CC       librrdupd_la-rrd_diff.lo
  CC       librrdupd_la-rrd_format.lo
  CC       librrdupd_la-rrd_info.lo
  CC       librrdupd_la-rrd_error.lo
  CC       librrdupd_la-rrd_open.lo
  CC       librrdupd_la-rrd_client.lo
  CC       librrdupd_la-rrd_nan_inf.lo
  CC       librrdupd_la-rrd_rpncalc.lo
  CC       librrdupd_la-rrd_utils.lo
  CC       librrdupd_la-rrd_snprintf.lo
  CC       librrdupd_la-rrd_update.lo
  CC       librrdupd_la-rrd_modify.lo
  CC       librrdupd_la-quicksort.lo
  CC       librrdupd_la-rrd_thread_safe.lo
  CC       rrd_tool.o
  CC       rrdupdate.o
  CC       rrd_cgi.o
  CC       rrdcached-rrd_daemon.o
  CCLD     librrdupd.la
  CCLD     librrd.la
  CCLD     rrdupdate
  CCLD     rrdtool
  CCLD     rrdcgi
  CCLD     rrdcached
make[2]: Leaving directory `/usr/local/src/rrdtool-1.7.1/src'
make[1]: Leaving directory `/usr/local/src/rrdtool-1.7.1/src'
Making all in bindings
make[1]: Entering directory `/usr/local/src/rrdtool-1.7.1/bindings'
make[2]: Entering directory `/usr/local/src/rrdtool-1.7.1/bindings'
mkdir -p ./perl-piped
mkdir -p ./perl-shared
( cd ./perl-piped \
  && ( test -e Makefile.PL || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-piped/Makefile.PL ) \
  && ( test -e RRDp.pm || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-piped/RRDp.pm ) \
  && ( test -e t || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-piped/t ) \
          && env \
             ABS_TOP_SRCDIR=/usr/local/src/rrdtool-1.7.1 \
             ABS_TOP_BUILDDIR=/usr/local/src/rrdtool-1.7.1 \
             ABS_SRCDIR=/usr/local/src/rrdtool-1.7.1/bindings/perl-piped \
             /usr/bin/perl Makefile.PL PREFIX=/usr/local/rrdtool INSTALL_BASE= LIB=/usr/local/rrdtool/lib/perl/5.16.3 \
          && make )
( cd ./perl-shared \
  && ( test -e Makefile.PL || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-shared/Makefile.PL ) \
  && ( test -e RRDs.pm || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-shared/RRDs.pm ) \
  && ( test -e RRDs.ppd || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-shared/RRDs.ppd ) \
  && ( test -e RRDs.xs || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-shared/RRDs.xs ) \
  && ( test -e t || ln -s /usr/local/src/rrdtool-1.7.1/bindings/perl-shared/t ) \
          && env \
             ABS_TOP_SRCDIR=/usr/local/src/rrdtool-1.7.1 \
             ABS_TOP_BUILDDIR=/usr/local/src/rrdtool-1.7.1 \
             ABS_SRCDIR=/usr/local/src/rrdtool-1.7.1/bindings/perl-shared \
             /usr/bin/perl Makefile.PL  PREFIX=/usr/local/rrdtool INSTALL_BASE= LIB=/usr/local/rrdtool/lib/perl/5.16.3 RPATH=/usr/local/rrdtool/lib \
          && make )
Checking if your kit is complete...
Checking if your kit is complete...
Looks good
Looks good
Writing Makefile for RRDp
Writing Makefile for RRDs
make[3]: Entering directory `/usr/local/src/rrdtool-1.7.1/bindings/perl-piped'
make[3]: Entering directory `/usr/local/src/rrdtool-1.7.1/bindings/perl-shared'
cp RRDp.pm blib/lib/RRDp.pm
/usr/bin/perl /usr/share/perl5/vendor_perl/ExtUtils/xsubpp  -typemap /usr/share/perl5/ExtUtils/typemap  RRDs.xs > RRDs.xsc && mv RRDs.xsc RRDs.c
cp RRDs.pm blib/lib/RRDs.pm
Running Mkbootstrap for RRDs ()
chmod 644 RRDs.bs
cp RRDs.bs blib/arch/auto/RRDs/RRDs.bs
chmod 644 blib/arch/auto/RRDs/RRDs.bs
Manifying blib/man3/RRDp.3pm
make[3]: Leaving directory `/usr/local/src/rrdtool-1.7.1/bindings/perl-piped'
gcc -c  -I/usr/local/src/rrdtool-1.7.1/src -I/usr/local/src/rrdtool-1.7.1/src -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"1.7001\" -DXS_VERSION=\"1.7001\" -fPIC "-I/usr/lib64/perl5/CORE"  -DPERLPATCHLEVEL=16 RRDs.c
In file included from /usr/lib64/perl5/CORE/perl.h:5012:0,
                 from RRDs.xs:6:
RRDs.xs: In function ‘rrd_fetch_cb_wrapper’:
/usr/lib64/perl5/CORE/pp.h:125:16: warning: value computed is not used [-Wunused-value]
 #define POPs  (*sp--)
                ^
RRDs.xs:178:9: note: in expansion of macro ‘POPs’
         POPs; /* there is undef on top of the stack when there is an error
         ^
RRDs.c: In function ‘XS_RRDs_graph’:
RRDs.c:606:7: warning: unused variable ‘RETVAL’ [-Wunused-variable]
  SV * RETVAL;
       ^
RRDs.c: In function ‘XS_RRDs_fetch’:
RRDs.c:669:7: warning: unused variable ‘RETVAL’ [-Wunused-variable]
  SV * RETVAL;
       ^
RRDs.c: In function ‘XS_RRDs_fetch_cb_register’:
RRDs.c:728:7: warning: unused variable ‘RETVAL’ [-Wunused-variable]
  SV * RETVAL;
       ^
RRDs.c: In function ‘XS_RRDs_times’:
RRDs.c:759:7: warning: unused variable ‘RETVAL’ [-Wunused-variable]
  SV * RETVAL;
       ^
In file included from RRDs.xs:7:0:
RRDs.c: In function ‘XS_RRDs_xport’:
/usr/lib64/perl5/CORE/XSUB.h:175:28: warning: unused variable ‘targ’ [-Wunused-variable]
 #define dXSTARG SV * const targ = ((PL_op->op_private & OPpENTERSUB_HASTARG) \
                            ^
RRDs.c:800:2: note: in expansion of macro ‘dXSTARG’
  dXSTARG;
  ^
RRDs.c:799:6: warning: unused variable ‘RETVAL’ [-Wunused-variable]
  int RETVAL;
      ^
RRDs.c: In function ‘XS_RRDs_list’:
RRDs.c:1008:7: warning: unused variable ‘RETVAL’ [-Wunused-variable]
  SV * RETVAL;
       ^
rm -f blib/arch/auto/RRDs/RRDs.so
gcc  -shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wl,-z,relro  RRDs.o -L/usr/local/src/rrdtool-1.7.1/src/.libs/ -Wl,--rpath -Wl,/usr/local/rrdtool/lib -lrrd  -o blib/arch/auto/RRDs/RRDs.so 	\
     	\
  
chmod 755 blib/arch/auto/RRDs/RRDs.so
Manifying blib/man3/RRDs.3pm
make[3]: Leaving directory `/usr/local/src/rrdtool-1.7.1/bindings/perl-shared'
mkdir -p ./perl-shared
make[2]: Leaving directory `/usr/local/src/rrdtool-1.7.1/bindings'
make[1]: Leaving directory `/usr/local/src/rrdtool-1.7.1/bindings'
Making all in tests
make[1]: Entering directory `/usr/local/src/rrdtool-1.7.1/tests'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/usr/local/src/rrdtool-1.7.1/tests'
Making all in etc
make[1]: Entering directory `/usr/local/src/rrdtool-1.7.1/etc'
make[1]: *** No rule to make target `etc/rrdcached.socket', needed by `all-am'.  Stop.
make[1]: Leaving directory `/usr/local/src/rrdtool-1.7.1/etc'
make: *** [all-recursive] Error 1

1.7.0 version no issue

**Comment by c72578** [comment]
Thanks for your report:
This has already been fixed in master by:
https://github.com/oetiker/rrdtool-1.x/commit/865a9bade72f93cf72ca59954c6df01e8c48915d
and will be included in RRDtool version 1.7.2

**Comment by akarelas-pt** [comment]
When will 1.7.2 come out? I have the same issue.

**Comment by whsir** [comment]
@akarelas-pt 1.7.2版本已发布

**Comment by c72578** [comment]
Thanks for your report.
In the meantime, v1.7.2 has been released, where this is fixed.
https://github.com/oetiker/rrdtool-1.x/releases
