### ISSUE TITLE
Outdated doc/name.inc file - file still needed?

### ISSUE THREAD

**Issue by c72578** [oetiker/rrdtool-1.x#968]
**Describe the bug**
The file doc/name.inc contains outdated information, e.g.:
WARNING: DO NOT EDIT THE POD FILES. THEY ARE AUTO-GENERATED
Documentation for version 1.2.0

Should this file be updated, is it still needed?

**To Reproduce**
NA

**Expected behavior**
Up to date info is expected in this file or removal of file, if not needed any more.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: NA
 - Browser NA
 - Version: Current master at 1e92f1affeebca020855ebb9f1263192b25d5204 or 1.7.1

**Smartphone (please complete the following information):**
 - NA

**Additional context**
- File:
https://github.com/oetiker/rrdtool-1.x/blob/master/doc/name.inc

**Comment by oetiker** [comment]
The file is obsoltet

**Comment by c72578** [comment]
OK, thanks for the info
