### ISSUE TITLE
New RPN Function ROUND

### ISSUE THREAD

**Issue by TheWitness** [oetiker/rrdtool-1.x#975]
**Is your feature request related to a problem? Please describe.**
Presently we have CDEF functions CEIL and FLOOR, but suspiciously absent is the ROUND function.  Am I missing something?

**Describe the solution you'd like**
Just this kind of pedestrian statistical function.  If my LINEX is 1.8, make it 2.0, if it's 1.45, make it 1.

**Describe alternatives you've considered**
I tried FLOOR and CEIL, but they did just what they were supposed to do, and did not ROUND

**Comment by oetiker** [comment]
:-) seems no-one has missed it yet ... but go ahead ... PR!

**Comment by TheWitness** [comment]
@oetiker, good to find you well.  let me see what I can do.

**Comment by TheWitness** [comment]
Done.  https://github.com/oetiker/rrdtool-1.x/pull/976

**Comment by c72578** [comment]
Merged into master.
Commit: https://github.com/oetiker/rrdtool-1.x/commit/fe0c1b81b752361ce40b485f16c4dbd72d16f7df
